(() => {
  'use strict';

  const CFG=window.LW_R02_CONFIG, R=window.LW_R02_RULES;
  if(!CFG||!R)return;
  const {BUILD,FIXTURE,PARAM_REV,DESIGN_BASELINE,PARAMS:P,ENEMY}=CFG;
  const laneIds=R.LANE_IDS;
  const laneMeta={north:{y:16,index:0},mid:{y:0,index:1},south:{y:-16,index:2}};
  const $=id=>document.getElementById(id);
  const canvas=$('battlefield'),fatal=$('fatal'),rotate=$('rotateInterstitial');
  const gl=canvas.getContext('webgl2',{alpha:false,antialias:true,depth:true,powerPreference:'high-performance'});
  if(!gl){fatal.hidden=false;return;}
  window.__LW_BUILD__=BUILD;

  const vs=`#version 300 es
  precision highp float;
  layout(location=0) in vec3 aPosition;layout(location=1) in vec3 aNormal;
  uniform vec3 uPos;uniform vec3 uSize;uniform vec2 uCamera;uniform vec2 uHalfView;uniform vec3 uColor;uniform float uTilt;
  out vec3 vColor;out float vLight;
  void main(){vec3 world=aPosition*uSize+uPos;vec3 p=world-vec3(uCamera,0.0);float c=cos(uTilt),s=sin(uTilt);float sy=p.y*c+p.z*s;float depth=p.y*s-p.z*c;gl_Position=vec4(p.x/uHalfView.x,sy/uHalfView.y,depth/120.0,1.0);vec3 ld=normalize(vec3(-.45,-.35,1.0));vLight=.62+.38*max(dot(normalize(aNormal),ld),0.0);vColor=uColor;}`;
  const fs=`#version 300 es
  precision highp float;in vec3 vColor;in float vLight;out vec4 outColor;void main(){outColor=vec4(vColor*vLight,1.0);}`;
  function compile(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s;}
  const program=gl.createProgram();gl.attachShader(program,compile(gl.VERTEX_SHADER,vs));gl.attachShader(program,compile(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program));gl.useProgram(program);
  const verts=[],norms=[];const faces=[[[0,0,1],[-.5,-.5,.5],[.5,-.5,.5],[.5,.5,.5],[-.5,.5,.5]],[[0,0,-1],[-.5,.5,-.5],[.5,.5,-.5],[.5,-.5,-.5],[-.5,-.5,-.5]],[[0,1,0],[-.5,.5,.5],[.5,.5,.5],[.5,.5,-.5],[-.5,.5,-.5]],[[0,-1,0],[-.5,-.5,-.5],[.5,-.5,-.5],[.5,-.5,.5],[-.5,-.5,.5]],[[1,0,0],[.5,-.5,.5],[.5,-.5,-.5],[.5,.5,-.5],[.5,.5,.5]],[[-1,0,0],[-.5,-.5,-.5],[-.5,-.5,.5],[-.5,.5,.5],[-.5,.5,-.5]]];
  for(const [n,a,b,c,d] of faces)for(const v of [a,b,c,a,c,d]){verts.push(...v);norms.push(...n)}
  const vao=gl.createVertexArray();gl.bindVertexArray(vao);
  const pbo=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,pbo);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.STATIC_DRAW);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,0,0);
  const nbo=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,nbo);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(norms),gl.STATIC_DRAW);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,3,gl.FLOAT,false,0,0);
  const U={pos:gl.getUniformLocation(program,'uPos'),size:gl.getUniformLocation(program,'uSize'),camera:gl.getUniformLocation(program,'uCamera'),halfView:gl.getUniformLocation(program,'uHalfView'),color:gl.getUniformLocation(program,'uColor'),tilt:gl.getUniformLocation(program,'uTilt')};
  const C={ground:[.10,.14,.15],lane:[.22,.26,.24],shoulder:[.14,.19,.19],friend:[.84,.62,.23],friend2:[.50,.75,.64],enemy:[.74,.29,.26],enemy2:[.90,.47,.38],commander:[.98,.80,.32],rival:[.96,.36,.34],bastion:[.35,.63,.56],guard:[.65,.25,.23],gate:[.48,.37,.23],core:[.29,.48,.55],tower:[.38,.44,.46],pylon:[.48,.66,.57],junction:[.30,.40,.39],presence:[.27,.49,.45],route:[.75,.68,.34],danger:[.90,.41,.34]};
  function box(x,y,z,sx,sy,sz,color){gl.uniform3f(U.pos,x,y,z);gl.uniform3f(U.size,sx,sy,sz);gl.uniform3fv(U.color,color);gl.drawArrays(gl.TRIANGLES,0,36)}
  function bar(x,y,z,w,h,ratio,back,fill){box(x,y,z,w,h,.11,back);const fw=Math.max(.05,w*Math.max(0,Math.min(1,ratio)));box(x-(w-fw)/2,y,z+.08,fw,h*.72,.11,fill)}

  const camera={x:-25,y:0,zoom:1,tilt:.38};
  const pointers=new Map();let gesture=null;const DRAG=9;
  let phase='deploy',selectedLane='north',waypointTargeting=false,simSpeed=1;
  let actorSeq=0,projectileSeq=0,fixedAccumulator=0,lastFrame=performance.now(),lastRecoveryAt=-Infinity;
  let deployment=R.clone(R.PRESETS.siegeDelay);
  let currentRun=null,telemetryMuted=false;
  const recoveryEvents=[];
  const RECOVERY_KEY='lane-warden:M1-0.4.0:R02-A:recovery:v1';
  const SNAPSHOT_SCHEMA=2;

  function orderedGuards(laneId){const count=P.guardPositions[laneId]||1;return Array.from({length:count},(_,i)=>({index:i,hp:P.guardHp,max:P.guardHp,broken:false,x:42+i*5,hits:[]}));}
  function newLane(id){return{id,y:laneMeta[id].y,bastion:{hp:P.bastionHp,max:P.bastionHp,broken:false,hits:[]},guards:orderedGuards(id),towers:[],overdriveUntil:0,frontX:-8,pressure:'below',warningStage:0};}
  const world={};
  function makeCommander(){return{x:-48,y:laneMeta.north.y,lane:'north',hp:P.commanderHp,max:P.commanderHp,path:[],attackCd:0,incapacitated:false,reformAt:0,endangered:false};}
  function makeRival(){return{x:30,y:laneMeta.mid.y,lane:'mid',targetLane:'mid',hp:P.rivalHp,max:P.rivalHp,path:[],attackCd:0,incapacitated:false,reformAt:0,nextDecision:10,intentReason:'probing middle pressure'};}
  function resetWorld(){
    Object.assign(world,{time:0,actors:[],projectiles:[],lanes:{north:newLane('north'),mid:newLane('mid'),south:newLane('south')},gate:{hp:P.gateHp,max:P.gateHp,vulnerable:false},core:{hp:P.coreHp,max:P.coreHp},commander:makeCommander(),rival:makeRival(),gold:P.initialGold,nextPlayerPulse:1,nextEnemy:{north:P.enemyInitial.north,mid:P.enemyInitial.mid,south:P.enemyInitial.south},enemyPulseIndex:{north:0,mid:0,south:0},rallyReady:0,rallyUntil:0,waypointReady:0,interventionReady:0,result:null});
    selectedLane='north';waypointTargeting=false;camera.x=-25;camera.y=0;camera.zoom=1;fixedAccumulator=0;lastRecoveryAt=-Infinity;
  }
  resetWorld();

  const evidence={schema:5,build:BUILD,designBaseline:DESIGN_BASELINE,fixture:FIXTURE,parameterRevision:PARAM_REV,parameterSet:P,tuningStatus:'exploratory R-02 structural parameterization; not canonical encounter balance or formal acceptance evidence',structuralClaims:{threeLanes:true,unitCapacity:8,towerCapacity:6,authoredJunctions:true,rivalLifecycle:true,rivalLaneStripMarker:true,orderedGuardLineModel:true,deterministicRecovery:true},startedAt:new Date().toISOString(),runs:[]};
  function ev(type,detail={}){if(!currentRun||telemetryMuted)return;currentRun.events.push({t:+world.time.toFixed(2),type,...detail});if(currentRun.events.length>1400)currentRun.events.shift();}

  function deploymentSummary(){return R.deploymentLegal(deployment)}
  function unitControl(lane,id){const u=R.UNITS[id],n=deployment[lane].units[id];return `<div class="unit-control"><strong>${u.name}</strong><small>${u.cost} Unit · ${u.role}</small><div class="stepper"><button type="button" data-step="-1" data-lane="${lane}" data-unit="${id}">−</button><b>${n}</b><button type="button" data-step="1" data-lane="${lane}" data-unit="${id}">+</button></div></div>`}
  function towerOptions(selected){return Object.values(R.TOWERS).map(t=>`<option value="${t.id}" ${selected===t.id?'selected':''}>${t.name} · ${t.cost}</option>`).join('')}
  function renderDeployment(){
    $('deployLanes').innerHTML=laneIds.map(lane=>`<section class="deploy-lane"><h2>${lane.toUpperCase()}</h2><div class="unit-grid">${Object.keys(R.UNITS).map(id=>unitControl(lane,id)).join('')}</div><div class="tower-row"><label>Rear<select data-tower-lane="${lane}" data-slot="rear">${towerOptions(deployment[lane].towers.rear)}</select></label><label>Central<select data-tower-lane="${lane}" data-slot="central">${towerOptions(deployment[lane].towers.central)}</select></label><label>Forward<select data-tower-lane="${lane}" data-slot="forward">${towerOptions(deployment[lane].towers.forward)}</select></label></div></section>`).join('');
    document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{const lane=b.dataset.lane,id=b.dataset.unit,delta=+b.dataset.step;deployment[lane].units[id]=Math.max(0,deployment[lane].units[id]+delta);renderDeployment();});
    document.querySelectorAll('[data-tower-lane]').forEach(s=>s.onchange=()=>{deployment[s.dataset.towerLane].towers[s.dataset.slot]=s.value;renderDeployment();});
    const ck=deploymentSummary();$('unitBudget').textContent=`Unit ${ck.unitTotal} / ${R.UNIT_CAP}`;$('towerBudget').textContent=`Tower ${ck.towerTotal} / ${R.TOWER_CAP}`;$('unitBudget').classList.toggle('over',ck.unitTotal>R.UNIT_CAP);$('towerBudget').classList.toggle('over',ck.towerTotal>R.TOWER_CAP);$('startBattle').disabled=!ck.legal;$('deployVerdict').textContent=ck.legal?'Legal deployment':ck.errors.join(' · ');$('deployNote').textContent=ck.legal?'Deployment locks when battle begins.':'Adjust the plan before starting.';
  }
  document.querySelectorAll('[data-deploy-preset]').forEach(b=>b.onclick=()=>{deployment=R.clone(R.PRESETS[b.dataset.deployPreset]);document.querySelectorAll('[data-deploy-preset]').forEach(x=>x.classList.toggle('active',x===b));renderDeployment();});

  function buildTowers(){for(const laneId of laneIds){const lane=world.lanes[laneId];for(const slot of ['rear','central','forward']){const id=deployment[laneId].towers[slot];if(id==='none')continue;const t=R.TOWERS[id];const x=slot==='rear'?-47:slot==='central'?-14:14;const y=lane.y+(slot==='central'?-4.6:4.6);lane.towers.push({id,type:id,slot,x,y,hp:t.hp,max:t.hp,cd:0,dead:false});}}}
  function startBattle(){
    const ck=deploymentSummary();if(!ck.legal)return;clearRecovery('new-battle');resetWorld();buildTowers();phase='battle';$('deployment').hidden=true;$('battleHud').hidden=false;$('battleResult').hidden=true;
    currentRun={runId:crypto.randomUUID?.()||String(Date.now()),startedAt:new Date().toISOString(),deployment:R.clone(deployment),parameterRevision:PARAM_REV,events:[],snapshots:[],debrief:{globalRead:null,rivalChanged:null,rivalPredict:null},metrics:{goldSpent:0,goldEarned:0,pulses:{north:0,mid:0,south:0},enemyPulses:{north:0,mid:0,south:0},guardBreakTimes:{north:null,mid:null,south:null},guardPositionBreaks:[],bastionBreaks:[],commanderIncapacitations:0,rivalIncapacitations:0,rivalDecisions:0,playerLaneTransitions:0,waypoints:0,laneStripJumps:{north:0,mid:0,south:0},attentionFocus:0,kills:{local:0,remote:0},interventions:{push:0,overdrive:0}},result:null,nextSnapshotAt:10};
    evidence.runs.push(currentRun);document.querySelectorAll('[data-debrief-key]').forEach(x=>x.classList.remove('selected-choice'));closeActionDrawer();closeLab();ev('battle-start',{deployment:R.clone(deployment),note:'R02-A structural parameterization'});persistRecovery('battle-start');updateUI();
  }
  $('startBattle').onclick=startBattle;$('redeployButton').onclick=returnToDeployment;$('resetBattle').onclick=returnToDeployment;
  function returnToDeployment(){if(currentRun&&!currentRun.result&&phase==='battle'){ev('battle-aborted');currentRun.endedAt=new Date().toISOString();}clearRecovery('return-to-deployment');phase='deploy';closeActionDrawer();closeLab();$('deployment').hidden=false;$('battleHud').hidden=true;$('battleResult').hidden=true;resetWorld();renderDeployment();updateUI();}

  function laneJitter(id){return((id%5)-2)*.58}
  function spawnActor(team,laneId,templateId,x,extra={}){const base=team===1?R.UNITS[templateId]:ENEMY[templateId],id=++actorSeq;const a={id,team,lane:laneId,x,y:laneMeta[laneId].y+laneJitter(id),z:1,templateId,role:base.role,hp:base.hp,max:base.hp,damage:base.damage,range:base.range,speed:base.speed,cadence:base.cadence,structure:base.structure,cd:0,slowUntil:0,dead:false,...extra};world.actors.push(a);return a;}
  function spawnPlayerPulse(laneId,source='scheduled'){const units=deployment[laneId].units;let offset=0,count=0;for(const [id,n] of Object.entries(units))for(let i=0;i<n;i++){spawnActor(1,laneId,id,-67-offset);offset+=1.5;count++;}if(count){currentRun.metrics.pulses[laneId]++;ev('player-pulse',{lane:laneId,source,count,types:R.committedTypes(deployment,laneId)});}return count;}
  function spawnReinforcement(laneId){const types=R.committedTypes(deployment,laneId);let offset=0;for(const id of types){spawnActor(1,laneId,id,-67-offset);offset+=1.5;}if(types.length){currentRun.metrics.pulses[laneId]++;ev('player-pulse',{lane:laneId,source:'gold-push',count:types.length,types});}return types.length;}
  function spawnEnemyPulse(laneId){const idx=world.enemyPulseIndex[laneId]++,recipe=CFG.enemyRecipe(laneId,idx);let offset=0;for(const id of recipe){spawnActor(-1,laneId,id,60+offset);offset+=1.5;}currentRun.metrics.enemyPulses[laneId]++;ev('enemy-pulse',{lane:laneId,index:idx,count:recipe.length,types:recipe});}
  function nearestActor(a,team,maxRange=Infinity){let best=null,dist=Infinity;for(const b of world.actors){if(b.dead||b.team!==team||b.lane!==a.lane)continue;const d=Math.abs(b.x-a.x);if(d<dist&&d<=maxRange){dist=d;best=b}}return best;}
  function activeGuard(lane){return lane.guards.find(g=>!g.broken)||null}
  function laneGuardBroken(lane){return lane.guards.every(g=>g.broken)}
  function damageGuard(lane,a,amount){const g=activeGuard(lane);if(!g)return false;g.hp=Math.max(0,g.hp-amount);if(g.hp<=0&&!g.broken){g.broken=true;currentRun.metrics.guardPositionBreaks.push({lane:lane.id,index:g.index,t:+world.time.toFixed(2)});ev('guard-position-broken',{lane:lane.id,index:g.index});if(laneGuardBroken(lane)){currentRun.metrics.guardBreakTimes[lane.id]=+world.time.toFixed(2);world.gate.vulnerable=true;ev('guard-line-broken',{lane:lane.id});attention(`${lane.id.toUpperCase()} BREACH OPEN`,'Gate is vulnerable. Decide whether to finish or rotate.',lane.id,'warning');}}return true;}
  function alliedBuff(a){let m=1;const lane=world.lanes[a.lane];for(const t of lane.towers)if(!t.dead&&t.type==='pylon'&&Math.abs(a.x-t.x)<=R.TOWERS.pylon.radius)m*=R.TOWERS.pylon.buff;if(world.time<lane.overdriveUntil)m*=P.overdriveMultiplier;if(world.time<world.rallyUntil&&Math.abs(a.x-world.commander.x)<=P.presenceRadius&&a.lane===world.commander.lane)m*=P.rallyDamage;if(!world.commander.incapacitated&&a.lane===world.commander.lane&&Math.abs(a.x-world.commander.x)<=P.presenceRadius)m*=P.presenceDamage;return m;}
  function enemyBuff(a){if(world.rival.incapacitated||a.lane!==world.rival.lane)return 1;return Math.abs(a.x-world.rival.x)<=P.rivalInfluenceRadius?P.rivalInfluenceDamage:1;}
  function killActor(a,killerTeam){if(a.dead)return;a.dead=true;if(killerTeam===1&&a.team===-1){const local=!world.commander.incapacitated&&a.lane===world.commander.lane&&Math.abs(a.x-world.commander.x)<=P.presenceRadius;const gain=local?P.fullGold:P.remoteGold;world.gold+=gain;currentRun.metrics.goldEarned+=gain;currentRun.metrics.kills[local?'local':'remote']++;}}
  function attackActor(attacker,target,mult=1){target.hp-=attacker.damage*mult;attacker.cd=attacker.cadence;if(target.hp<=0)killActor(target,attacker.team);}
  function tickActor(a,dt){if(a.dead)return;a.cd=Math.max(0,a.cd-dt);const dir=a.team===1?1:-1;const target=nearestActor(a,-a.team,a.range+1.2);if(target&&a.cd<=0){attackActor(a,target,a.team===1?alliedBuff(a):enemyBuff(a));return;}const lane=world.lanes[a.lane];
    if(a.team===1){const rival=world.rival;if(!rival.incapacitated&&rival.lane===a.lane&&Math.abs(rival.x-a.x)<=a.range+1.2){if(a.cd<=0){rival.hp-=a.damage*alliedBuff(a);a.cd=a.cadence;if(rival.hp<=0)incapacitateRival();}return;}const g=activeGuard(lane);if(g){const d=g.x-a.x;if(d<=a.range+1.5){if(a.cd<=0){damageGuard(lane,a,a.damage*a.structure*alliedBuff(a));a.cd=a.cadence;}return;}}else if(world.gate.vulnerable&&60-a.x<=a.range+2){if(a.cd<=0){world.gate.hp=Math.max(0,world.gate.hp-a.damage*a.structure*alliedBuff(a));a.cd=a.cadence;}return;}}
    else{const tower=lane.towers.filter(t=>!t.dead).sort((x,y)=>Math.abs(x.x-a.x)-Math.abs(y.x-a.x))[0];if(tower&&Math.abs(tower.x-a.x)<=a.range+1.2){if(a.cd<=0){tower.hp=Math.max(0,tower.hp-a.damage*a.structure*enemyBuff(a));a.cd=a.cadence;if(tower.hp<=0){tower.dead=true;ev('tower-destroyed',{lane:a.lane,slot:tower.slot,type:tower.type});}}return;}if(!lane.bastion.broken){const d=a.x-(-57);if(d<=a.range+1.6){if(a.cd<=0){lane.bastion.hp=Math.max(0,lane.bastion.hp-a.damage*a.structure*enemyBuff(a));a.cd=a.cadence;}return;}}else if(a.x-(-67)<=a.range+2){if(a.cd<=0){world.core.hp=Math.max(0,world.core.hp-a.damage*a.structure*enemyBuff(a));a.cd=a.cadence;}return;}}
    const speed=a.speed*(world.time<(a.slowUntil||0)?.0.55:1);a.x+=dir*speed*dt;
  }
  function tickTowers(dt){for(const laneId of laneIds){const lane=world.lanes[laneId];for(const t of lane.towers){if(t.dead)continue;t.cd=Math.max(0,t.cd-dt);if(t.type==='pylon')continue;const spec=R.TOWERS[t.type];let best=null,dist=Infinity;for(const a of world.actors){if(a.dead||a.team!==-1||a.lane!==laneId)continue;const d=Math.abs(a.x-t.x);if(d<dist&&d<=spec.range){dist=d;best=a}}if(best&&t.cd<=0){best.hp-=spec.damage;if(spec.slow)best.slowUntil=Math.max(best.slowUntil,world.time+spec.slowSeconds);t.cd=spec.cadence;if(best.hp<=0)killActor(best,1);}}}}
  function tickGuards(dt){for(const laneId of laneIds){const lane=world.lanes[laneId];for(const g of lane.guards)if(!g.broken&&g.hp<g.max)g.hp=Math.min(g.max,g.hp+P.guardRegen*dt);}}
  function tickBastions(){for(const laneId of laneIds){const lane=world.lanes[laneId];if(!lane.bastion.broken&&lane.bastion.hp<=0){lane.bastion.broken=true;currentRun.metrics.bastionBreaks.push({lane:laneId,t:+world.time.toFixed(2)});ev('bastion-broken',{lane:laneId});attention(`${laneId.toUpperCase()} BASTION LOST`,'Core is now exposed from this lane.',laneId,'critical');}}}

  function chooseJunction(x){return P.junctionXs.reduce((best,j)=>Math.abs(j-x)<Math.abs(best-x)?j:best,P.junctionXs[0])}
  function routeBetween(x,y,targetX,targetLane){const targetY=laneMeta[targetLane].y;const startLane=laneIds.reduce((best,l)=>Math.abs(laneMeta[l].y-y)<Math.abs(laneMeta[best].y-y)?l:best,laneIds[0]);if(startLane===targetLane)return[{x:targetX,y:targetY}];const j=chooseJunction(x);const path=[{x:j,y:laneMeta[startLane].y}];let i=laneMeta[startLane].index,goal=laneMeta[targetLane].index;while(i!==goal){i+=i<goal?1:-1;path.push({x:j,y:laneMeta[laneIds[i]].y});}path.push({x:targetX,y:targetY});return path;}
  function moveAlong(entity,dt,speed,onArrive){if(!entity.path.length)return;const p=entity.path[0],dx=p.x-entity.x,dy=p.y-entity.y,d=Math.hypot(dx,dy);if(d<=speed*dt+.02){entity.x=p.x;entity.y=p.y;entity.path.shift();if(!entity.path.length&&onArrive)onArrive();return;}entity.x+=dx/d*speed*dt;entity.y+=dy/d*speed*dt;}
  function orderCommander(targetX,targetLane,source='ground'){if(world.commander.incapacitated)return;const from=world.commander.lane;world.commander.path=routeBetween(world.commander.x,world.commander.y,targetX,targetLane);world.commander.lane=targetLane;if(from!==targetLane){currentRun.metrics.playerLaneTransitions++;ev('commander-lane-order',{from,to:targetLane,source,junctionX:chooseJunction(world.commander.x)});}else ev('commander-order',{lane:targetLane,x:+targetX.toFixed(1),source});}
  function tickCommander(dt){const c=world.commander;if(c.incapacitated){if(world.time>=c.reformAt){c.incapacitated=false;c.hp=c.max;c.x=-62;c.y=laneMeta.mid.y;c.lane='mid';c.path=[];ev('commander-reformed',{lane:'mid'});}return;}moveAlong(c,dt,5.2,()=>ev('commander-arrived',{lane:c.lane,x:+c.x.toFixed(1)}));c.attackCd=Math.max(0,c.attackCd-dt);let target=nearestActor({lane:c.lane,x:c.x},-1,P.commanderRange);const rival=world.rival;if(!rival.incapacitated&&rival.lane===c.lane&&Math.abs(rival.x-c.x)<=P.commanderRange){if(!target||Math.abs(rival.x-c.x)<Math.abs(target.x-c.x))target=rival;}if(target&&c.attackCd<=0){target.hp-=P.commanderDamage;c.attackCd=P.commanderCadence;if(target===rival&&target.hp<=0)incapacitateRival();else if(target!==rival&&target.hp<=0)killActor(target,1);}const hostile=nearestActor({lane:c.lane,x:c.x},-1,2.8);if(hostile)damageCommander(hostile.damage*dt*.55*enemyBuff(hostile));if(!rival.incapacitated&&rival.lane===c.lane&&Math.abs(rival.x-c.x)<=P.rivalRange)damageCommander(P.rivalDamage*dt*.45);const endangered=!c.incapacitated&&c.hp/c.max<=.30;if(endangered&&!c.endangered){c.endangered=true;ev('commander-endangered',{lane:c.lane,hpPct:+(c.hp/c.max*100).toFixed(1)});attention('COMMANDER ENDANGERED','Disengage, Waypoint, or accept reform downtime.',c.lane,'critical');}if(!endangered)c.endangered=false;}
  function damageCommander(amount){const c=world.commander;if(c.incapacitated)return;c.hp-=amount;if(c.hp<=0){c.hp=0;c.incapacitated=true;c.reformAt=world.time+P.reformSeconds;c.path=[];currentRun.metrics.commanderIncapacitations++;ev('commander-incapacitated',{lane:c.lane,reformAt:+c.reformAt.toFixed(2)});attention('COMMANDER INCAPACITATED','Presence and abilities are offline until reform.',c.lane,'critical');}}

  function rivalScore(laneId){const lane=world.lanes[laneId],friendlies=world.actors.filter(a=>!a.dead&&a.team===1&&a.lane===laneId),front=friendlies.length?Math.max(...friendlies.map(a=>a.x)):-68;const absent=world.commander.incapacitated||world.commander.lane!==laneId?12:0;const breach=laneGuardBroken(lane)?18:0;const bastionDamage=(1-lane.bastion.hp/lane.bastion.max)*8;return front*.13+absent+breach+bastionDamage;}
  function decideRival(){if(world.rival.incapacitated)return;const scored=laneIds.map(l=>({lane:l,score:rivalScore(l)})).sort((a,b)=>b.score-a.score);let choice=scored[0];if(choice.lane===world.rival.lane&&scored[1]&&scored[1].score>choice.score-3)choice=scored[1];const lane=world.lanes[choice.lane];const reason=laneGuardBroken(lane)?'punishing the open breach':(world.commander.incapacitated||world.commander.lane!==choice.lane)?'exploiting your absence':'contesting your strongest visible pressure';const from=world.rival.lane;world.rival.targetLane=choice.lane;world.rival.intentReason=reason;world.rival.path=routeBetween(world.rival.x,world.rival.y,8,choice.lane);world.rival.lane=choice.lane;world.rival.nextDecision=world.time+P.rivalDecisionCadence;currentRun.metrics.rivalDecisions++;ev('rival-decision',{from,to:choice.lane,reason,scores:Object.fromEntries(scored.map(s=>[s.lane,+s.score.toFixed(2)]))});showRivalIntent(choice.lane,reason);}
  function tickRival(dt){const r=world.rival;if(r.incapacitated){if(world.time>=r.reformAt){r.incapacitated=false;r.hp=r.max;r.x=52;r.y=laneMeta.mid.y;r.lane='mid';r.targetLane='mid';r.path=[];r.nextDecision=world.time+5;ev('rival-reformed',{lane:'mid'});showRivalIntent('mid','reformed at the enemy anchor');}return;}if(world.time>=r.nextDecision)decideRival();moveAlong(r,dt,P.rivalSpeed,()=>ev('rival-arrived',{lane:r.lane,x:+r.x.toFixed(1)}));r.attackCd=Math.max(0,r.attackCd-dt);const c=world.commander;if(!c.incapacitated&&c.lane===r.lane&&Math.abs(c.x-r.x)<=P.rivalRange&&r.attackCd<=0){damageCommander(P.rivalDamage);r.attackCd=P.rivalCadence;return;}const target=nearestActor({lane:r.lane,x:r.x},1,P.rivalRange);if(target&&r.attackCd<=0){target.hp-=P.rivalDamage;r.attackCd=P.rivalCadence;if(target.hp<=0)killActor(target,-1);}}
  function incapacitateRival(){const r=world.rival;if(r.incapacitated)return;r.hp=0;r.incapacitated=true;r.path=[];r.reformAt=world.time+P.rivalReformSeconds;currentRun.metrics.rivalIncapacitations++;ev('rival-incapacitated',{lane:r.lane,reformAt:+r.reformAt.toFixed(2),reward:'macro-window-only'});showRivalIntent(r.lane,'incapacitated — temporary macro window');}

  function updateFronts(){for(const laneId of laneIds){const f=world.actors.filter(a=>!a.dead&&a.team===1&&a.lane===laneId),e=world.actors.filter(a=>!a.dead&&a.team===-1&&a.lane===laneId);const fx=f.length?Math.max(...f.map(a=>a.x)):-66,ex=e.length?Math.min(...e.map(a=>a.x)):60;world.lanes[laneId].frontX=(fx+ex)/2;const g=activeGuard(world.lanes[laneId]);if(!g)world.lanes[laneId].pressure='broken';else{const close=f.filter(a=>g.x-a.x<12).reduce((s,a)=>s+a.damage*a.structure*alliedBuff(a)/Math.max(.2,a.cadence),0);world.lanes[laneId].pressure=close<P.guardRegen*.85?'below':close<P.guardRegen*1.15?'near':'above';}}}
  function checkWarnings(){for(const laneId of laneIds){const lane=world.lanes[laneId],pct=lane.bastion.hp/lane.bastion.max;let stage=pct<=.35?2:pct<=.75?1:0;if(stage>lane.warningStage){lane.warningStage=stage;if(stage===1)attention(`${laneId.toUpperCase()} BASTION UNDER PRESSURE`,`${Math.round(pct*100)}% remaining · decide whether to rotate or accept the clock.`,laneId,'warning');else attention(`${laneId.toUpperCase()} BASTION CRITICAL`,`${Math.round(pct*100)}% remaining · loss is now close.`,laneId,'critical');ev(stage===1?'bastion-warning':'bastion-critical',{lane:laneId,hpPct:+(pct*100).toFixed(1)});}}}
  function checkResult(){if(world.gate.hp<=0){world.gate.hp=0;finishBattle('win');}else if(world.core.hp<=0){world.core.hp=0;finishBattle('loss');}}

  function simStep(dt){if(phase!=='battle'||world.result)return;world.time+=dt;
    if(world.time>=world.nextPlayerPulse){for(const laneId of laneIds)spawnPlayerPulse(laneId);world.nextPlayerPulse+=P.playerPulse;}
    for(const laneId of laneIds)while(world.time>=world.nextEnemy[laneId]){spawnEnemyPulse(laneId);world.nextEnemy[laneId]+=P.enemyCadence[laneId];}
    tickTowers(dt);for(const a of world.actors)tickActor(a,dt);tickGuards(dt);tickBastions();tickCommander(dt);tickRival(dt);world.actors=world.actors.filter(a=>!a.dead&&a.x>-76&&a.x<72);updateFronts();checkWarnings();checkResult();
    if(currentRun&&world.time>=currentRun.nextSnapshotAt){currentRun.snapshots.push(snapshotSummary());currentRun.nextSnapshotAt+=10;if(currentRun.snapshots.length>50)currentRun.snapshots.shift();}
    if(world.time-lastRecoveryAt>=P.recoveryInterval)persistRecovery('interval');
  }

  function spendIntervention(kind){if(phase!=='battle'||world.result||world.gold<P.interventionCost||world.time<world.interventionReady)return false;const lane=selectedLane;if(kind==='push'&&!R.committedTypes(deployment,lane).length)return false;world.gold-=P.interventionCost;world.interventionReady=world.time+P.interventionCooldown;currentRun.metrics.goldSpent+=P.interventionCost;if(kind==='push'){spawnReinforcement(lane);currentRun.metrics.interventions.push++;}else{world.lanes[lane].overdriveUntil=world.time+P.overdriveSeconds;currentRun.metrics.interventions.overdrive++;}ev('intervention',{kind,lane,cost:P.interventionCost,goldAfter:world.gold});closeActionDrawer();return true;}
  $('pushButton').onclick=()=>spendIntervention('push');$('overdriveButton').onclick=()=>spendIntervention('overdrive');
  $('rallyButton').onclick=()=>{if(phase!=='battle'||world.commander.incapacitated||world.time<world.rallyReady)return;world.rallyUntil=world.time+P.rallySeconds;world.rallyReady=world.time+P.rallyCooldown;ev('rally',{lane:world.commander.lane});closeActionDrawer();};
  $('waypointButton').onclick=()=>{if(phase!=='battle'||world.commander.incapacitated||world.time<world.waypointReady)return;waypointTargeting=!waypointTargeting;$('waypointButton').classList.toggle('active',waypointTargeting);ev('waypoint-targeting',{active:waypointTargeting});};
  function useWaypoint(laneId){if(!waypointTargeting||world.time<world.waypointReady||world.commander.incapacitated)return false;const c=world.commander;c.x=-47;c.y=laneMeta[laneId].y;c.lane=laneId;c.path=[];world.waypointReady=world.time+P.waypointCooldown;waypointTargeting=false;currentRun.metrics.waypoints++;ev('waypoint',{lane:laneId,cooldownUntil:+world.waypointReady.toFixed(2)});$('waypointButton').classList.remove('active');attention('WAYPOINT COMMITTED',`${laneId.toUpperCase()} reached instantly. Emergency rotation is now on cooldown.`,laneId,'warning');return true;}

  let attentionTimer=0,attentionLane=null;
  function attention(title,detail,lane,severity='warning'){attentionLane=lane;$('dangerToastTitle').textContent=title;$('dangerToastDetail').textContent=detail;$('dangerToast').hidden=false;$('dangerToast').dataset.severity=severity;$('dangerPointerLabel').textContent=lane?`${lane.toUpperCase()} ${severity==='critical'?'CRITICAL':'THREAT'}`:'THREAT';$('dangerPointer').hidden=false;clearTimeout(attentionTimer);attentionTimer=setTimeout(()=>{$('dangerToast').hidden=true;},4200);}
  $('dangerPointer').onclick=()=>{if(!attentionLane)return;focusLane(attentionLane,'attention');currentRun.metrics.attentionFocus++;ev('attention-focus',{lane:attentionLane});};
  function showRivalIntent(lane,reason){$('rivalIntent').hidden=false;$('rivalIntent').querySelector('b').textContent=`RIVAL → ${lane.toUpperCase()}`;$('rivalIntentReason').textContent=reason;}

  function resize(){const dpr=Math.min(devicePixelRatio||1,2),w=Math.max(1,innerWidth),h=Math.max(1,innerHeight);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);canvas.style.width=w+'px';canvas.style.height=h+'px';gl.viewport(0,0,canvas.width,canvas.height);rotate.hidden=!(innerHeight>innerWidth);}
  addEventListener('resize',resize);addEventListener('orientationchange',()=>setTimeout(resize,100));resize();
  function viewSize(){const aspect=canvas.width/canvas.height,halfH=28/camera.zoom;return{halfH,halfW:halfH*aspect}}
  function clampCamera(){const v=viewSize();camera.x=Math.max(-72+v.halfW*.35,Math.min(62-v.halfW*.35,camera.x));camera.y=Math.max(-18,Math.min(18,camera.y));camera.zoom=Math.max(.68,Math.min(1.55,camera.zoom));}
  function screenToWorld(clientX,clientY){const r=canvas.getBoundingClientRect(),v=viewSize();return{x:camera.x+((clientX-r.left)/r.width*2-1)*v.halfW,y:camera.y-(clientY-r.top)/r.height*2*v.halfH+v.halfH};}
  function focusLane(laneId,source='strip'){camera.y=laneMeta[laneId].y;camera.x=Math.max(-25,Math.min(20,world.lanes[laneId].frontX));clampCamera();selectedLane=laneId;document.querySelectorAll('.lane[data-lane]').forEach(x=>x.classList.toggle('selected',x.dataset.lane===laneId));if(currentRun)ev('camera-focus',{lane:laneId,source});}
  canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture?.(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,sx:e.clientX,sy:e.clientY});if(pointers.size===1)gesture={type:'tap',id:e.pointerId,startX:e.clientX,startY:e.clientY,lastX:e.clientX,lastY:e.clientY};else if(pointers.size===2){const pts=[...pointers.values()],d=Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y);gesture={type:'pinch',startD:d,startZoom:camera.zoom};}});
  canvas.addEventListener('pointermove',e=>{const p=pointers.get(e.pointerId);if(!p)return;p.x=e.clientX;p.y=e.clientY;if(pointers.size===1&&gesture&&gesture.id===e.pointerId){const dx=e.clientX-gesture.startX,dy=e.clientY-gesture.startY;if(gesture.type==='tap'&&Math.hypot(dx,dy)>DRAG)gesture.type='pan';if(gesture.type==='pan'){const v=viewSize(),r=canvas.getBoundingClientRect();camera.x-=(e.clientX-gesture.lastX)/r.width*2*v.halfW;camera.y+=(e.clientY-gesture.lastY)/r.height*2*v.halfH;clampCamera();gesture.lastX=e.clientX;gesture.lastY=e.clientY;}}else if(pointers.size===2&&gesture?.type==='pinch'){const pts=[...pointers.values()],d=Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y);camera.zoom=gesture.startZoom*(d/gesture.startD);clampCamera();}});
  function pointerFinish(e,cancel=false){const p=pointers.get(e.pointerId);if(p&&gesture?.type==='tap'&&gesture.id===e.pointerId&&!cancel&&phase==='battle'){const w=screenToWorld(e.clientX,e.clientY),lane=laneIds.reduce((best,l)=>Math.abs(laneMeta[l].y-w.y)<Math.abs(laneMeta[best].y-w.y)?l:best,laneIds[0]);orderCommander(Math.max(-62,Math.min(38,w.x)),lane,'ground');}pointers.delete(e.pointerId);if(pointers.size===0)gesture=null;}
  canvas.addEventListener('pointerup',e=>pointerFinish(e,false));canvas.addEventListener('pointercancel',e=>pointerFinish(e,true));
  $('recenterButton').onclick=()=>{camera.x=world.commander.x;camera.y=world.commander.y;clampCamera();if(currentRun)ev('recenter',{lane:world.commander.lane});};
  document.querySelectorAll('.lane[data-lane]').forEach(b=>b.onclick=()=>{const lane=b.dataset.lane;if(waypointTargeting){useWaypoint(lane);focusLane(lane,'waypoint-target');return;}focusLane(lane,'lane-strip');if(currentRun)currentRun.metrics.laneStripJumps[lane]++;});

  function closeActionDrawer(){$('actionDrawer').hidden=true;$('actionsToggle').setAttribute('aria-expanded','false')}
  $('actionsToggle').onclick=()=>{const open=$('actionDrawer').hidden;$('actionDrawer').hidden=!open;$('actionsToggle').setAttribute('aria-expanded',String(open));};
  function closeLab(){$('labPanel').hidden=true;$('labToggle').setAttribute('aria-expanded','false')}
  $('labToggle').onclick=()=>{const open=$('labPanel').hidden;$('labPanel').hidden=!open;$('labToggle').setAttribute('aria-expanded',String(open));};
  $('simSpeed').onchange=e=>{simSpeed=+e.target.value;ev('sim-speed',{value:simSpeed});};
  $('audioButton').onclick=()=>{$('audioButton').textContent='Sound ✓';};
  function pct(x,max){return Math.max(0,Math.round(x/max*100))}
  function guardPct(lane){const remaining=lane.guards.filter(g=>!g.broken);if(!remaining.length)return 0;return Math.round(remaining.reduce((s,g)=>s+g.hp,0)/remaining.reduce((s,g)=>s+g.max,0)*100)}
  function updateLaneUI(id){const lane=world.lanes[id],front=Math.max(2,Math.min(98,(lane.frontX+68)/128*100));$(id+'Front').style.width=front+'%';$(id+'Commander').textContent=!world.commander.incapacitated&&world.commander.lane===id?'◆':'';$(id+'Commander').style.left=Math.max(2,Math.min(98,(world.commander.x+68)/128*100))+'%';$(id+'Rival').textContent=!world.rival.incapacitated&&world.rival.lane===id?'✦':'';$(id+'Rival').style.left=Math.max(2,Math.min(98,(world.rival.x+68)/128*100))+'%';const bp=pct(lane.bastion.hp,lane.bastion.max),gp=guardPct(lane);const b=$(id+'Bastion');b.textContent=lane.bastion.broken?'B✕':'B'+bp;b.className=lane.bastion.broken?'broken':bp<=35?'critical':'good';const g=$(id+'Guard');g.textContent=laneGuardBroken(lane)?'G✕':'G'+gp;g.className='guard '+(laneGuardBroken(lane)?'broken':gp<=35?'critical':'');const p=$(id+'Pressure');p.textContent=lane.pressure==='above'?'DMG > REGEN':lane.pressure==='near'?'AT THRESH':lane.pressure==='broken'?'OPEN BREACH':'REGEN > DMG';}
  function updateUI(){
    $('timer').textContent=phase==='battle'?formatTime(world.time):phase==='ended'?'ENDED':'DEPLOY';$('gold').textContent=Math.floor(world.gold)+'g';$('gateMeter').value=world.gate.hp/world.gate.max;$('coreMeter').value=world.core.hp/world.core.max;$('gateState').textContent=world.gate.vulnerable?'VULNERABLE':'SHIELDED';$('coreState').textContent=world.core.hp/world.core.max<=.35?'CRITICAL':laneIds.some(l=>world.lanes[l].bastion.broken)?'EXPOSED':'SECURE';
    if(phase==='battle')$('objectiveText').textContent=world.gate.vulnerable?'One breach is open — finish or rotate':'Read Rival intent, Guard thresholds, and Bastion clocks';
    for(const id of laneIds)updateLaneUI(id);
    const wp=Math.max(0,world.waypointReady-world.time),rr=Math.max(0,world.rallyReady-world.time),ir=Math.max(0,world.interventionReady-world.time);$('waypointStatus').textContent=wp>0?wp.toFixed(0)+'s':'ready';$('rallyStatus').textContent=rr>0?rr.toFixed(0)+'s':'ready';$('pushStatus').textContent=world.gold<P.interventionCost?`${P.interventionCost}g · need gold`:ir>0?`${P.interventionCost}g · ${ir.toFixed(0)}s`:`${P.interventionCost}g · ready`;$('overdriveStatus').textContent=$('pushStatus').textContent;$('actionsSummary').textContent=`WP ${wp>0?wp.toFixed(0)+'s':'READY'} · ${Math.floor(world.gold)}g`;$('waypointButton').disabled=world.commander.incapacitated||wp>0;$('rallyButton').disabled=world.commander.incapacitated||rr>0;$('pushButton').disabled=world.gold<P.interventionCost||ir>0||!R.committedTypes(deployment,selectedLane).length;$('overdriveButton').disabled=world.gold<P.interventionCost||ir>0;
    $('rivalIntent').hidden=phase!=='battle';if(phase==='battle'){const b=$('rivalIntent').querySelector('b');b.textContent=world.rival.incapacitated?'RIVAL DOWN':`RIVAL → ${world.rival.targetLane.toUpperCase()}`;$('rivalIntentReason').textContent=world.rival.incapacitated?`${Math.max(0,world.rival.reformAt-world.time).toFixed(0)}s to reform`:world.rival.intentReason;}
  }
  function formatTime(t){const m=Math.floor(t/60),s=Math.floor(t%60);return`${m}:${String(s).padStart(2,'0')}`}
  function snapshotSummary(){return{t:+world.time.toFixed(2),gold:Math.floor(world.gold),commander:{lane:world.commander.lane,hpPct:pct(world.commander.hp,world.commander.max)},rival:{lane:world.rival.lane,targetLane:world.rival.targetLane,hpPct:pct(world.rival.hp,world.rival.max),incapacitated:world.rival.incapacitated},gatePct:pct(world.gate.hp,world.gate.max),corePct:pct(world.core.hp,world.core.max),lanes:Object.fromEntries(laneIds.map(id=>[id,{bastionPct:pct(world.lanes[id].bastion.hp,world.lanes[id].bastion.max),guardPct:guardPct(world.lanes[id]),guardPositions:world.lanes[id].guards.map(g=>({broken:g.broken,hpPct:pct(g.hp,g.max)})),pressure:world.lanes[id].pressure}]))};}
  function finishBattle(result){if(world.result)return;world.result=result;phase='ended';clearRecovery('battle-ended');currentRun.result={result,time:+world.time.toFixed(2),gatePct:pct(world.gate.hp,world.gate.max),corePct:pct(world.core.hp,world.core.max)};currentRun.endedAt=new Date().toISOString();ev('battle-end',currentRun.result);$('battleHud').hidden=true;$('battleResult').hidden=false;$('resultTitle').textContent=result==='win'?'Gate broken':'Core lost';$('resultBody').textContent=result==='win'?'The structural question is not merely whether you won: did three lanes and the Rival create readable, adversarial macro choices?':'Export the run anyway. A loss can be useful structural evidence if its causes were readable.';$('resultStats').innerHTML=`<b>${formatTime(world.time)}<br>battle</b><b>${pct(world.core.hp,world.core.max)}%<br>Core</b><b>${currentRun.metrics.rivalDecisions}<br>Rival decisions</b>`;updateUI();}
  document.querySelectorAll('[data-debrief-key]').forEach(b=>b.onclick=()=>{if(!currentRun)return;const key=b.dataset.debriefKey,value=b.dataset.debriefValue;currentRun.debrief[key]=value;document.querySelectorAll(`[data-debrief-key="${key}"]`).forEach(x=>x.classList.toggle('selected-choice',x===b));ev('debrief',{key,value});});

  function clone(v){return JSON.parse(JSON.stringify(v))}
  function stableStringify(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return'['+v.map(stableStringify).join(',')+']';return'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stableStringify(v[k])).join(',')+'}'}
  function fnv1a(text){let h=0x811c9dc5;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,0x01000193)>>>0;}return h.toString(16).padStart(8,'0')}
  function digestPayload(){return{phase,selectedLane,waypointTargeting,simSpeed,actorSeq,projectileSeq,deployment,world,currentRun:currentRun?{deployment:currentRun.deployment,parameterRevision:currentRun.parameterRevision,events:currentRun.events,snapshots:currentRun.snapshots,debrief:currentRun.debrief,metrics:currentRun.metrics,result:currentRun.result,nextSnapshotAt:currentRun.nextSnapshotAt}:null}}
  function stateDigest(){return fnv1a(stableStringify(digestPayload()))}
  function snapshotBattle(reason='manual'){return{snapshotSchema:SNAPSHOT_SCHEMA,build:BUILD,designBaseline:DESIGN_BASELINE,fixture:FIXTURE,parameterRevision:PARAM_REV,fixedDt:P.fixedDt,reason,savedAt:new Date().toISOString(),stateHash:stateDigest(),state:{phase,selectedLane,waypointTargeting,simSpeed,actorSeq,projectileSeq,fixedAccumulator,deployment:clone(deployment),world:clone(world),currentRun:currentRun?clone(currentRun):null,camera:clone(camera)}}}
  function compatible(s){return!!s&&s.snapshotSchema===SNAPSHOT_SCHEMA&&s.build===BUILD&&s.fixture===FIXTURE&&s.parameterRevision===PARAM_REV&&s.fixedDt===P.fixedDt&&s.state}
  function recoveryStatus(text,kind='neutral'){$('recoveryStatus').textContent=text;$('recoveryStatus').dataset.kind=kind}
  function persistRecovery(reason='interval'){if(phase!=='battle'||world.result||telemetryMuted)return null;const s=snapshotBattle(reason);try{localStorage.setItem(RECOVERY_KEY,JSON.stringify(s));lastRecoveryAt=world.time;recoveryEvents.push({type:'saved',t:+world.time.toFixed(2),reason,hash:s.stateHash});recoveryStatus(`Saved ${world.time.toFixed(1)}s · ${s.stateHash}`,'good');return s}catch(err){recoveryStatus('Recovery save failed','bad');return null}}
  function clearRecovery(reason='clear'){try{localStorage.removeItem(RECOVERY_KEY)}catch(_){}lastRecoveryAt=-Infinity;if(!telemetryMuted)recoveryEvents.push({type:'cleared',t:+world.time.toFixed(2),reason});recoveryStatus('No active recovery snapshot')}
  function latestRecovery(){try{const raw=localStorage.getItem(RECOVERY_KEY);return raw?JSON.parse(raw):null}catch(_){return null}}
  function restoreSnapshot(s,reason='manual'){if(!compatible(s)){recoveryStatus('Incompatible recovery snapshot','bad');return false;}const x=clone(s.state);phase=x.phase;selectedLane=x.selectedLane;waypointTargeting=x.waypointTargeting;simSpeed=x.simSpeed;actorSeq=x.actorSeq;projectileSeq=x.projectileSeq;fixedAccumulator=x.fixedAccumulator||0;deployment=x.deployment;for(const k of Object.keys(world))delete world[k];Object.assign(world,x.world);currentRun=x.currentRun;if(currentRun){const i=evidence.runs.findIndex(r=>r.runId===currentRun.runId);if(i>=0)evidence.runs[i]=currentRun;else evidence.runs.push(currentRun);}Object.assign(camera,x.camera||{});clampCamera();$('deployment').hidden=phase!=='deploy';$('battleHud').hidden=phase!=='battle';$('battleResult').hidden=phase!=='ended';$('simSpeed').value=String(simSpeed);document.querySelectorAll('.lane[data-lane]').forEach(n=>n.classList.toggle('selected',n.dataset.lane===selectedLane));const actual=stateDigest(),ok=actual===s.stateHash;if(!telemetryMuted)recoveryEvents.push({type:'restored',t:+world.time.toFixed(2),reason,expected:s.stateHash,actual,exact:ok});recoveryStatus((ok?'Restored exact · ':'RESTORE MISMATCH · ')+actual,ok?'good':'bad');updateUI();return ok}
  function maybeRestore(){const s=latestRecovery();if(!s)return false;const ok=restoreSnapshot(s,'boot');if(ok)lastRecoveryAt=world.time;return ok}
  function runSteps(n){for(let i=0;i<n&&phase==='battle'&&!world.result;i++)simStep(P.fixedDt);return stateDigest()}
  function selfCheck(){if(phase!=='battle'||world.result){recoveryStatus('Start a battle before self-check','bad');return;}telemetryMuted=true;const cp=snapshotBattle('self-check'),roundBefore=cp.stateHash;const rt=restoreSnapshot(cp,'roundtrip'),roundAfter=stateDigest();const badRejected=!restoreSnapshot({...cp,snapshotSchema:999},'bad-schema');const results=[];for(const steps of[600,1800]){restoreSnapshot(cp,'A');const a=runSteps(steps);restoreSnapshot(cp,'B');const b=runSteps(steps);results.push({steps,a,b,exact:a===b});}restoreSnapshot(cp,'final');telemetryMuted=false;const pass=rt&&roundBefore===roundAfter&&badRejected&&results.every(r=>r.exact);const report={type:'determinism-self-check',t:+world.time.toFixed(2),roundTrip:{before:roundBefore,after:roundAfter,exact:roundBefore===roundAfter},incompatibleRejected:badRejected,continuations:results,pass};recoveryEvents.push(report);ev('determinism-self-check',report);persistRecovery('post-self-check');recoveryStatus(pass?'SELF-CHECK PASS · exact continuation':'SELF-CHECK FAIL · inspect export',pass?'good':'bad')}
  $('saveRecovery').onclick=()=>persistRecovery('manual');$('reloadRecovery').onclick=()=>{const s=latestRecovery();s?restoreSnapshot(s,'manual'):recoveryStatus('No recovery snapshot','bad')};$('clearRecovery').onclick=()=>clearRecovery('manual');$('determinismCheck').onclick=selfCheck;
  function exportEvidence(){const doc={...evidence,recovery:{patch:'DET-001-integrated',snapshotSchema:SNAPSHOT_SCHEMA,fixedDt:P.fixedDt,events:clone(recoveryEvents),hasRecovery:!!latestRecovery(),currentStateHash:stateDigest()},exportedAt:new Date().toISOString()};const blob=new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`lane-warden-${BUILD}-${PARAM_REV}-gameplay-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  $('exportEvidence').onclick=exportEvidence;$('resultExport').onclick=exportEvidence;
  addEventListener('visibilitychange',()=>{if(currentRun)ev('visibility',{state:document.visibilityState});if(document.hidden)persistRecovery('background');else lastFrame=performance.now();});addEventListener('pagehide',()=>persistRecovery('pagehide'));

  function render(){gl.clearColor(.045,.065,.07,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.useProgram(program);gl.bindVertexArray(vao);const v=viewSize();gl.uniform2f(U.camera,camera.x,camera.y);gl.uniform2f(U.halfView,v.halfW,v.halfH);gl.uniform1f(U.tilt,camera.tilt);
    box(-5,0,-.9,145,52,.7,C.ground);for(const laneId of laneIds){const y=laneMeta[laneId].y;box(-4,y,-.45,132,5.6,.25,C.lane);box(-4,y+5,-.5,132,2.5,.18,C.shoulder);box(-4,y-5,-.5,132,2.5,.18,C.shoulder);}for(const j of P.junctionXs)box(j,0,-.25,5,38,.18,C.junction);
    for(const laneId of laneIds){const lane=world.lanes[laneId],y=lane.y;box(-58,y,2,4.8,5.2,4.2,lane.bastion.broken?C.danger:C.bastion);if(!lane.bastion.broken)bar(-58,y,5,5,1,lane.bastion.hp/lane.bastion.max,[.16,.16,.16],C.bastion);for(const g of lane.guards){box(g.x,y,2.1,3.5,5,4.5,g.broken?[.18,.15,.14]:C.guard);if(!g.broken)bar(g.x,y,5.2,4.2,.8,g.hp/g.max,[.15,.12,.12],C.guard);}for(const t of lane.towers){if(t.dead)continue;box(t.x,t.y,1.5,2.8,2.8,3.4,t.type==='pylon'?C.pylon:C.tower);}}
    box(58,0,3,6,42,6,C.gate);bar(58,0,7,7,1.2,world.gate.hp/world.gate.max,[.14,.12,.1],world.gate.vulnerable?C.danger:C.gate);box(-68,0,3,6,42,6,C.core);bar(-68,0,7,7,1.2,world.core.hp/world.core.max,[.12,.14,.16],C.core);
    for(const a of world.actors){const color=a.team===1?(a.role==='siege'?C.friend2:C.friend):(a.role==='siege'?C.enemy2:C.enemy);const scale=a.role==='siege'?1.6:1;box(a.x,a.y,1.1,1.5*scale,1.4*scale,2.2*scale,color);}
    const c=world.commander;if(!c.incapacitated){box(c.x,c.y,1.7,2.5,2.5,3.8,C.commander);bar(c.x,c.y,4.2,3.4,.55,c.hp/c.max,[.15,.13,.08],C.commander);for(let i=0;i<16;i++){const a=i/16*Math.PI*2;box(c.x+Math.cos(a)*P.presenceRadius,c.y+Math.sin(a)*P.presenceRadius,.08,.35,.35,.12,C.presence);}}
    const r=world.rival;if(!r.incapacitated){box(r.x,r.y,1.7,2.5,2.5,3.8,C.rival);bar(r.x,r.y,4.2,3.4,.55,r.hp/r.max,[.15,.09,.09],C.rival);}if(c.path?.length)for(const p of c.path)box(p.x,p.y,.2,1,1,.15,C.route);
  }
  let fpsFrames=0,fpsLast=performance.now();function animate(now){requestAnimationFrame(animate);const raw=Math.min(.1,(now-lastFrame)/1000);lastFrame=now;if(!document.hidden&&phase==='battle'){fixedAccumulator+=raw*simSpeed;let guard=0;while(fixedAccumulator+1e-12>=P.fixedDt&&guard<20){simStep(P.fixedDt);fixedAccumulator-=P.fixedDt;guard++;}}render();updateUI();fpsFrames++;if(now-fpsLast>=1000){$('fps').textContent=Math.round(fpsFrames*1000/(now-fpsLast))+' fps';$('actors').textContent=world.actors.length+' actors';fpsFrames=0;fpsLast=now;}}

  if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
  renderDeployment();maybeRestore();updateUI();requestAnimationFrame(animate);
})();
