(() => {
'use strict';
const E=window.LW_ENGINE,D=window.LW_DATA,SAVE='lane-warden-production-run-v1';const $=id=>document.getElementById(id);let run=null,battle=null,raf=0,last=0,deploy=E.defaultDeployment(),resolutionKind=null,orientationTimer=0;
function save(){if(!run)return;run.updatedAt=new Date().toISOString();localStorage.setItem(SAVE,JSON.stringify(run))}
function load(){try{return JSON.parse(localStorage.getItem(SAVE)||'null')}catch{return null}}
function show(id){['home','map','deployment','battle','resolution','lastStand'].forEach(x=>$(x).hidden=x!==id);if(id!=='battle')cancelAnimationFrame(raf);orientation(true)}
function setupHome(){const old=load();$('continueRun').hidden=!old;$('regression').textContent=`internal invariants: ${E.selfTest().pass?'PASS':'FAIL'} · production runtime owns its rules`;}
function beginNew(){run=E.newRun(`warden-${new Date().toISOString().slice(0,10)}-${Math.floor(Math.random()*9999)}`);save();renderMap()}
function continueRun(){run=load()||E.newRun();renderMap()}
function renderMap(){show('map');$('seedBadge').textContent=`SEED ${run.seed}`;$('emberBadge').textContent=`${'◆'.repeat(run.embers)}${'◇'.repeat(3-run.embers)} EMBERS`;$('salvageBadge').textContent=`${run.salvage} SALVAGE`;const g=$('mapGraph');g.innerHTML='';for(const n of D.nodes){const b=document.createElement('button');const done=run.resolvedNodes.some(r=>r.id===n.id);const ready=run.currentNode===n.id&&!n.placeholder;b.className=`node ${done?'done':ready?'ready':'locked'}`;b.style.left=n.x+'%';b.style.top=n.y+'%';b.innerHTML=`<strong>${done?'✓ ':''}${n.name}</strong><small>${n.subtitle}</small>`;b.disabled=!ready;b.onclick=()=>showDeployment();g.appendChild(b)}$('mapFooter').textContent=run.currentNode==='A1-B1'?'Outer Approach is ready. Later nodes are visible but intentionally not implemented in P0.':'Outer Approach resolved. The production loop has persisted your result; P2 will open the next node families.';save()}
function showDeployment(){deploy=E.defaultDeployment();show('deployment');renderDeployment()}
function renderDeployment(){const nc=Object.values(deploy.north.units).reduce((a,b)=>a+b,0),sc=Object.values(deploy.south.units).reduce((a,b)=>a+b,0);$('northCount').textContent=`${nc} squads`;$('southCount').textContent=`${sc} squads`;$('deployRoster').innerHTML=D.units.map(u=>`<span class="chip">${u.name}: N${deploy.north.units[u.id]||0} / S${deploy.south.units[u.id]||0}</span>`).join('')}
function shiftOne(to){const from=to==='north'?'south':'north';const order=['ironjack','slingline','bulwark','zealot','ram'];const id=order.find(x=>(deploy[from].units[x]||0)>0);if(!id)return;deploy[from].units[id]--;deploy[to].units[id]=(deploy[to].units[id]||0)+1;renderDeployment()}
function startBattle(){battle=E.createBattle(run,deploy);run.battle={nodeId:battle.nodeId,startedAt:new Date().toISOString(),deployment:deploy};save();buildAbilityUI();show('battle');last=performance.now();raf=requestAnimationFrame(frame);orientation()}
function buildAbilityUI(){const rail=$('abilityRail'),list=$('readAbilityList');rail.innerHTML='';list.innerHTML='';for(const a of D.commander.abilities){const b=document.createElement('button');b.dataset.id=a.id;b.innerHTML=`<b>${a.id==='rally'?'✦':a.id==='sunder'?'⚒':a.id==='waypoint'?'↯':'+'}</b>${a.name.toUpperCase()}`;b.onclick=()=>useAbility(a.id);rail.appendChild(b);const d=document.createElement('button');d.innerHTML=`<b>${a.name}</b><br>${a.description}`;d.onclick=()=>useAbility(a.id);list.appendChild(d)}}
function useAbility(id){if(id==='waypoint'){const lane=battle.commanderLane==='north'?'south':'north';E.useAbility(battle,id,lane)}else E.useAbility(battle,id,battle.commanderLane);closeRead();renderHUD()}
function frame(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;E.stepBattle(battle,dt);draw();renderHUD();if(battle.lastStand?.active){cancelAnimationFrame(raf);show('lastStand');return}if(battle.result?.kind==='victory'){cancelAnimationFrame(raf);E.resolveVictory(run,battle);finishResolution('victory');return}raf=requestAnimationFrame(frame)}
function draw(){const c=$('battlefield'),dpr=Math.min(devicePixelRatio||1,2),r=c.getBoundingClientRect(),w=Math.max(1,Math.floor(r.width*dpr)),h=Math.max(1,Math.floor(r.height*dpr));if(c.width!==w||c.height!==h){c.width=w;c.height=h}const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,r.width,r.height);x.fillStyle='#0b141a';x.fillRect(0,0,r.width,r.height);const lanes=[['north',r.height*.34],['south',r.height*.64]];for(const [id,y] of lanes){const l=battle.lanes[id];x.strokeStyle='#32454b';x.lineWidth=18;x.beginPath();x.moveTo(75,y);x.lineTo(r.width-75,y);x.stroke();x.strokeStyle='#607875';x.lineWidth=2;x.beginPath();x.moveTo(75,y);x.lineTo(r.width-75,y);x.stroke();const fx=75+(r.width-150)*l.front;x.fillStyle='#6fc3b5';x.fillRect(fx-6,y-14,12,28);for(let i=0;i<12;i++){const px=fx-25-(i%6)*13,py=y-11+(i>5?18:0);x.fillStyle=i%3===0?'#87c9ba':'#4f907f';x.beginPath();x.arc(px,py,4,0,Math.PI*2);x.fill()}for(let i=0;i<10;i++){const px=fx+24+(i%5)*13,py=y-10+(i>4?18:0);x.fillStyle='#b45859';x.beginPath();x.arc(px,py,4,0,Math.PI*2);x.fill()}x.fillStyle=l.bastion>0?'#4c7772':'#382c2c';x.fillRect(42,y-25,22,50);x.fillStyle=l.guard>0?'#895150':'#3b2a2a';x.fillRect(r.width-65,y-23,20,46);if(battle.commanderLane===id){x.fillStyle='#e3b451';x.font='bold 24px system-ui';x.fillText('◆',fx-12,y-25)}}x.fillStyle=battle.gateVulnerable?'#d8a84b':'#6d5838';x.fillRect(r.width-28,r.height*.27,14,r.height*.46);x.fillStyle='#42606a';x.fillRect(14,r.height*.27,14,r.height*.46);x.fillStyle='#d6e0df';x.font='bold 10px system-ui';x.fillText(`CORE ${Math.round(battle.core)}%`,34,26);x.fillText(`GATE ${Math.round(battle.gate)}% ${battle.gateVulnerable?'· VULNERABLE':'· SHIELDED'}`,r.width-185,26)}
function renderHUD(){$('battleGold').textContent=`${Math.floor(battle.gold)}g`;$('readReserve').textContent=`READ ${battle.readReserve.toFixed(1)}s`;for(const id of ['north','south']){const l=battle.lanes[id];$(id+'Front').style.width=`${Math.round(l.front*100)}%`;$(id+'Cmd').textContent=battle.commanderLane===id?'◆':'';const bs=$(id+'Bastion');bs.textContent=l.status;bs.className=l.status==='CRITICAL'?'critical':'';const gs=$(id+'Guard');gs.textContent=l.bastion>0?'SHIELDED':l.guard<=0?'BREACHED':l.guard<99?guardLabel(l):'STALLING';gs.className=l.guard<=0||guardLabel(l)==='NET PROGRESS'?'progress':''}document.querySelectorAll('#abilityRail button').forEach(b=>{const cd=battle.abilities[b.dataset.id]||0;b.disabled=cd>0;b.title=cd>0?`${cd.toFixed(1)}s`:''})}
function guardLabel(l){const d=l.guard-l.guardPrev;return d>0.08?'REGENERATING':d<-0.08?'NET PROGRESS':'STALLING'}
function openRead(){battle.readMenuOpen=true;E.setReadMenu(battle,true);$('readPanel').hidden=false;$('readToggle').textContent='CLOSE'}
function closeRead(){if(!battle)return;battle.readMenuOpen=false;E.setReadMenu(battle,false);$('readPanel').hidden=true;$('readToggle').textContent='ACTIONS'}
function finishResolution(kind){resolutionKind=kind;run.battle=null;save();show('resolution');if(kind==='victory'){$('resolutionEyebrow').textContent='NODE RESOLVED · VICTORY';$('resolutionTitle').textContent='THE GATE IS OPEN';$('resolutionBody').textContent='Outer Approach is broken. The Warden keeps the normal reward and the run returns to the road.';$('resolutionStats').textContent=`+180 salvage · ${run.embers} Embers remain`}else if(kind==='last-stand'){$('resolutionEyebrow').textContent='NODE RESOLVED · LAST STAND';$('resolutionTitle').textContent='A COSTLY ADVANCE';$('resolutionBody').textContent='The Core fell, but Bulwark Detonation destroyed the Gate. One Ember was spent; the normal reward was lost.';$('resolutionStats').textContent=`+120 salvage · ${run.embers} Embers remain`}else{$('resolutionEyebrow').textContent='RUN COMPLETE';$('resolutionTitle').textContent='THE ROAD REMEMBERS';$('resolutionBody').textContent='Bulwark Detonation opened the Gate, but no Ember remained to carry the company onward.';$('resolutionStats').textContent=`${run.salvage} salvage banked · 0 Embers`}}
function landscapeSignal(){const vv=window.visualViewport;const signals=[innerWidth>=innerHeight,vv?vv.width>=vv.height:null,typeof matchMedia==='function'?matchMedia('(orientation: landscape)').matches:null,screen.orientation&&typeof screen.orientation.angle==='number'?Math.abs(screen.orientation.angle)%180===90:null].filter(v=>v!==null);return signals.some(Boolean)}
function orientation(immediate=false){clearTimeout(orientationTimer);const apply=()=>{$('rotate').hidden=$('battle').hidden||landscapeSignal()};if(immediate)apply();else orientationTimer=setTimeout(apply,180)}
$('newRun').onclick=beginNew;$('continueRun').onclick=continueRun;$('clearSave').onclick=()=>{localStorage.removeItem(SAVE);setupHome()};$('backToMap').onclick=renderMap;document.querySelectorAll('.deploy-lane').forEach(x=>x.onclick=()=>shiftOne(x.dataset.lane));$('startBattle').onclick=startBattle;$('readToggle').onclick=()=>battle.readMenuOpen?closeRead():openRead();$('structureButton').onclick=()=>{$('structurePanel').hidden=false;if(!battle.readMenuOpen)openRead()};$('structureClose').onclick=()=>{$('structurePanel').hidden=true;closeRead()};$('recenter').onclick=()=>{};document.querySelectorAll('#laneStrip [data-lane]').forEach(b=>b.onclick=()=>E.setCommanderLane(battle,b.dataset.lane));$('resolveLastStand').onclick=()=>{const result=E.resolveLastStand(run,battle);finishResolution(result.kind==='last-stand-advance'?'last-stand':'terminal')};$('returnMap').onclick=()=>resolutionKind==='terminal'?show('home'):renderMap();addEventListener('resize',()=>orientation());addEventListener('orientationchange',()=>orientation());window.visualViewport?.addEventListener('resize',()=>orientation());setupHome();orientation(true);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
