(() => {
'use strict';
const BUILD='T7-0.6.1',DECLARATION='LW-T7-002';
const CATEGORIES=[
 {id:'commander',name:'COMMANDER IDENTITY',question:'Which marker is your Commander?',answers:['A','B','C'],correct:'B',order:['A','B']},
 {id:'guard',name:'GUARD THRESHOLD',question:'Which Guard line is making net progress?',answers:['NORTH','MID','SOUTH'],correct:'MID',order:['B','A']},
 {id:'presence',name:'PRESENCE',question:'Which allied unit is inside Presence?',answers:['A','B','C'],correct:'B',order:['A','B']},
 {id:'mobHealth',name:'ORDINARY HEALTH',question:'Which ordinary unit is badly wounded?',answers:['A','B','C'],correct:'B',order:['B','A']},
 {id:'bastion',name:'BASTION URGENCY',question:'Which Bastion is in the critical clock state?',answers:['NORTH','MID','SOUTH'],correct:'NORTH',order:['A','B']},
 {id:'gate',name:'GATE VULNERABILITY',question:'What is the Gate state right now?',answers:['SHIELDED','VULNERABLE'],correct:'VULNERABLE',order:['B','A']}
];
const THRESHOLDS=Object.freeze({recognitionExposures:12,overallMinCorrect:11,minTapTarget:44});
const state={categoryIndex:0,exposureIndex:0,responses:[],decisions:{},startedAt:null,completedAt:null,shownAt:0,device:null,layoutSamples:[]};
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const r1=n=>+n.toFixed(1),rect=el=>{if(!el)return null;const r=el.getBoundingClientRect();return{x:r1(r.x),y:r1(r.y),width:r1(r.width),height:r1(r.height),right:r1(r.right),bottom:r1(r.bottom)}};
function device(){return{userAgent:navigator.userAgent,standalone:!!navigator.standalone||matchMedia('(display-mode: standalone)').matches,language:navigator.language,viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio||1,orientation:innerWidth>=innerHeight?'landscape':'portrait'}}}
function unit(x,label,{enemy=false,commander=false,denseCommander=false,health=null,wounded=false}={}){const cls=['unit',enemy?'enemy':'',commander?'commander':''].filter(Boolean).join(' '),glyph=denseCommander?'C':(commander?'◆':'');let h=`<span class="${cls}" style="left:${x}%;top:50%"><span class="glyph">${glyph}</span></span>`;if(label)h+=`<span class="candidate-label" style="left:${x}%;top:23%">${label}</span>`;if(health!==null)h+=`<span class="health ${wounded?'low':''}" style="left:${x}%;top:calc(50% + 11px)"><i style="width:${health}%"></i></span><span class="health-num" style="left:${x}%;top:calc(50% + 17px)">${health}%</span>`;return h}
function contextualHealth(x,label,hp){return `${unit(x,label)}<span class="health low" style="left:${x}%;top:calc(50% + 11px)"><i style="width:${hp}%"></i></span><span class="wounded-tag" style="left:${x}%;top:calc(50% + 18px)">WOUNDED</span>`}
function noise(){return `<span class="dense-noise" style="left:40%;top:8%">SPD 1.08</span><span class="dense-noise" style="left:58%;bottom:7%">DMG 12</span><span class="dense-noise" style="left:74%;top:10%">RNG 8</span>`}
function lane(id,content=''){return `<div class="lane-row" data-lane="${id}"><span class="lane-label">${id.toUpperCase()}</span><span class="route"></span><span class="gate-post"></span>${content}</div>`}
function commanderScene(t){const d=t==='A',row=[unit(32,'A',{health:d?74:null}),unit(52,'B',{commander:!d,denseCommander:d,health:d?88:null}),unit(71,'C',{health:d?63:null}),d?noise():''].join('');return lane('north',d?noise():'')+lane('mid',row)+lane('south',d?noise():'')}
function presenceScene(t){const d=t==='A';let row=`<span class="presence-ring ${d?'dense':''}" style="left:49%;top:50%;width:36%;height:82%"></span>`;row+=unit(23,'A',{health:d?82:null})+unit(55,'B',{health:d?71:null})+unit(77,'C',{health:d?94:null})+unit(49,null,{commander:!d,denseCommander:d,health:d?91:null});if(!d)row+=`<span class="buff-dot" style="left:55%;top:50%"></span>`;if(d)row+=noise();return lane('north',d?noise():'')+lane('mid',row)+lane('south',d?noise():'')}
function mobScene(t){const d=t==='A';let row='';if(d)row+=unit(34,'A',{health:78})+unit(53,'B',{health:18,wounded:true})+unit(72,'C',{health:64})+noise();else row+=unit(34,'A')+contextualHealth(53,'B',18)+unit(72,'C');return lane('north',d?noise():'')+lane('mid',row)+lane('south',d?noise():'')}
function bastionContent(id,t){const v={north:{hp:22,state:'CRITICAL',cls:'critical',pips:1},mid:{hp:58,state:'WATCH',cls:'watch',pips:2},south:{hp:81,state:'STABLE',cls:'good',pips:3}}[id];if(t==='A')return `<span class="structure ${id==='north'?'critical':''}" style="left:18%;top:52%"><b>BASTION</b><span class="sbar"><i style="width:${v.hp}%"></i></span><span class="exact">HP ${v.hp}% · −${id==='north'?9:id==='mid'?4:2}/s</span></span>${noise()}`;return `<span class="structure" style="left:18%;top:52%;color:${id==='north'?'var(--critical)':id==='mid'?'var(--watch)':'var(--good)'}"><span class="state-tag ${v.cls}">${id==='north'?'! ':''}${v.state}</span><span class="clock-pips">${[1,2,3].map(n=>`<i class="${n<=v.pips?'on':''}"></i>`).join('')}</span></span>`}
function bastionScene(t){return ['north','mid','south'].map(id=>lane(id,bastionContent(id,t))).join('')}
function guardContent(id,t){const v={north:{hp:64,to:67,state:'REGENERATING',cls:'regen'},mid:{hp:61,to:55,state:'NET PROGRESS',cls:'progressing'},south:{hp:49,to:49,state:'STALLING',cls:'stall'}}[id];if(t==='A')return `<span class="structure" style="left:70%;top:52%"><b>GUARD</b><span class="sbar"><i style="width:${v.hp}%"></i></span><span class="exact">${v.hp}% → ${v.to}% · R+${id==='north'?6:id==='mid'?2:4}</span></span>${noise()}`;return `<span class="structure" style="left:70%;top:52%"><span class="state-tag ${v.cls}">${id==='north'?'↗ ':id==='mid'?'↘ ':'↔ '}${v.state}</span></span>`}
function guardScene(t){return ['north','mid','south'].map(id=>lane(id,guardContent(id,t))).join('')}
function gateScene(t){const d=t==='A',mid=d?`<span class="gate-state" style="right:40px"><span class="shield">◇</span><b>GATE HP 82%</b><small>SHIELD 0 · BREACH 1 · GUARD N 0</small></span>${noise()}`:`<span class="gate-state" style="right:40px;color:var(--critical)"><span class="shield">◈</span><b>BREACH OPEN</b><small>GATE VULNERABLE</small></span>`;return lane('north',d?noise():'')+lane('mid',mid)+lane('south',d?noise():'')}
function sceneFor(id,t){return id==='commander'?commanderScene(t):id==='guard'?guardScene(t):id==='presence'?presenceScene(t):id==='mobHealth'?mobScene(t):id==='bastion'?bastionScene(t):gateScene(t)}
function capture(kind){const buttons=[...document.querySelectorAll(kind==='recognition'?'.answer':'.pref')].filter(x=>!x.hidden).map(rect),containers=[rect(kind==='recognition'?$('trial'):$('compare'))].filter(Boolean);const minW=buttons.length?Math.min(...buttons.map(r=>r.width)):0,minH=buttons.length?Math.min(...buttons.map(r=>r.height)):0,overflow=[...containers,...buttons].some(r=>!r||r.x<-1||r.y<-1||r.right>innerWidth+1||r.bottom>innerHeight+1);state.layoutSamples.push({kind,category:CATEGORIES[state.categoryIndex]?.id||null,viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio||1},minTargetWidth:r1(minW),minTargetHeight:r1(minH),overflow})}
function showRecognition(){const c=CATEGORIES[state.categoryIndex],t=c.order[state.exposureIndex];$('compare').hidden=true;$('trial').hidden=false;$('progress').textContent=`PAIR ${state.categoryIndex+1} / 6 · READ ${state.exposureIndex+1} / 2`;$('categoryLabel').textContent=c.name;$('sceneTreatment').textContent=`TREATMENT ${t}`;$('orderLabel').textContent=`SAME STATE · ${state.exposureIndex+1} OF 2`;$('question').textContent=c.question;$('battlefield').innerHTML=sceneFor(c.id,t);$('answers').innerHTML=c.answers.map(a=>`<button class="answer" data-answer="${esc(a)}" type="button">${esc(a)}</button>`).join('');document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>recordRecognition(b.dataset.answer));state.shownAt=performance.now();requestAnimationFrame(()=>capture('recognition'))}
function recordRecognition(selected){const c=CATEGORIES[state.categoryIndex],t=c.order[state.exposureIndex],seconds=(performance.now()-state.shownAt)/1000;state.responses.push({index:state.responses.length+1,category:c.id,treatment:t,orderWithinPair:state.exposureIndex+1,question:c.question,correctAnswer:c.correct,selectedAnswer:selected,correct:selected===c.correct,responseSeconds:+seconds.toFixed(3)});document.querySelectorAll('.answer').forEach(b=>b.disabled=true);if(state.exposureIndex===0){state.exposureIndex=1;setTimeout(showRecognition,180)}else setTimeout(showCompare,180)}
function responseFor(category,t){return state.responses.find(r=>r.category===category&&r.treatment===t)}
function showCompare(){const c=CATEGORIES[state.categoryIndex];$('trial').hidden=true;$('compare').hidden=false;$('progress').textContent=`PAIR ${state.categoryIndex+1} / 6 · COMPARE`;$('sceneA').innerHTML=sceneFor(c.id,'A');$('sceneB').innerHTML=sceneFor(c.id,'B');$('aTime').textContent='SAME STATE';$('bTime').textContent='SAME STATE';$('compareQuestion').textContent=`${c.name}: what should the game use?`;$('hybridNote').classList.remove('show');$('noteText').value='';document.querySelectorAll('.pref').forEach(b=>{b.disabled=false;b.onclick=()=>choosePreference(b.dataset.pref)});requestAnimationFrame(()=>capture('compare'))}
function choosePreference(pref){const c=CATEGORIES[state.categoryIndex];if(pref==='HYBRID'){$('hybridNote').classList.add('show');document.querySelectorAll('.pref').forEach(b=>b.disabled=true);$('saveHybrid').onclick=()=>finishCategory('HYBRID',$('noteText').value.trim());return}finishCategory(pref,'')}
function finishCategory(pref,note){const c=CATEGORIES[state.categoryIndex];state.decisions[c.id]={preference:pref,note};state.categoryIndex++;state.exposureIndex=0;if(state.categoryIndex>=CATEGORIES.length){state.completedAt=new Date().toISOString();setTimeout(showFinish,160)}else setTimeout(showRecognition,160)}
function median(xs){if(!xs.length)return null;const a=[...xs].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function score(){const all=state.responses,correct=all.filter(r=>r.correct).length,categoryFloor=CATEGORIES.every(c=>all.filter(r=>r.category===c.id&&r.correct).length>=1),layoutPass=state.layoutSamples.length>=18&&state.layoutSamples.every(s=>!s.overflow&&s.minTargetWidth>=THRESHOLDS.minTapTarget&&s.minTargetHeight>=THRESHOLDS.minTapTarget);const byTreatment=Object.fromEntries(['A','B'].map(t=>{const rows=all.filter(r=>r.treatment===t);return[t,{correct:rows.filter(r=>r.correct).length,total:rows.length,medianSeconds:rows.length?+median(rows.map(r=>r.responseSeconds)).toFixed(3):null}]}));const byCategory=Object.fromEntries(CATEGORIES.map(c=>{const a=responseFor(c.id,'A'),b=responseFor(c.id,'B');return[c.id,{A:a?{correct:a.correct,responseSeconds:a.responseSeconds}:null,B:b?{correct:b.correct,responseSeconds:b.responseSeconds}:null,decision:state.decisions[c.id]||null}]}));const checks={coverage:all.length===12,overallRecognition:correct>=THRESHOLDS.overallMinCorrect,categoryFloor,phoneLayout:layoutPass,allCategoryDecisions:CATEGORIES.every(c=>!!state.decisions[c.id])};return{verdict:Object.values(checks).every(Boolean)?'PASS':'FAIL',checks,metrics:{completed:all.length,correct,accuracy:all.length?+(correct/all.length).toFixed(3):0,byTreatment,byCategory},layoutSamples:state.layoutSamples}}
function showFinish(){$('compare').hidden=true;$('finish').hidden=false;$('progress').textContent='COMPLETE';const s=score();$('finishTitle').textContent=`Battlefield information policy · ${s.verdict}`;$('summary').innerHTML=`<div><b>${s.metrics.correct}/12</b><span>recognition</span></div><div><b>A ${s.metrics.byTreatment.A.medianSeconds}s</b><span>median read</span></div><div><b>B ${s.metrics.byTreatment.B.medianSeconds}s</b><span>median read</span></div>`;$('policy').innerHTML=CATEGORIES.map(c=>{const d=state.decisions[c.id];return `<div class="policy-row"><span>${c.name}</span><b>${esc(d.preference)}</b>${d.note?`<small>${esc(d.note)}</small>`:''}</div>`}).join('')}
function exportEvidence(){const s=score(),doc={schema:1,declarationId:DECLARATION,build:BUILD,designBaseline:'1.7',test:'Test 7 — Paired Information Legibility',question:'For each battlefield information category, which treatment should the game use: A, B, or Hybrid?',device:state.device,thresholds:THRESHOLDS,categoryPlan:CATEGORIES.map(c=>({category:c.id,order:c.order})),startedAt:state.startedAt,completedAt:state.completedAt,responses:state.responses,decisions:state.decisions,finalScore:s,exportedAt:new Date().toISOString(),note:'Recognition is measured per treatment against identical category state. Design preference is resolved independently per category; HYBRID is a valid intended result.'},blob=new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`lane-warden-${DECLARATION}-${BUILD}-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('start').onclick=()=>{state.startedAt=new Date().toISOString();state.device=device();$('intro').hidden=true;showRecognition()};$('export').onclick=exportEvidence;if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();