(() => {
'use strict';
const E=window.LW_ENGINE,D=window.LW_DATA,SAVE='lane-warden-production-run-v1',BUILD='P2-0.17.0';
const $=id=>document.getElementById(id);const LANES=['north','south'];
let run=null,battle=null,raf=0,last=0,lastSaveAt=0,deploy=E.defaultDeployment(),resolutionKind=null,selectedLane='north',pendingTarget=null,reclamationShown=false;
const camera={x:0,zoom:1,worldW:2100,pointers:new Map(),pinchStart:null};
function save(){if(!run)return;run.updatedAt=new Date().toISOString();localStorage.setItem(SAVE,JSON.stringify(run))}
function load(){try{return JSON.parse(localStorage.getItem(SAVE)||'null')}catch{return null}}
function show(id){['home','map','deployment','battle','resolution','lastStand'].forEach(x=>$(x).hidden=x!==id);if(id!=='battle')cancelAnimationFrame(raf)}
function setupHome(){const old=load();$('continueRun').hidden=!old;const t=E.selfTest();$('regression').textContent=`internal invariants: ${t.pass?'PASS':'FAIL'} · ${BUILD}`}
function beginNew(){run=E.newRun(`warden-${new Date().toISOString().slice(0,10)}-${Math.floor(Math.random()*9999)}`);save();renderMap()}
function continueRun(){run=load()||E.newRun();if(run.battle?.state&&!run.battle.state.result){resumeBattle(run.battle.state);return}renderMap()}
function renderMap(){show('map');$('seedBadge').textContent=`SEED ${run.seed}`;$('emberBadge').textContent=`${'◆'.repeat(run.embers)}${'◇'.repeat(3-run.embers)} EMBERS`;$('salvageBadge').textContent=`${run.salvage} SALVAGE`;const g=$('mapGraph');g.innerHTML='';for(const n of D.nodes){const b=document.createElement('button'),done=run.resolvedNodes.some(r=>r.id===n.id),ready=run.currentNode===n.id&&!n.placeholder;b.className=`node ${done?'done':ready?'ready':'locked'}`;b.style.left=n.x+'%';b.style.top=n.y+'%';b.innerHTML=`<strong>${done?'✓ ':''}${n.name}</strong><small>${n.subtitle}</small>`;b.disabled=!ready;b.onclick=showDeployment;g.appendChild(b)}$('mapFooter').textContent=run.currentNode==='A1-B1'?'Outer Approach is ready. Choose a deployment thesis before committing.':'Outer Approach resolved. P2 will open the next node families.';save()}
function showDeployment(){deploy=E.defaultDeployment();show('deployment');renderDeployment()}
function changeUnit(lane,id,delta){deploy[lane].units[id]=Math.max(0,(deploy[lane].units[id]||0)+delta);renderDeployment()}
function renderDeployment(){const v=E.validateDeployment(deploy);$('unitBudget').textContent=`UNITS ${v.unitCost} / ${v.unitCapacity}`;$('towerBudget').textContent=`TOWERS ${v.towerCost} / ${v.towerCapacity}`;$('deployLegal').textContent=v.legal?'LEGAL':v.reasons[0]||'ILLEGAL';$('deployLegal').className=v.legal?'':'bad';$('unitBudget').className=v.unitCost>v.unitCapacity?'bad':'';$('towerBudget').className=v.towerCost>v.towerCapacity?'bad':'';$('startBattle').disabled=!v.legal;
 const u=$('unitDeploy');u.innerHTML='';for(const item of D.units){const row=document.createElement('div');row.className='unit-row';row.innerHTML=`<div class="unit-name"><b>${item.name} · ${item.cost}pt</b><small>${item.tags.join(' · ')} · ${item.role}</small></div><div class="lane-step"><button data-l="north" data-i="${item.id}" data-d="-1">−</button><span>NORTH · ${deploy.north.units[item.id]||0}</span><button data-l="north" data-i="${item.id}" data-d="1">+</button></div><div class="lane-step"><button data-l="south" data-i="${item.id}" data-d="-1">−</button><span>SOUTH · ${deploy.south.units[item.id]||0}</span><button data-l="south" data-i="${item.id}" data-d="1">+</button></div>`;u.appendChild(row)}u.querySelectorAll('button').forEach(b=>b.onclick=()=>changeUnit(b.dataset.l,b.dataset.i,Number(b.dataset.d)));
 const t=$('towerDeploy');t.innerHTML='';for(const lane of LANES){const card=document.createElement('div');card.className='tower-pick';card.innerHTML=`<b>${lane.toUpperCase()} TOWER</b><select data-tower="${lane}">${D.towers.map(x=>`<option value="${x.id}" ${deploy[lane].tower===x.id?'selected':''}>${x.name} · ${x.cost}pt</option>`).join('')}</select><select data-slot="${lane}"><option value="forward" ${deploy[lane].towerSlot==='forward'?'selected':''}>Forward slot</option><option value="rear" ${deploy[lane].towerSlot==='rear'?'selected':''}>Rear slot</option></select><small>${D.towers.find(x=>x.id===deploy[lane].tower)?.role||''}</small>`;t.appendChild(card)}t.querySelectorAll('[data-tower]').forEach(s=>s.onchange=()=>{deploy[s.dataset.tower].tower=s.value;renderDeployment()});t.querySelectorAll('[data-slot]').forEach(s=>s.onchange=()=>{deploy[s.dataset.slot].towerSlot=s.value;renderDeployment()})}
function buildAbilityUI(){const rail=$('abilityRail'),list=$('readAbilityList');rail.innerHTML='';list.innerHTML='';for(const a of D.commander.abilities){const b=document.createElement('button');b.dataset.id=a.id;b.innerHTML=`<b>${a.id==='rally'?'✦':a.id==='sunder'?'⚒':a.id==='waypoint'?'↯':'+'}</b>${a.name.toUpperCase()}`;b.onclick=()=>useAbility(a.id);rail.appendChild(b);const d=document.createElement('button');d.innerHTML=`<b>${a.name}</b><br>${a.description}`;d.onclick=()=>useAbility(a.id);list.appendChild(d)}}
function startBattle(){const v=E.validateDeployment(deploy);if(!v.legal)return;battle=E.createBattle(run,JSON.parse(JSON.stringify(deploy)));run.battle={state:battle,startedAt:new Date().toISOString()};save();selectedLane='north';reclamationShown=false;buildAbilityUI();installCanvasInput();show('battle');last=performance.now();lastSaveAt=0;centerCommander();raf=requestAnimationFrame(frame)}
function resumeBattle(state){battle=state;run.battle={state:battle,startedAt:run.battle?.startedAt||new Date().toISOString()};selectedLane=battle.commander?.lane||'north';reclamationShown=!!battle.reclamation?.active;buildAbilityUI();installCanvasInput();if(battle.lastStand?.active){show('lastStand');return}show('battle');last=performance.now();lastSaveAt=0;centerCommander();raf=requestAnimationFrame(frame)}
function useAbility(id){if(!battle||battle.commander.incapacitated)return;if(id==='waypoint'){pendingTarget='waypoint';$('targetTitle').textContent='WAYPOINT';$('targetPanel').hidden=false;return}const ok=E.useAbility(battle,id,battle.commander.lane||selectedLane);if(ok){closeRead();renderHUD()}}
function chooseTarget(lane){if(pendingTarget==='waypoint')E.useAbility(battle,'waypoint',lane);pendingTarget=null;$('targetPanel').hidden=true;renderHUD();centerCommander()}
function walkTo(lane){if(E.setCommanderLane(battle,lane)){closeRead();renderHUD()}}
function trulyPortrait(){const vv=window.visualViewport,w=vv?.width||innerWidth,h=vv?.height||innerHeight;return h>w}
function frame(now){if(trulyPortrait()){last=now;raf=requestAnimationFrame(frame);return}const dt=Math.min(.05,(now-last)/1000||0);last=now;E.stepBattle(battle,dt);draw();renderHUD();if(battle.elapsed-lastSaveAt>=2){lastSaveAt=battle.elapsed;run.battle={state:battle,startedAt:run.battle?.startedAt};save()}if(battle.reclamation.active&&!reclamationShown){reclamationShown=true;showReclamationBanner()}if(battle.lastStand?.active){run.battle={state:battle,startedAt:run.battle?.startedAt};save();cancelAnimationFrame(raf);show('lastStand');return}if(battle.result?.kind==='victory'){cancelAnimationFrame(raf);E.resolveVictory(run,battle);finishResolution('victory');return}raf=requestAnimationFrame(frame)}
function worldMetrics(r){camera.worldW=Math.max(1700,r.width*2.55);const left=120,right=camera.worldW-120;return{left,right,span:right-left,northY:r.height*.34,southY:r.height*.67,junctionX:left+(right-left)*.36}}
function clampCamera(r){const visible=r.width/camera.zoom;camera.x=Math.max(0,Math.min(Math.max(0,camera.worldW-visible),camera.x))}
function sx(wx){return(wx-camera.x)*camera.zoom}
function commanderWorld(r,m){const c=battle.commander,frontLane=c.travel?.from||c.lane||'north',base=battle.lanes[frontLane]?.front??.3,fromY=frontLane==='north'?m.northY:m.southY;let wx=m.left+m.span*base,wy=fromY;if(c.travel){const p=1-c.travel.remaining/c.travel.total,toY=c.travel.to==='north'?m.northY:m.southY;wx=m.junctionX;wy=fromY+(toY-fromY)*p}return{wx,wy}}
function draw(){const c=$('battlefield'),dpr=Math.min(devicePixelRatio||1,2),r=c.getBoundingClientRect(),w=Math.max(1,Math.floor(r.width*dpr)),h=Math.max(1,Math.floor(r.height*dpr));if(c.width!==w||c.height!==h){c.width=w;c.height=h}const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,r.width,r.height);x.fillStyle='#0b141a';x.fillRect(0,0,r.width,r.height);const m=worldMetrics(r);clampCamera(r);
 x.strokeStyle='#1e343c';x.lineWidth=28;for(const y of[m.northY,m.southY]){x.beginPath();x.moveTo(sx(m.left),y);x.lineTo(sx(m.right),y);x.stroke()}x.strokeStyle='#49635f';x.lineWidth=3;for(const y of[m.northY,m.southY]){x.beginPath();x.moveTo(sx(m.left),y);x.lineTo(sx(m.right),y);x.stroke()}x.strokeStyle='#35505a';x.lineWidth=18;x.beginPath();x.moveTo(sx(m.junctionX),m.northY);x.lineTo(sx(m.junctionX),m.southY);x.stroke();x.fillStyle='#20353c';x.fillRect(sx(m.junctionX)-16,(m.northY+m.southY)/2-16,32,32);
 for(const[id,y]of[['north',m.northY],['south',m.southY]]){const l=battle.lanes[id],fx=m.left+m.span*l.front;const pulseBonus=l.pulseActive>0?3:0;for(let i=0;i<6+pulseBonus;i++){const px=sx(fx-35-(i%5)*18),py=y-10+(i>4?20:0);x.fillStyle=i%3===0?'#8bd3c3':'#4f907f';x.beginPath();x.arc(px,py,5,0,Math.PI*2);x.fill()}for(let i=0;i<6;i++){const px=sx(fx+35+(i%5)*18),py=y-10+(i>4?20:0);x.fillStyle='#b85d5d';x.beginPath();x.arc(px,py,5,0,Math.PI*2);x.fill()}x.fillStyle='#6fc3b5';x.fillRect(sx(fx)-7,y-16,14,32);
   x.fillStyle=l.bastion>0?'#4c7772':'#382c2c';x.fillRect(sx(m.left-45),y-30,30,60);x.fillStyle=l.guard>0?'#895150':'#3b2a2a';x.fillRect(sx(m.right+15),y-28,28,56);const slotX=l.tower.slot==='forward'?m.left+m.span*.27:m.left+m.span*.10;x.fillStyle=l.tower.hp>0?'#5d8790':'#302f31';x.fillRect(sx(slotX)-10,y+(id==='north'?-56:34),20,20);if(id===selectedLane){x.strokeStyle='#7fd0be';x.lineWidth=2;x.strokeRect(sx(slotX)-14,y+(id==='north'?-60:30),28,28)}
   if(battle.reclamation.active&&battle.reclamation.artilleryLane===id){const remain=Math.max(0,battle.reclamation.artilleryTimer);x.strokeStyle='#d8865e';x.lineWidth=3;x.beginPath();x.arc(sx(fx),y,22+remain*2,0,Math.PI*2);x.stroke();x.fillStyle='#efb287';x.font='bold 10px system-ui';x.fillText(`ARTILLERY ${remain.toFixed(1)}`,sx(fx)-38,y-30)}if(battle.reclamation.active&&l.guard<=0&&l.guardDestroyedEver){x.strokeStyle='#d8b56a';x.strokeRect(sx(m.right+12),y-31,34,62)}}
 x.fillStyle=battle.gateVulnerable?'#d8a84b':'#6d5838';x.fillRect(sx(m.right+70),r.height*.23,18,r.height*.54);x.fillStyle='#42606a';x.fillRect(sx(m.left-92),r.height*.23,18,r.height*.54);
 const cp=commanderWorld(r,m);if(!battle.commander.incapacitated){x.strokeStyle='rgba(227,180,81,.28)';x.lineWidth=2;x.beginPath();x.arc(sx(cp.wx),cp.wy,48,0,Math.PI*2);x.stroke();x.fillStyle='#e3b451';x.font='bold 28px system-ui';x.fillText('◆',sx(cp.wx)-14,cp.wy-20)} }
function renderHUD(){if(!battle)return;$('battleGold').textContent=`${Math.floor(battle.gold)}g`;$('readReserve').textContent=`READ ${battle.readReserve.toFixed(1)}s`;$('coreHud').textContent=`CORE ${Math.round(battle.core)}%`;$('gateHud').textContent=`GATE ${Math.round(battle.gate)}% · ${battle.gateVulnerable?'VULNERABLE':'SHIELDED'}`;const c=battle.commander,work=c.work&&E.fieldworkState?.(battle,c.work.siteId);$('commanderHud').textContent=c.incapacitated?`REFORM ${c.reform.toFixed(1)}s`:work?`WORK ${work.remaining.toFixed(1)}s`:c.siteTravel?`APPROACH ${c.siteTravel.remaining.toFixed(1)}s`:c.travel?`WALK ${c.travel.remaining.toFixed(1)}s`:c.move?`WALK ${c.move.remaining.toFixed(1)}s`:`CMD ${Math.round(c.health)}%`;$('commanderHud').style.color=c.endangered?'#ef9a91':'';const rem=Math.max(0,battle.reclamation.trigger-battle.elapsed);$('reclamationHud').textContent=battle.reclamation.active?'RECLAMATION':`RECL ${Math.floor(rem/60)}:${String(Math.floor(rem%60)).padStart(2,'0')}`;$('battlePrompt').textContent=work?'Fieldwork underway — tap elsewhere to pause with progress saved.':battle.reclamation.active?'Reclamation active — close before the field is rebuilt.':battle.gateVulnerable?'Gate vulnerable — destroy the Gate.':'Break one lane’s Guard to expose the Gate.';
 for(const id of LANES){const l=battle.lanes[id];$(id+'Front').style.width=`${Math.round(l.front*100)}%`;$(id+'Cmd').textContent=!c.incapacitated&&!c.travel&&c.lane===id?'◆':'';const bs=$(id+'Bastion');bs.textContent=l.status;bs.className=l.status==='CRITICAL'?'critical':'';const gs=$(id+'Guard');gs.textContent=l.guard<=0?'BREACHED':E.guardState(l);gs.className=l.guard<=0||E.guardState(l)==='NET PROGRESS'?'progress':'';const ex=$(id+'Extra');if(battle.reclamation.active&&battle.reclamation.artilleryLane===id){ex.textContent=`ART ${battle.reclamation.artilleryTimer.toFixed(0)}`;ex.className='artillery'}else if(battle.reclamation.active&&l.guard<=0&&l.guardDestroyedEver){ex.textContent=`REBUILD ${Math.max(0,battle.reclamation.guardRebuildCadence-l.guardRebuild).toFixed(0)}`;ex.className='rebuild'}else if(c.travel&&(c.travel.from===id||c.travel.to===id)){ex.textContent='WALKING';ex.className='travel'}else{ex.textContent='';ex.className=''}}document.querySelectorAll('#abilityRail button').forEach(b=>{const cd=battle.abilities[b.dataset.id]||0;b.disabled=cd>0||c.incapacitated;b.title=cd>0?`${cd.toFixed(1)}s`:''});renderStructurePanel(false)}
function showReclamationBanner(){$('reclamationBanner').hidden=false;setTimeout(()=>{$('reclamationBanner').hidden=true},2600)}
function openRead(){if(!battle)return;battle.readMenuOpen=true;E.setReadMenu(battle,true);$('readPanel').hidden=false;$('readToggle').textContent='CLOSE'}
function closeRead(){if(!battle)return;battle.readMenuOpen=false;E.setReadMenu(battle,false);$('readPanel').hidden=true;$('readToggle').textContent='ACTIONS'}
function openStructure(){if(!battle)return;$('structurePanel').hidden=false;if(!battle.readMenuOpen)openRead();renderStructurePanel(true)}
function renderStructurePanel(force){if(!battle||($('structurePanel').hidden&&!force))return;const l=battle.lanes[selectedLane];$('structureTitle').textContent=`${selectedLane.toUpperCase()} · ${l.tower.name}`;$('structureStatus').textContent=`Tower ${Math.round(l.tower.hp)}/${l.tower.maxHp} · output +${l.tower.outputLevel} · next pulse ${Math.max(0,l.pulseTimer).toFixed(1)}s`;$('fortifyTower').disabled=battle.gold<28||l.tower.hp<=0;$('overchargeTower').disabled=battle.gold<36||l.tower.hp<=0;$('reinforceLane').disabled=battle.gold<30}
function buy(kind){const r=E.purchaseStructure(battle,selectedLane,kind);$('purchaseFeedback').textContent=r.ok?`${kind.toUpperCase()} committed to ${selectedLane}.`:r.reason;renderHUD()}
function laneFocus(id){selectedLane=id;document.querySelectorAll('#laneStrip [data-lane]').forEach(b=>b.classList.toggle('selected',b.dataset.lane===id));focusFront(id);renderStructurePanel(false)}
function viewportRect(){return $('battlefield').getBoundingClientRect()}
function focusWorld(wx){const r=viewportRect();camera.x=wx-r.width/(2*camera.zoom);clampCamera(r)}
function focusFront(id){const r=viewportRect(),m=worldMetrics(r),l=battle.lanes[id];focusWorld(m.left+m.span*l.front)}
function centerCommander(){if(!battle)return;const r=viewportRect(),m=worldMetrics(r),c=commanderWorld(r,m);focusWorld(c.wx)}
function installCanvasInput(){const canvas=$('battlefield');if(canvas.dataset.inputReady)return;canvas.dataset.inputReady='1';canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture?.(e.pointerId);camera.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY});if(camera.pointers.size===2){const p=[...camera.pointers.values()];camera.pinchStart={distance:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y),zoom:camera.zoom}}});canvas.addEventListener('pointermove',e=>{const p=camera.pointers.get(e.pointerId);if(!p)return;p.x=e.clientX;p.y=e.clientY;if(camera.pointers.size===1){const dx=e.clientX-p.lastX;camera.x-=dx/camera.zoom;p.lastX=e.clientX;p.lastY=e.clientY;clampCamera(viewportRect())}else if(camera.pointers.size===2&&camera.pinchStart){const ps=[...camera.pointers.values()],d=Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y);camera.zoom=Math.max(.8,Math.min(1.35,camera.pinchStart.zoom*(d/camera.pinchStart.distance)));clampCamera(viewportRect())}});const end=e=>{camera.pointers.delete(e.pointerId);if(camera.pointers.size<2)camera.pinchStart=null};canvas.addEventListener('pointerup',end);canvas.addEventListener('pointercancel',end)}
function finishResolution(kind){resolutionKind=kind;run.battle=null;save();show('resolution');if(kind==='victory'){$('resolutionEyebrow').textContent='NODE RESOLVED · VICTORY';$('resolutionTitle').textContent='THE GATE IS OPEN';$('resolutionBody').textContent='Outer Approach is broken. The Warden keeps the normal reward and the run returns to the road.';$('resolutionStats').textContent=`+180 salvage · ${run.embers} Embers remain`}else if(kind==='last-stand'){$('resolutionEyebrow').textContent='NODE RESOLVED · LAST STAND';$('resolutionTitle').textContent='A COSTLY ADVANCE';$('resolutionBody').textContent='The Core fell, but Bulwark Detonation destroyed the Gate. One Ember was spent; the normal reward was lost.';$('resolutionStats').textContent=`+120 salvage · ${run.embers} Embers remain`}else{$('resolutionEyebrow').textContent='RUN COMPLETE';$('resolutionTitle').textContent='THE ROAD REMEMBERS';$('resolutionBody').textContent='Bulwark Detonation opened the Gate, but no Ember remained to carry the company onward.';$('resolutionStats').textContent=`${run.salvage} salvage banked · 0 Embers`}}
function leaveResolution(){if(resolutionKind==='terminal')show('home');else renderMap();setTimeout(()=>window.LW_UPDATE?.applyIfReady?.(),0)}
$('newRun').onclick=beginNew;$('continueRun').onclick=continueRun;$('clearSave').onclick=()=>{localStorage.removeItem(SAVE);setupHome()};$('backToMap').onclick=renderMap;$('startBattle').onclick=startBattle;$('readToggle').onclick=()=>battle?.readMenuOpen?closeRead():openRead();document.querySelectorAll('[data-walk]').forEach(b=>b.onclick=()=>walkTo(b.dataset.walk));$('structureButton').onclick=openStructure;$('structureClose').onclick=()=>{$('structurePanel').hidden=true;closeRead()};$('fortifyTower').onclick=()=>buy('fortify');$('overchargeTower').onclick=()=>buy('overcharge');$('reinforceLane').onclick=()=>buy('reinforce');$('recenter').onclick=centerCommander;document.querySelectorAll('#laneStrip [data-lane]').forEach(b=>b.onclick=()=>laneFocus(b.dataset.lane));document.querySelectorAll('#targetPanel [data-target]').forEach(b=>b.onclick=()=>chooseTarget(b.dataset.target));$('targetCancel').onclick=()=>{pendingTarget=null;$('targetPanel').hidden=true};$('resolveLastStand').onclick=()=>{const result=E.resolveLastStand(run,battle);finishResolution(result.kind==='last-stand-advance'?'last-stand':'terminal')};$('returnMap').onclick=leaveResolution;setupHome();
})();
