(() => {
'use strict';
const BUILD='P2-0.21.0',SAVE='lane-warden-production-run-v1',NODE='A1-B2';
const $=id=>document.getElementById(id);
function saved(){try{return JSON.parse(localStorage.getItem(SAVE)||'null')}catch{return null}}
function ensureBar(){let el=$('causewayBar');if(el)return el;const prompt=$('battlePrompt');if(!prompt)return null;el=document.createElement('div');el.id='causewayBar';el.className='causeway-bar';el.hidden=true;prompt.insertAdjacentElement('afterend',el);return el}
function currentBattle(){return window.LW_ACTIVE_BATTLE||saved()?.battle?.state||null}
function setDeploymentCopy(run){const eyebrow=document.querySelector('#deployment .eyebrow'),title=document.querySelector('#deployment h2'),copy=document.querySelector('#deployment p.muted');if(!eyebrow||!title||!copy)return;if(run?.currentNode===NODE){eyebrow.textContent='SPLIT CAUSEWAY · DEPLOYMENT';title.textContent='Plan to fight in two places, not one.';copy.textContent='Raid signals alternate lanes. Rotate the Warden before impact to blunt the surge.'}else if(run?.currentNode==='A1-B3'){eyebrow.textContent='BROKEN SWITCHBACK · DEPLOYMENT';title.textContent='Decide what can hold without you.';copy.textContent='Alternating fall lines threaten each Bastion. Presence braces them best; completed fieldworks can hold while the Warden attacks elsewhere.'}else if(run?.currentNode==='A1-GK'){eyebrow.textContent='IRONBOUND GATE · GATEKEEPER';title.textContent='Break the commander, then break the Gate.';copy.textContent='Iron Edicts target your most advanced lane. Presence or completed works can answer them. A failed Last Stand here costs two Embers.'}else{eyebrow.textContent='OUTER APPROACH · DEPLOYMENT';title.textContent='Choose what each lane is trying to do.';copy.textContent='Six Unit points and four Tower points before run bonuses. Deployment locks when battle begins.'}}
function setMapCopy(run){const intro=document.querySelector('#map .map-shell > div:first-child p.muted'),footer=$('mapFooter');if(intro)intro.textContent='A complete short Act 1 route: two opening battles, one Forge project, the Broken Switchback, a Rift decision, and the Ironbound Gatekeeper.';if(!footer)return;const copy={'A1-B1':'Outer Approach is ready. Establish the run.','A1-B2':'Split Causeway is ready. Read the raid signal and rotate.','A1-F1':'The Ruined Forge can install one roster-specific project.','A1-B3':'Broken Switchback is ready. Presence and fieldworks now compete for your time.','A1-R1':'The Ashen Rift offers hidden power for an Ember—or certain Salvage.','A1-GK':'The Ironbound Gate waits. Victory earns the premium Act packet; Last Stand costs two Embers.','A1-END':'Act 1 complete.'};footer.textContent=copy[run?.currentNode]||'The road records every battle and permanent decision.'}
function laneState(id,b,c){const ex=$(id+'Extra');if(!ex)return;if(c.phase==='telegraph'&&c.target===id){const braced=!b.commander.incapacitated&&!b.commander.travel&&b.commander.lane===id;ex.textContent=braced?`BRACED ${c.timer.toFixed(0)}`:`RAID ${c.timer.toFixed(0)}`;ex.className=braced?'causeway-braced':'causeway-warning'}else if(c.phase==='surge'&&c.lastTarget===id){ex.textContent=c.intercepted?'INTERCEPTED':'SURGE';ex.className=c.intercepted?'causeway-braced':'causeway-surge'}else if(c.phase==='recovery'&&c.nextTarget===id){ex.textContent='NEXT';ex.className='causeway-next'}}
function battleUI(b){const bar=ensureBar();if(!bar)return;if(!b||b.nodeId!==NODE||!b.causeway){bar.hidden=true;return}const c=b.causeway,target=c.target||c.lastTarget||c.nextTarget||'north',last=c.lastTarget||target,next=c.nextTarget||target;bar.hidden=false;bar.className=`causeway-bar ${c.phase}${c.intercepted?' intercepted':''}`;const braced=c.phase==='telegraph'&&c.target&&!b.commander.incapacitated&&!b.commander.travel&&b.commander.lane===c.target;
 if(c.phase==='telegraph')bar.innerHTML=`<b>${braced?'BRACED':'RAID SIGNAL'} · ${target.toUpperCase()}</b><span>${c.timer.toFixed(1)}s to impact · ${braced?'hold the lane to intercept':'walk or Waypoint now'}</span>`;
 else if(c.phase==='surge')bar.innerHTML=`<b>${c.intercepted?'INTERCEPTED':'SURGE'} · ${last.toUpperCase()}</b><span>${c.timer.toFixed(1)}s · ${c.intercepted?'pressure blunted + 8g tempo':'heavy enemy pressure; presence still helps'}</span>`;
 else bar.innerHTML=`<b>ROTATION WINDOW</b><span>${c.timer.toFixed(1)}s · next raid ${next.toUpperCase()}</span>`;
 const prompt=$('battlePrompt');if(prompt&&!b.reclamation?.active)prompt.textContent=c.phase==='telegraph'?(braced?'Hold position through impact to intercept the raid.':`Rotate to ${target.toUpperCase()} before the signal hits.`):c.phase==='surge'?(c.intercepted?'Raid intercepted — use the tempo window.':`Stabilize ${last.toUpperCase()} or exploit the opposite lane.`):`Next raid will hit ${next.toUpperCase()}. Plan the rotation now.`;
 laneState('north',b,c);laneState('south',b,c);
 const hud=document.querySelector('#battle .hud-top > b');if(hud)hud.textContent='THE WARDEN · SPLIT CAUSEWAY';
}
function homeUI(){const eyebrow=document.querySelector('#home .eyebrow'),p=document.querySelector('#home .home-card > p'),build=document.querySelector('#battle .build-id');if(eyebrow)eyebrow.textContent='P2 · IRONBOUND GATE · P2-0.21.0';if(p)p.textContent='A complete short Act 1 route: survive the Switchback, choose what the Rift takes, and confront the Ironbound Gatekeeper.';if(build)build.textContent='0.21.0';const reg=$('regression');if(reg&&reg.textContent.includes('P1-0.11.0'))reg.textContent=reg.textContent.replace('P1-0.11.0',BUILD)}
function loop(){const run=saved(),b=currentBattle();homeUI();setDeploymentCopy(run);setMapCopy(run);battleUI(b);requestAnimationFrame(loop)}
requestAnimationFrame(loop);
})();
