(() => {
'use strict';
const BUILD='P2-0.16.0',SAVE='lane-warden-production-run-v1',NODE='A1-B2';
const $=id=>document.getElementById(id);
function saved(){try{return JSON.parse(localStorage.getItem(SAVE)||'null')}catch{return null}}
function ensureBar(){let el=$('causewayBar');if(el)return el;const prompt=$('battlePrompt');if(!prompt)return null;el=document.createElement('div');el.id='causewayBar';el.className='causeway-bar';el.hidden=true;prompt.insertAdjacentElement('afterend',el);return el}
function currentBattle(){return window.LW_ACTIVE_BATTLE||saved()?.battle?.state||null}
function setDeploymentCopy(run){const eyebrow=document.querySelector('#deployment .eyebrow'),title=document.querySelector('#deployment h2'),copy=document.querySelector('#deployment p.muted');if(!eyebrow||!title||!copy)return;if(run?.currentNode===NODE){eyebrow.textContent='SPLIT CAUSEWAY · EASY POOL · DEPLOYMENT';title.textContent='Plan to fight in two places, not one.';copy.textContent='Raid signals alternate lanes. You get 8 seconds of warning: a normal 7-second walk can make it if you react immediately, while Waypoint and movement rewards create breathing room.'}else{eyebrow.textContent='OUTER APPROACH · DEPLOYMENT';title.textContent='Choose what each lane is trying to do.';copy.textContent='Six Unit points and four Tower points before run bonuses. Deployment locks when battle begins.'}}
function setMapCopy(run){const intro=document.querySelector('#map .map-shell > div:first-child p.muted'),footer=$('mapFooter');if(intro)intro.textContent='Act 1 Easy Pool is live: Outer Approach tests concentration; Split Causeway tests Commander rotation and lane triage.';if(!footer)return;if(run?.currentNode===NODE)footer.textContent='Split Causeway is ready. Watch the raid signal, rotate before impact, and learn what your first reward changed.';else if(run?.currentNode==='A1-F1')footer.textContent='Split Causeway resolved. The Ruined Forge is the next P2 production seam.'}
function laneState(id,b,c){const ex=$(id+'Extra');if(!ex)return;if(c.phase==='telegraph'&&c.target===id){const braced=!b.commander.incapacitated&&!b.commander.travel&&b.commander.lane===id;ex.textContent=braced?`BRACED ${c.timer.toFixed(0)}`:`RAID ${c.timer.toFixed(0)}`;ex.className=braced?'causeway-braced':'causeway-warning'}else if(c.phase==='surge'&&c.lastTarget===id){ex.textContent=c.intercepted?'INTERCEPTED':'SURGE';ex.className=c.intercepted?'causeway-braced':'causeway-surge'}else if(c.phase==='recovery'&&c.nextTarget===id){ex.textContent='NEXT';ex.className='causeway-next'}}
function battleUI(b){const bar=ensureBar();if(!bar)return;if(!b||b.nodeId!==NODE||!b.causeway){bar.hidden=true;return}const c=b.causeway,target=c.target||c.lastTarget||c.nextTarget||'north',last=c.lastTarget||target,next=c.nextTarget||target;bar.hidden=false;bar.className=`causeway-bar ${c.phase}${c.intercepted?' intercepted':''}`;const braced=c.phase==='telegraph'&&c.target&&!b.commander.incapacitated&&!b.commander.travel&&b.commander.lane===c.target;
 if(c.phase==='telegraph')bar.innerHTML=`<b>${braced?'BRACED':'RAID SIGNAL'} · ${target.toUpperCase()}</b><span>${c.timer.toFixed(1)}s to impact · ${braced?'hold the lane to intercept':'walk or Waypoint now'}</span>`;
 else if(c.phase==='surge')bar.innerHTML=`<b>${c.intercepted?'INTERCEPTED':'SURGE'} · ${last.toUpperCase()}</b><span>${c.timer.toFixed(1)}s · ${c.intercepted?'pressure blunted + 8g tempo':'heavy enemy pressure; presence still helps'}</span>`;
 else bar.innerHTML=`<b>ROTATION WINDOW</b><span>${c.timer.toFixed(1)}s · next raid ${next.toUpperCase()}</span>`;
 const prompt=$('battlePrompt');if(prompt&&!b.reclamation?.active)prompt.textContent=c.phase==='telegraph'?(braced?'Hold position through impact to intercept the raid.':`Rotate to ${target.toUpperCase()} before the signal hits.`):c.phase==='surge'?(c.intercepted?'Raid intercepted — use the tempo window.':`Stabilize ${last.toUpperCase()} or exploit the opposite lane.`):`Next raid will hit ${next.toUpperCase()}. Plan the rotation now.`;
 laneState('north',b,c);laneState('south',b,c);
 const hud=document.querySelector('#battle .hud-top > b');if(hud)hud.textContent='THE WARDEN · SPLIT CAUSEWAY';
}
function homeUI(){const eyebrow=document.querySelector('#home .eyebrow'),p=document.querySelector('#home .home-card > p'),build=document.querySelector('#battle .build-id');if(eyebrow)eyebrow.textContent='P2 · TACTICAL MODELS · P2-0.16.0';if(p)p.textContent='Living Lanes now deploys readable miniature formations whose silhouettes, motion, formation, and casualties carry the battle state.';if(build)build.textContent='0.16.0';const reg=$('regression');if(reg&&reg.textContent.includes('P1-0.11.0'))reg.textContent=reg.textContent.replace('P1-0.11.0',BUILD)}
function loop(){const run=saved(),b=currentBattle();homeUI();setDeploymentCopy(run);setMapCopy(run);battleUI(b);requestAnimationFrame(loop)}
requestAnimationFrame(loop);
})();
