(() => {
'use strict';
const D=()=>window.LW_DATA;
function mulberry32(a){return function(){let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function hashSeed(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function newRun(seedText){const seed=hashSeed(seedText||`${Date.now()}`);return{schema:2,version:D().version,seed,seedLabel:seedText||String(seed),commanderId:'warden',embers:3,salvage:0,currentNode:'A1-B1',resolvedNodes:[],mapVisitCount:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),battle:null}}
function emptyUnits(){return Object.fromEntries(D().units.map(u=>[u.id,0]))}
function defaultDeployment(){const n=emptyUnits(),s=emptyUnits();n.ironjack=1;n.ram=1;s.ironjack=1;s.slingline=1;return{north:{units:n,tower:'pylon',towerSlot:'forward'},south:{units:s,tower:'frost',towerSlot:'rear'}}}
function deploymentCost(dep){let unitCost=0,towerCost=0;for(const lane of ['north','south']){for(const u of D().units)unitCost+=(dep[lane].units[u.id]||0)*u.cost;const t=D().towers.find(x=>x.id===dep[lane].tower);towerCost+=t?.cost||0}return{unitCost,towerCost}}
function validateDeployment(dep){const c=deploymentCost(dep),reasons=[];if(c.unitCost>D().deployment.unitCapacity)reasons.push(`Unit points ${c.unitCost}/${D().deployment.unitCapacity}`);if(c.towerCost>D().deployment.towerCapacity)reasons.push(`Tower points ${c.towerCost}/${D().deployment.towerCapacity}`);for(const lane of ['north','south']){const units=Object.values(dep[lane].units).reduce((a,b)=>a+b,0);if(units<1)reasons.push(`${lane} needs at least one committed unit`);if(dep[lane].tower&&!D().towers.some(t=>t.id===dep[lane].tower))reasons.push(`${lane} tower is invalid`)}return{legal:reasons.length===0,reasons,...c,unitCapacity:D().deployment.unitCapacity,towerCapacity:D().deployment.towerCapacity}}
function lanePower(dep){let p=0,d=0,siege=0,unitCost=0;for(const u of D().units){const n=dep.units[u.id]||0;p+=n*u.power;d+=n*u.durability;unitCost+=n*u.cost;if(u.tags.includes('siege'))siege+=n}return{power:p,durability:d,siege,unitCost}}
function towerState(dep){const t=D().towers.find(x=>x.id===dep.tower);return{id:t?.id||null,name:t?.name||'Empty slot',role:t?.role||'No tower',effect:t?.effect||'none',slot:dep.towerSlot||'rear',basePower:t?.power||0,hp:t?100:0,maxHp:t?100:0,outputLevel:0,fortifyLevel:0}}
function createBattle(run,deployment=defaultDeployment()){
 const legal=validateDeployment(deployment);if(!legal.legal)throw new Error(`Illegal deployment: ${legal.reasons.join(', ')}`);
 const rng=mulberry32(run.seed^0xA11CE),N=lanePower(deployment.north),S=lanePower(deployment.south),enc=D().encounter;
 const makeLane=(id,pow,dep,enemy,cadence)=>({id,front:id==='north'?.37:.42,bastion:100,guard:100,guardPrev:100,guardDestroyedEver:false,guardRebuild:0,baseEnemyPower:enemy,allyBase:pow.power,allyDurability:pow.durability,siege:pow.siege,unitCost:pow.unitCost,regen:id==='north'?2.4:2.6,tower:towerState(dep),status:'STABLE',pulseTimer:2+rng()*3,pulseCadence:cadence,pulseActive:0,pulseCount:0,reinforcementPulses:0});
 return{schema:2,seed:run.seed,nodeId:'A1-B1',elapsed:0,gold:42,core:100,gate:100,gateVulnerable:false,gateVulnerabilityLatched:false,readReserve:4,readMenuOpen:false,lastStand:null,result:null,
 commander:{lane:'north',health:100,maxHealth:D().commander.maxHealth,incapacitated:false,reform:0,travel:null,endangered:false},
 abilities:{rally:0,sunder:0,waypoint:0,conscript:0},effects:{north:{rally:0,conscript:0},south:{rally:0,conscript:0}},
 reclamation:{active:false,trigger:enc.reclamationTrigger,startedAt:null,artilleryTimer:enc.artilleryCadence,artilleryLane:null,artilleryTelegraph:enc.artilleryTelegraph,guardRebuildCadence:enc.guardRebuildCadence},
 lanes:{north:makeLane('north',N,deployment.north,3.15+rng()*.18,16),south:makeLane('south',S,deployment.south,3.35+rng()*.22,18)},deployment,events:[{t:0,type:'battle-start'}]}
}
function guardState(l){if(l.guard<=0)return'BREACHED';const delta=l.guard-l.guardPrev;if(l.guard>=99.5)return'STALLING';if(delta>0.08)return'REGENERATING';if(delta<-0.08)return'NET PROGRESS';return'STALLING'}
function bastionState(hp){if(hp<=0)return'FALLEN';if(hp<28)return'CRITICAL';if(hp<62)return'WATCH';return'STABLE'}
function towerModifiers(l){if(!l.tower.id||l.tower.hp<=0)return{friendly:1,enemy:1,add:0};const level=1+l.tower.outputLevel*.18;switch(l.tower.effect){case'amplify':return{friendly:1+.18*level,enemy:1,add:0};case'slow':return{friendly:1,enemy:Math.max(.72,1-.10*level),add:0};case'defense':return{friendly:1,enemy:1,add:.42*level};case'swarm':return{friendly:1,enemy:1,add:.50*level};default:return{friendly:1,enemy:1,add:0}}}
function commanderPresent(b,id){return !b.commander.incapacitated&&!b.commander.travel&&b.commander.lane===id}
function beginIncapacitation(b){if(b.commander.incapacitated)return;b.commander.incapacitated=true;b.commander.reform=D().commander.reformTime;b.commander.health=0;b.commander.travel=null;b.commander.lane=null;b.commander.endangered=false;b.events.push({t:b.elapsed,type:'commander-incapacitated'})}
function stepCommander(b,sd){for(const k of Object.keys(b.abilities))b.abilities[k]=Math.max(0,b.abilities[k]-sd);if(b.commander.incapacitated){b.commander.reform=Math.max(0,b.commander.reform-sd);if(b.commander.reform<=0){b.commander.incapacitated=false;b.commander.lane='north';b.commander.health=b.commander.maxHealth;b.events.push({t:b.elapsed,type:'commander-reformed',anchor:'core'})}return}if(b.commander.travel){b.commander.travel.remaining=Math.max(0,b.commander.travel.remaining-sd);if(b.commander.travel.remaining<=0){b.commander.lane=b.commander.travel.to;b.events.push({t:b.elapsed,type:'commander-arrived',lane:b.commander.lane});b.commander.travel=null}}}
function chooseArtilleryLane(b){return Object.values(b.lanes).slice().sort((a,c)=>c.front-a.front)[0].id}
function startReclamation(b){if(b.reclamation.active)return;b.reclamation.active=true;b.reclamation.startedAt=b.elapsed;b.reclamation.artilleryTimer=8;b.events.push({t:b.elapsed,type:'reclamation-start'})}
function stepReclamation(b,sd){const r=b.reclamation;if(!r.active&&b.elapsed>=r.trigger)startReclamation(b);if(!r.active)return;r.artilleryTimer-=sd;if(!r.artilleryLane&&r.artilleryTimer<=r.artilleryTelegraph){r.artilleryLane=chooseArtilleryLane(b);b.events.push({t:b.elapsed,type:'artillery-telegraph',lane:r.artilleryLane})}if(r.artilleryTimer<=0){const lane=b.lanes[r.artilleryLane||chooseArtilleryLane(b)];lane.front=Math.max(.08,lane.front-.055);if(lane.tower.hp>0)lane.tower.hp=Math.max(0,lane.tower.hp-12);if(commanderPresent(b,lane.id)){b.commander.health=Math.max(0,b.commander.health-18);if(b.commander.health<=0)beginIncapacitation(b)}b.events.push({t:b.elapsed,type:'artillery-impact',lane:lane.id});r.artilleryLane=null;r.artilleryTimer=D().encounter.artilleryCadence}for(const l of Object.values(b.lanes)){if(l.guard<=0&&l.guardDestroyedEver){l.guardRebuild+=sd;if(l.guardRebuild>=r.guardRebuildCadence){l.guard=35;l.guardPrev=35;l.guardRebuild=0;b.events.push({t:b.elapsed,type:'guard-rebuilt',lane:l.id})}}else l.guardRebuild=0}}
function stepBattle(b,dt){
 if(b.result||b.lastStand?.active)return b;const scale=b.readMenuOpen&&b.readReserve>0?.35:1;if(b.readMenuOpen&&b.readReserve>0)b.readReserve=Math.max(0,b.readReserve-dt);else if(!b.readMenuOpen)b.readReserve=Math.min(4,b.readReserve+dt*.22);const sd=dt*scale;b.elapsed+=sd;b.gold=Math.min(99,b.gold+sd*.16);stepCommander(b,sd);stepReclamation(b,sd);
 for(const[id,l]of Object.entries(b.lanes)){l.guardPrev=l.guard;l.pulseTimer-=sd;if(l.pulseTimer<=0){l.pulseCount++;l.pulseActive=6;l.pulseTimer=l.pulseCadence;if(l.reinforcementPulses>0){l.reinforcementPulses--;b.effects[id].conscript=6}b.events.push({t:b.elapsed,type:'pulse',lane:id,count:l.pulseCount})}l.pulseActive=Math.max(0,l.pulseActive-sd);b.effects[id].rally=Math.max(0,b.effects[id].rally-sd);b.effects[id].conscript=Math.max(0,b.effects[id].conscript-sd);
   const tm=towerModifiers(l),presence=commanderPresent(b,id)?D().commander.presence:1,rally=b.effects[id].rally>0?1.35:1,cons=b.effects[id].conscript>0?1.3:1,pulse=l.pulseActive>0?1.14:.9;let friendly=(l.allyBase*tm.friendly+tm.add)*presence*rally*cons*pulse;let enemy=l.baseEnemyPower*tm.enemy;if(b.reclamation.active&&l.front<=.13)enemy*=1.35;const pressure=friendly-enemy;
   b.gold=Math.min(99,b.gold+Math.max(0,friendly)*sd*(commanderPresent(b,id)?.055:.025));l.front=Math.max(.08,Math.min(.92,l.front+pressure*sd*.0029));
   if(pressure>0){if(l.front>.70&&l.guard>0){const before=l.guard;l.guard=Math.max(0,l.guard-pressure*sd*.88);if(l.guard>0)l.guard=Math.min(100,l.guard+l.regen*sd*.42);if(before>0&&l.guard<=0){l.guardDestroyedEver=true;b.gateVulnerabilityLatched=true;b.events.push({t:b.elapsed,type:'guard-broken',lane:id})}}else if(l.front>.70&&l.guard<=0&&b.gateVulnerabilityLatched){const siege=1+l.siege*.34;b.gate=Math.max(0,b.gate-pressure*sd*.46*siege)}}else{const threat=(-pressure)*sd*.22;if(l.front<.30&&l.tower.hp>0)l.tower.hp=Math.max(0,l.tower.hp-threat*.55);if(l.front<.22){if(l.bastion>0)l.bastion=Math.max(0,l.bastion-threat*1.15);else b.core=Math.max(0,b.core-threat*1.55)}l.front=Math.max(.08,l.front-threat*.003)}
   if(commanderPresent(b,id)&&pressure<-.25){b.commander.health=Math.max(0,b.commander.health-(-pressure)*sd*.52);b.commander.endangered=b.commander.health<35;if(b.commander.health<=0)beginIncapacitation(b)}l.status=bastionState(l.bastion)
 }
 b.gateVulnerable=b.gateVulnerabilityLatched;if(b.gate<=0){b.result={kind:'victory',at:b.elapsed};b.events.push({t:b.elapsed,type:'victory'})}else if(b.core<=0){b.lastStand={active:true,phase:'core-fallen',t:0,payable:true};b.events.push({t:b.elapsed,type:'core-fallen'})}return b
}
function useAbility(b,id,targetLane){if(b.result||b.lastStand?.active||b.commander.incapacitated)return false;if((b.abilities[id]||0)>0)return false;const lane=targetLane||b.commander.lane;if(!lane||!b.lanes[lane])return false;const def=D().commander.abilities.find(a=>a.id===id);if(!def)return false;if(id==='rally')b.effects[lane].rally=6;if(id==='sunder'){const l=b.lanes[lane];if(l.guard<=0&&b.gateVulnerabilityLatched&&l.front>.62)b.gate=Math.max(0,b.gate-14);else if(l.guard>0&&l.front>.62){const before=l.guard;l.guard=Math.max(0,l.guard-18);if(before>0&&l.guard<=0){l.guardDestroyedEver=true;b.gateVulnerabilityLatched=true;b.events.push({t:b.elapsed,type:'guard-broken',lane})}}else l.front=Math.min(.92,l.front+.035)}if(id==='waypoint'){b.commander.travel=null;b.commander.lane=lane;b.events.push({t:b.elapsed,type:'waypoint',lane})}if(id==='conscript'){if(b.lanes[lane].unitCost<=0)return false;b.lanes[lane].reinforcementPulses+=2}b.abilities[id]=def.cooldown;b.events.push({t:b.elapsed,type:'ability',id,lane});return true}
function setCommanderLane(b,lane){if(!b.lanes[lane]||b.commander.incapacitated||b.commander.travel||b.commander.lane===lane)return false;const from=b.commander.lane;b.commander.travel={from,to:lane,total:D().commander.walkTime,remaining:D().commander.walkTime};b.events.push({t:b.elapsed,type:'commander-walk',from,to:lane});return true}
function setReadMenu(b,open){b.readMenuOpen=!!open}
function purchaseStructure(b,laneId,kind){const l=b.lanes[laneId];if(!l||b.result||b.lastStand?.active)return{ok:false,reason:'Unavailable'};const costs={fortify:28,overcharge:36,reinforce:30},cost=costs[kind];if(!cost)return{ok:false,reason:'Unknown purchase'};if(b.gold<cost)return{ok:false,reason:`Need ${cost}g`};if((kind==='fortify'||kind==='overcharge')&&(!l.tower.id||l.tower.hp<=0))return{ok:false,reason:'Tower unavailable'};b.gold-=cost;if(kind==='fortify'){l.tower.fortifyLevel++;l.tower.maxHp+=25;l.tower.hp=Math.min(l.tower.maxHp,l.tower.hp+35)}if(kind==='overcharge')l.tower.outputLevel++;if(kind==='reinforce')l.reinforcementPulses+=2;b.events.push({t:b.elapsed,type:'purchase',lane:laneId,kind,cost});return{ok:true,cost}}
function resolveLastStand(run,b){if(!b.lastStand?.active)return null;b.gate=0;b.gateVulnerable=true;b.gateVulnerabilityLatched=true;const payable=run.embers>0;if(payable){run.embers-=1;run.salvage+=120;run.resolvedNodes.push({id:b.nodeId,result:'last-stand',at:new Date().toISOString()});run.currentNode='A1-F1';b.result={kind:'last-stand-advance',at:b.elapsed}}else{b.result={kind:'terminal',at:b.elapsed};run.endedAt=new Date().toISOString();run.endReason='last-stand-no-ember'}b.lastStand={active:false,phase:'resolved',payable};return b.result}
function resolveVictory(run,b){run.salvage+=180;run.resolvedNodes.push({id:b.nodeId,result:'victory',at:new Date().toISOString()});run.currentNode='A1-F1';b.result=b.result||{kind:'victory',at:b.elapsed};return{reward:{salvage:180},nextNode:'A1-F1'}}
function selfTest(){const r=newRun('regression-seed'),dep=defaultDeployment(),v=validateDeployment(dep),b=createBattle(r,dep);const gate=b.gate;b.lanes.north.bastion=0;b.lanes.north.guard=0;b.lanes.north.guardDestroyedEver=true;b.gateVulnerabilityLatched=true;b.gateVulnerable=true;for(const l of Object.values(b.lanes)){l.allyBase=0;l.baseEnemyPower=0;l.tower.hp=0}stepBattle(b,.5);const noPassiveGate=b.gate===gate;const beforeSunder=b.gate;b.abilities.sunder=0;b.commander.lane='north';b.lanes.north.front=.8;useAbility(b,'sunder','north');const sunderGate=b.gate<beforeSunder;const walkTest=createBattle(newRun('walk'),dep);setCommanderLane(walkTest,'south');const walkNotInstant=walkTest.commander.travel?.to==='south'&&walkTest.commander.lane==='north';const checks={deploymentLegal:v.legal&&v.unitCost===6&&v.towerCost===4,twoLanes:Object.keys(b.lanes).length===2,zeroEmberLegal:(()=>{const rr=newRun('z');rr.embers=0;return rr.embers===0})(),gateNeedsGuard:b.gateVulnerabilityLatched,deadGuardNotAutoWin:noPassiveGate,sunderHitsOpenGate:sunderGate,walkUsesTravel:walkNotInstant,deterministic:(()=>{const a=createBattle(newRun('x'),dep),c=createBattle(newRun('x'),dep);return a.lanes.north.baseEnemyPower===c.lanes.north.baseEnemyPower})()};return{pass:Object.values(checks).every(Boolean),checks}}
window.LW_ENGINE={newRun,defaultDeployment,deploymentCost,validateDeployment,createBattle,stepBattle,useAbility,setCommanderLane,setReadMenu,purchaseStructure,resolveLastStand,resolveVictory,selfTest,guardState,bastionState};
})();