(() => {
'use strict';
const E=window.LW_ENGINE,L=window.LW_LIVING;
if(!E||!L)return;
const BUILD='P2-0.15.0';
const base=document.getElementById('battlefield'),battleEl=document.getElementById('battle');if(!base||!battleEl)return;
const canvas=document.createElement('canvas');canvas.id='livingBattlefield';canvas.setAttribute('aria-hidden','true');Object.assign(canvas.style,{position:'absolute',inset:'0',width:'100%',height:'100%',zIndex:'1',pointerEvents:'none'});base.insertAdjacentElement('afterend',canvas);
let targetPing=null,press=null;
function active(){const b=window.LW_ACTIVE_BATTLE;return b?.living?b:null}
function metrics(r){const left=Math.max(78,r.width*.075),right=Math.min(r.width-80,r.width*.925);return{left,right,span:right-left,northY:r.height*.34,southY:r.height*.67}}
function px(m,x){return m.left+m.span*((x-.09)/(.91-.09))}
function laneY(m,id){return id==='north'?m.northY:m.southY}
function hpBar(ctx,x,y,w,p,fill){ctx.fillStyle='rgba(2,7,10,.75)';ctx.fillRect(x-w/2,y,w,4);ctx.fillStyle=fill;ctx.fillRect(x-w/2,y,w*Math.max(0,Math.min(1,p)),4)}
function drawCohort(ctx,m,c,now){const x=px(m,c.x),y=laneY(m,c.lane),friendly=c.side==='friendly',isAlive=c.hp>0;let alpha=1;if(!isAlive&&c.deadAt!=null)alpha=Math.max(0,1-(now-c.deadAt)/1.4);ctx.save();ctx.globalAlpha=alpha;const pipCount=Math.max(3,Math.min(9,c.count||6));const spread=3.8;const stagger=c.id.charCodeAt(c.id.length-1)%3;for(let i=0;i<pipCount;i++){const row=i%2,col=Math.floor(i/2),dx=(col-(pipCount/4))*spread,dy=(row?5:-3)+(stagger-1);ctx.beginPath();ctx.arc(x+dx,y+dy,isAlive?3.3:2.7,0,Math.PI*2);ctx.fillStyle=friendly?(c.reinforced?'#d6c16b':'#79cabb'):(c.kind==='raider'?'#d98c66':c.kind==='brute'?'#b75252':'#c96762');ctx.fill()}
 if(c.state==='engaged'||c.state==='supporting'){ctx.strokeStyle=friendly?'rgba(121,202,187,.7)':'rgba(210,100,90,.7)';ctx.lineWidth=1.4;ctx.beginPath();ctx.arc(x,y,13,0,Math.PI*2);ctx.stroke()}
 hpBar(ctx,x,y-14,24,c.hp/c.maxHp,friendly?'#74c5b5':'#ce6b63');if(c.reinforced&&isAlive){ctx.fillStyle='#e0c76c';ctx.font='bold 7px system-ui';ctx.textAlign='center';ctx.fillText('REINF',x,y+18)}ctx.restore()}
function drawObjective(ctx,m,b,lane){const l=b.lanes[lane],y=laneY(m,lane),bx=px(m,.09),gx=px(m,.91),gate=px(m,.965);ctx.fillStyle=l.bastion>0?'#446e69':'#342a2b';ctx.fillRect(bx-12,y-26,24,52);ctx.fillStyle=l.guard>0?'#8e5552':'#3c2b2c';ctx.fillRect(gx-10,y-24,20,48);ctx.fillStyle=b.gateVulnerable?'#d6a64f':'#6c593a';ctx.fillRect(gate-6,y-31,12,62);hpBar(ctx,bx,y+31,34,l.bastion/100,'#68ad9f');hpBar(ctx,gx,y+29,34,l.guard/100,'#c36b65');ctx.fillStyle='#8ca0a3';ctx.font='bold 7px system-ui';ctx.textAlign='center';ctx.fillText('BASTION',bx,y-33);ctx.fillText(l.guard>0?'GUARD':'BREACHED',gx,y-31)}
function drawTower(ctx,m,b,lane){const l=b.lanes[lane],t=l.tower;if(!t?.id)return;const tx=px(m,t.slot==='forward'?.38:.22),y=laneY(m,lane)+(lane==='north'?-42:42);ctx.fillStyle=t.hp>0?'#5d8992':'#342f31';ctx.fillRect(tx-8,y-8,16,16);ctx.strokeStyle='rgba(93,137,146,.18)';ctx.beginPath();ctx.arc(tx,y,Math.max(20,m.span*.16/.82),0,Math.PI*2);ctx.stroke();ctx.fillStyle='#80989d';ctx.font='6px system-ui';ctx.textAlign='center';ctx.fillText(t.name?.split(' ')[0]||'TOWER',tx,y+(lane==='north'?-12:18))}
function drawCommander(ctx,m,b){const c=b.commander;if(!c||c.incapacitated)return;let lane=c.lane||c.travel?.from||'north',x=c.pos??.3,y=laneY(m,lane);if(c.travel){const p=1-c.travel.remaining/c.travel.total,fromY=laneY(m,c.travel.from),toY=laneY(m,c.travel.to),junction=.38;x=c.travel.fromPos??c.pos??.3;if(p<.45){const q=p/.45;x=x+(junction-x)*q;y=fromY}else if(p<.55){x=junction;y=fromY+(toY-fromY)*((p-.45)/.10)}else{const q=(p-.55)/.45,x2=c.travel.targetPos??.3;x=junction+(x2-junction)*q;y=toY}}
 const sx=px(m,x);ctx.strokeStyle='rgba(226,180,83,.25)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(sx,y,m.span*(L.cfg.presenceRadius/.82),0,Math.PI*2);ctx.stroke();ctx.fillStyle='#e3b451';ctx.font='bold 25px system-ui';ctx.textAlign='center';ctx.fillText('◆',sx,y-12);ctx.fillStyle='#e3c681';ctx.font='bold 7px system-ui';ctx.fillText(c.move?'MOVING':'WARDEN',sx,y+20)}
function drawLane(ctx,m,b,id){const y=laneY(m,id);ctx.strokeStyle='#1d3138';ctx.lineWidth=30;ctx.beginPath();ctx.moveTo(m.left,y);ctx.lineTo(m.right,y);ctx.stroke();ctx.strokeStyle='#46625f';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(m.left,y);ctx.lineTo(m.right,y);ctx.stroke();ctx.fillStyle='#789095';ctx.font='bold 8px system-ui';ctx.textAlign='left';ctx.fillText(id.toUpperCase(),m.left,y-22);drawObjective(ctx,m,b,id);drawTower(ctx,m,b,id);const ll=b.living.lanes[id];for(const c of [...ll.friendly,...ll.enemy])drawCohort(ctx,m,c,b.elapsed)}
function draw(){const b=active(),r=base.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.floor(r.width*dpr)),h=Math.max(1,Math.floor(r.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,r.width,r.height);if(b&&!battleEl.hidden){ctx.fillStyle='#091116';ctx.fillRect(0,0,r.width,r.height);const m=metrics(r);drawLane(ctx,m,b,'north');drawLane(ctx,m,b,'south');ctx.strokeStyle='#314b54';ctx.lineWidth=14;const jx=px(m,.38);ctx.beginPath();ctx.moveTo(jx,m.northY);ctx.lineTo(jx,m.southY);ctx.stroke();ctx.fillStyle='#314b54';ctx.fillRect(jx-10,(m.northY+m.southY)/2-10,20,20);drawCommander(ctx,m,b);if(targetPing&&performance.now()-targetPing.at<850){ctx.strokeStyle='rgba(226,180,83,.75)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(px(m,targetPing.pos),laneY(m,targetPing.lane),10+(performance.now()-targetPing.at)/55,0,Math.PI*2);ctx.stroke()}ctx.fillStyle='rgba(145,165,168,.7)';ctx.font='7px system-ui';ctx.textAlign='center';ctx.fillText('TAP A LANE POSITION TO MOVE THE WARDEN',r.width/2,r.height-68)}requestAnimationFrame(draw)}
function pointerPos(e){const r=base.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top,r}}
base.addEventListener('pointerdown',e=>{const b=active();if(!b)return;e.stopImmediatePropagation();const p=pointerPos(e);press={id:e.pointerId,x:p.x,y:p.y,moved:false};base.setPointerCapture?.(e.pointerId)},true);
base.addEventListener('pointermove',e=>{if(!press||e.pointerId!==press.id)return;e.stopImmediatePropagation();const p=pointerPos(e);if(Math.hypot(p.x-press.x,p.y-press.y)>10)press.moved=true},true);
function endPointer(e){if(!press||e.pointerId!==press.id)return;e.stopImmediatePropagation();const b=active(),p=pointerPos(e),start=press;press=null;if(!b||start.moved)return;const m=metrics(p.r),lane=Math.abs(p.y-m.northY)<=Math.abs(p.y-m.southY)?'north':'south',raw=.09+((p.x-m.left)/m.span)*.82,pos=Math.max(.12,Math.min(.86,raw));if(E.setCommanderPosition?.(b,lane,pos)){targetPing={lane,pos,at:performance.now()}}}
base.addEventListener('pointerup',endPointer,true);base.addEventListener('pointercancel',e=>{if(press&&e.pointerId===press.id){e.stopImmediatePropagation();press=null}},true);
const reg=document.getElementById('regression');if(reg){const t=E.selfTest();reg.textContent=`internal invariants: ${t.pass?'PASS':'FAIL'} · ${BUILD}`}
window.LW_LIVING_UI={build:BUILD};requestAnimationFrame(draw);
})();