(() => {
'use strict';
const E=window.LW_ENGINE,L=window.LW_LIVING,M=window.LW_MOVEMENT,T=window.LW_TACTICAL_MODELS;
if(!E||!L||!M||!T)return;
const BUILD='P2-0.16.1',WORLD_MIN=.09,WORLD_MAX=.965;
const base=document.getElementById('battlefield'),battleEl=document.getElementById('battle');if(!base||!battleEl)return;
const canvas=document.createElement('canvas');canvas.id='livingBattlefield';canvas.setAttribute('aria-hidden','true');Object.assign(canvas.style,{position:'absolute',inset:'0',width:'100%',height:'100%',zIndex:'1',pointerEvents:'none'});base.insertAdjacentElement('afterend',canvas);
const view={x:0,y:0,zoom:1,worldW:0,worldH:0,pointers:new Map(),pinch:null,tap:null,battleKey:null};
const visualCohorts=new Map();let targetPing=null;
function active(){const b=window.LW_ACTIVE_BATTLE;return b?.living?b:null}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
const random=rng(1601);
const TERRAIN=Array.from({length:150},(_,i)=>({x:random(),y:.06+random()*.88,r:2+random()*7,type:i%9===0?'rock':i%5===0?'shrub':'grass',tone:random()}));
const PATCHES=Array.from({length:34},()=>({x:random(),y:.08+random()*.84,rx:45+random()*105,ry:22+random()*65,tone:random()}));
function worldMetrics(r){view.worldW=Math.max(1700,r.width*2.55);view.worldH=Math.max(1,r.height);const leftW=120,rightW=view.worldW-120;clampView(r);return{worldW:view.worldW,worldH:view.worldH,leftW,rightW,spanW:rightW-leftW}}
function clampView(r){const visibleW=r.width/view.zoom,visibleH=r.height/view.zoom;view.x=clamp(view.x,0,Math.max(0,view.worldW-visibleW));view.y=clamp(view.y,0,Math.max(0,view.worldH-visibleH))}
function worldX(m,pos){return m.leftW+m.spanW*((pos-WORLD_MIN)/(WORLD_MAX-WORLD_MIN))}
function laneWorldY(m,id,pos){const wave=id==='north'?Math.sin(pos*Math.PI*2.15+.35)*14+Math.sin(pos*Math.PI*5.2)*5:Math.sin(pos*Math.PI*1.82+2.2)*17+Math.sin(pos*Math.PI*4.4+.8)*5;return m.worldH*(id==='north'?.34:.67)+wave}
function worldToScreen(x,y){return{x:(x-view.x)*view.zoom,y:(y-view.y)*view.zoom}}
function lanePoint(m,id,pos){return worldToScreen(worldX(m,pos),laneWorldY(m,id,pos))}
function fieldWorldPoint(m,x,y){const n=laneWorldY(m,'north',x),s=laneWorldY(m,'south',x);return{x:worldX(m,x),y:n+(s-n)*clamp(y,0,1)}}
function fieldPoint(m,x,y){const p=fieldWorldPoint(m,x,y);return worldToScreen(p.x,p.y)}
function normAtScreen(m,screenX){const wx=view.x+screenX/view.zoom;return WORLD_MIN+((wx-m.leftW)/m.spanW)*(WORLD_MAX-WORLD_MIN)}
function laneAtScreen(m,screenX,screenY){const pos=clamp(normAtScreen(m,screenX),WORLD_MIN,WORLD_MAX),wy=view.y+screenY/view.zoom;return Math.abs(wy-laneWorldY(m,'north',pos))<=Math.abs(wy-laneWorldY(m,'south',pos))?'north':'south'}
function visiblePoint(p,margin=80){return p.x>-margin&&p.x<base.clientWidth+margin&&p.y>-margin&&p.y<base.clientHeight+margin}
function circle(ctx,x,y,r,fill,stroke=null){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.stroke()}}
function hpBar(ctx,x,y,w,p,fill){ctx.fillStyle='rgba(2,7,10,.76)';ctx.fillRect(x-w/2,y,w,Math.max(3,4*view.zoom));ctx.fillStyle=fill;ctx.fillRect(x-w/2,y,w*clamp(p,0,1),Math.max(3,4*view.zoom))}
function traceLane(ctx,m,id,start=WORLD_MIN,end=WORLD_MAX,steps=92){ctx.beginPath();for(let i=0;i<=steps;i++){const p=lanePoint(m,id,start+(end-start)*(i/steps));if(i)ctx.lineTo(p.x,p.y);else ctx.moveTo(p.x,p.y)}}
function traceCrossing(ctx,m,c,steps=18){ctx.beginPath();for(let i=0;i<=steps;i++){const q=M.crossingPoint(c,i/steps),p=fieldPoint(m,q.x,q.y);if(i)ctx.lineTo(p.x,p.y);else ctx.moveTo(p.x,p.y)}}
function drawTerrain(ctx,m,r){
  const g=ctx.createLinearGradient(0,0,0,r.height);g.addColorStop(0,'#101b1b');g.addColorStop(.48,'#0b1718');g.addColorStop(1,'#121b18');ctx.fillStyle=g;ctx.fillRect(0,0,r.width,r.height);
  for(const p of PATCHES){const s=worldToScreen(p.x*m.worldW,p.y*m.worldH),rx=p.rx*view.zoom,ry=p.ry*view.zoom;if(!visiblePoint(s,Math.max(rx,ry)))continue;ctx.fillStyle=p.tone>.5?'rgba(43,58,43,.15)':'rgba(54,47,34,.13)';ctx.beginPath();ctx.ellipse(s.x,s.y,rx,ry,p.tone*Math.PI,0,Math.PI*2);ctx.fill()}
  const ford=M.crossings.find(c=>c.kind==='ford')||M.crossings[1];ctx.strokeStyle='rgba(39,83,88,.28)';ctx.lineWidth=24*view.zoom;ctx.beginPath();for(let i=0;i<=28;i++){const y=m.worldH*(i/28),x=worldX(m,ford.x)+Math.sin(i*.72)*9,pt=worldToScreen(x,y);if(i)ctx.lineTo(pt.x,pt.y);else ctx.moveTo(pt.x,pt.y)}ctx.stroke();ctx.strokeStyle='rgba(79,132,136,.24)';ctx.lineWidth=4*view.zoom;ctx.stroke();
  for(const o of TERRAIN){const s=worldToScreen(o.x*m.worldW,o.y*m.worldH),z=view.zoom;if(!visiblePoint(s,18*z))continue;if(o.type==='grass'){ctx.strokeStyle=`rgba(91,117,79,${.14+o.tone*.16})`;ctx.lineWidth=Math.max(1,z);ctx.beginPath();ctx.moveTo(s.x,s.y+o.r*z);ctx.lineTo(s.x-2*z,s.y-o.r*z);ctx.moveTo(s.x,s.y+o.r*z);ctx.lineTo(s.x+3*z,s.y-o.r*.7*z);ctx.stroke()}else if(o.type==='shrub'){circle(ctx,s.x,s.y,o.r*z,'rgba(45,79,59,.34)');circle(ctx,s.x-3*z,s.y+2*z,o.r*.55*z,'rgba(68,96,66,.28)')}else{ctx.fillStyle='rgba(99,101,88,.34)';ctx.beginPath();ctx.moveTo(s.x-o.r*z,s.y+o.r*.5*z);ctx.lineTo(s.x-o.r*.2*z,s.y-o.r*z);ctx.lineTo(s.x+o.r*z,s.y+o.r*.6*z);ctx.closePath();ctx.fill()}}
}
function drawCrossings(ctx,m){for(const c of M.crossings){traceCrossing(ctx,m,c);ctx.strokeStyle=c.kind==='ford'?'rgba(111,104,75,.52)':'rgba(91,82,62,.48)';ctx.lineWidth=13*view.zoom;ctx.stroke();traceCrossing(ctx,m,c);ctx.strokeStyle='rgba(177,155,102,.34)';ctx.lineWidth=Math.max(1,2*view.zoom);ctx.setLineDash([5*view.zoom,7*view.zoom]);ctx.stroke();ctx.setLineDash([]);const q=M.crossingPoint(c,.5),p=fieldPoint(m,q.x,q.y);if(visiblePoint(p)&&view.zoom>.72){ctx.fillStyle='rgba(185,176,139,.62)';ctx.font=`800 ${Math.max(6,6.5*view.zoom)}px system-ui`;ctx.textAlign='center';ctx.fillText(c.label,p.x,p.y-9*view.zoom)}}}
function drawCampDetails(ctx,m){const z=view.zoom;for(const lane of ['north','south']){const p=lanePoint(m,lane,.15),dir=lane==='north'?-1:1;ctx.fillStyle='rgba(73,65,45,.72)';ctx.beginPath();ctx.moveTo(p.x-10*z,p.y+dir*26*z);ctx.lineTo(p.x,p.y+dir*10*z);ctx.lineTo(p.x+11*z,p.y+dir*26*z);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(194,158,87,.48)';ctx.lineWidth=Math.max(1,z);ctx.beginPath();ctx.moveTo(p.x,p.y+dir*9*z);ctx.lineTo(p.x,p.y+dir*31*z);ctx.stroke();for(const c of M.crossings){const e=M.crossingPoint(c,lane==='north'?0:1),q=fieldPoint(m,e.x,e.y);circle(ctx,q.x,q.y,4.5*z,'rgba(116,103,73,.68)','rgba(197,171,109,.38)')}}}
function modelState(c){if(c.hp<=0)return'fallen';if(c.state==='engaged'||c.state==='supporting')return'engaged';if(c.state==='marching')return'march';return'idle'}
function friendlyRoster(c){const out=[];for(const [id,n0] of Object.entries(c.composition||{})){const n=Math.max(0,Number(n0)||0),visual=T.map(id);if(id==='ram'){if(n)out.push({visual,ram:true});continue}const copies=Math.max(1,Math.min(id==='slingline'||id==='zealot'?3:4,n*2));for(let i=0;i<copies;i++)out.push({visual,ranged:id==='slingline'||id==='zealot'})}return out.length?out.slice(0,6):[{visual:T.map('ironjack')},{visual:T.map('ironjack')},{visual:T.map('ironjack')}]}
function enemyRoster(c){const visual=T.map(`enemy-${c.kind||'line'}`),n=c.kind==='brute'?2:c.kind==='raider'?4:5;return Array.from({length:n},()=>({visual,brute:c.kind==='brute'}))}
function formation(roster){const ranged=roster.every(r=>r.ranged),slots=ranged?[[-11,1],[0,5],[11,1],[-5,-4],[7,-4]]:[[-10,4],[0,7],[10,4],[-5,-4],[6,-4],[0,-10]];return roster.map((r,i)=>({...r,dx:slots[i%slots.length][0],dy:slots[i%slots.length][1]}))}
function smoothedX(c,stamp){let p=visualCohorts.get(c.id);if(!p){p={x:c.x+(c.side==='friendly'?-.016:.016),at:stamp};visualCohorts.set(c.id,p)}const dt=clamp((stamp-p.at)/1000,0,.08),follow=c.state==='engaged'?'6.2':c.kind==='raider'?'4.8':c.kind==='brute'?'2.7':'3.5';p.x+= (c.x-p.x)*(1-Math.exp(-follow*dt));p.at=stamp;return p.x}
function laneAngle(m,lane,pos){const a=lanePoint(m,lane,clamp(pos-.003,WORLD_MIN,WORLD_MAX)),b=lanePoint(m,lane,clamp(pos+.003,WORLD_MIN,WORLD_MAX));return Math.atan2(b.y-a.y,b.x-a.x)}
function drawRam(ctx,x,y,state,flip,alpha,elapsed,size){const scale=size/46;ctx.save();ctx.globalAlpha*=alpha;ctx.translate(x,y);if(flip)ctx.scale(-1,1);const bob=state==='march'?Math.sin(elapsed*4.2)*.8*scale:0;ctx.translate(0,bob);ctx.scale(scale,scale);ctx.fillStyle='#172229';ctx.beginPath();ctx.ellipse(0,6,18,5,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#907346';ctx.fillRect(-16,-1,28,8);ctx.fillStyle='#c49a58';ctx.beginPath();ctx.moveTo(8,-5);ctx.lineTo(22,3);ctx.lineTo(8,7);ctx.closePath();ctx.fill();circle(ctx,-10,8,4,'#2c3438','#a98a53');circle(ctx,9,8,4,'#2c3438','#a98a53');ctx.fillStyle='#72bdae';ctx.fillRect(-12,-10,5,9);ctx.fillRect(1,-9,5,8);ctx.restore()}
function drawFigure(ctx,r,x,y,state,flip,alpha,elapsed,seed){const size=(r.brute?45:r.ram?46:r.ranged?30:32)*view.zoom,bob=state==='march'?Math.sin(elapsed*4.6+seed)*.65*view.zoom:state==='engaged'?Math.sin(elapsed*7+seed)*.55*view.zoom:0,lunge=state==='engaged'?Math.max(0,Math.sin(elapsed*6.5+seed))*1.4*view.zoom:0;if(r.ram){drawRam(ctx,x+(flip?-lunge:lunge),y+bob,state,flip,alpha,elapsed,size);return}if(!T.draw(ctx,r.visual,state,x+(flip?-lunge:lunge),y+bob,size,flip,alpha)){ctx.save();ctx.globalAlpha*=alpha;circle(ctx,x,y,6*view.zoom,r.visual.includes('enemy')?'#bd5b52':'#75c5b5');ctx.restore()}}
function cohortAnchor(m,c,stamp){const x=smoothedX(c,stamp),p=lanePoint(m,c.lane,x);return{...p,pos:x,angle:laneAngle(m,c.lane,x)}}
function drawCohort(ctx,m,c,elapsed,stamp){const a=cohortAnchor(m,c,stamp),friendly=c.side==='friendly',alive=c.hp>0,state=modelState(c),hp=clamp(c.hp/c.maxHp,0,1),full=formation(friendly?friendlyRoster(c):enemyRoster(c)),visible=alive?Math.max(1,Math.ceil(full.length*hp)):Math.min(3,full.length),members=full.slice(0,visible),alpha=!alive&&c.deadAt!=null?Math.max(0,1-(elapsed-c.deadAt)/1.4):1,z=view.zoom,flip=!friendly,co=Math.cos(a.angle),si=Math.sin(a.angle);
  ctx.save();ctx.globalAlpha=alpha;circle(ctx,a.x,a.y+9*z,13*z,friendly?'rgba(59,125,117,.30)':'rgba(135,54,50,.28)',friendly?'rgba(115,213,196,.42)':'rgba(226,110,92,.42)');if(c.state==='engaged'||c.state==='supporting'){ctx.strokeStyle=friendly?'rgba(121,222,202,.72)':'rgba(232,112,96,.68)';ctx.lineWidth=1.5*z;ctx.beginPath();ctx.arc(a.x,a.y+3*z,(17+Math.sin(elapsed*6)*1.3)*z,0,Math.PI*2);ctx.stroke()}if(c.slow>0){ctx.strokeStyle='rgba(111,203,236,.82)';ctx.lineWidth=1.3*z;ctx.beginPath();ctx.arc(a.x,a.y+4*z,20*z,Math.PI*.15,Math.PI*1.65);ctx.stroke()}if(state==='march'){ctx.fillStyle=friendly?'rgba(150,179,151,.16)':'rgba(172,128,101,.14)';circle(ctx,a.x+(friendly?-15:15)*z,a.y+10*z,3.2*z,ctx.fillStyle)}ctx.restore();
  members.slice().sort((x,y)=>x.dy-y.dy).forEach((r,i)=>{const dx=r.dx*z,dy=r.dy*z,px=a.x+dx*co-dy*si,py=a.y+dx*si+dy*co;drawFigure(ctx,r,px,py,state,flip,alpha,elapsed,i+c.id.length)});
  if(c.state==='supporting'){ctx.strokeStyle=friendly?'rgba(121,222,202,.5)':'rgba(232,112,96,.45)';ctx.lineWidth=Math.max(1,z);ctx.setLineDash([3*z,4*z]);ctx.beginPath();ctx.moveTo(a.x+(friendly?12:-12)*z,a.y-5*z);ctx.lineTo(a.x+(friendly?35:-35)*z,a.y-10*z);ctx.stroke();ctx.setLineDash([])}
  hpBar(ctx,a.x,a.y-25*z,30*z,hp,friendly?'#74c5b5':'#ce6b63');const age=elapsed-(c.spawnedAt||0);if(alive&&age<1.25){ctx.strokeStyle=friendly?'rgba(124,226,207,.9)':'rgba(232,120,102,.85)';ctx.lineWidth=2*z;ctx.beginPath();ctx.arc(a.x,a.y+2*z,(10+age*12)*z,0,Math.PI*2);ctx.stroke()}if(c.reinforced&&alive){ctx.fillStyle='#e5cb67';ctx.font=`bold ${Math.max(7,7*z)}px system-ui`;ctx.textAlign='center';ctx.fillText('◆ REINFORCED',a.x,a.y+26*z)}
}
function drawEngagements(ctx,m,ll,elapsed,stamp){if(view.zoom<.9)return;const enemy=new Map(ll.enemy.map(c=>[c.id,c]));for(const f of ll.friendly){if(f.state!=='engaged'||!f.target)continue;const e=enemy.get(f.target);if(!e||e.hp<=0)continue;const a=cohortAnchor(m,f,stamp),b=cohortAnchor(m,e,stamp),x=(a.x+b.x)/2,y=(a.y+b.y)/2,z=view.zoom,pulse=.5+.5*Math.sin(elapsed*10+f.id.length);ctx.strokeStyle=`rgba(241,190,99,${.34+pulse*.42})`;ctx.lineWidth=1.5*z;ctx.beginPath();ctx.moveTo(x-5*z,y-8*z);ctx.lineTo(x+4*z,y+5*z);ctx.moveTo(x+5*z,y-6*z);ctx.lineTo(x-3*z,y+6*z);ctx.stroke();circle(ctx,x,y,2.2*z,`rgba(243,209,125,${.35+pulse*.35})`)}}
function drawObjective(ctx,m,b,lane){const l=b.lanes[lane],bp=lanePoint(m,lane,.09),gp=lanePoint(m,lane,.91),gate=lanePoint(m,lane,.965),z=view.zoom;circle(ctx,bp.x,bp.y+17*z,20*z,'rgba(37,73,69,.48)');T.draw(ctx,T.map('bastion'),'idle',bp.x,bp.y+z,65*z,false,l.bastion>0?1:.28);if(l.guard>0)T.draw(ctx,T.map('guard'),'idle',gp.x,gp.y+2*z,58*z,true,1);else{ctx.strokeStyle='#c36b65';ctx.lineWidth=3*z;ctx.beginPath();ctx.moveTo(gp.x-15*z,gp.y+8*z);ctx.lineTo(gp.x-5*z,gp.y);ctx.lineTo(gp.x+3*z,gp.y+10*z);ctx.lineTo(gp.x+15*z,gp.y+2*z);ctx.stroke();ctx.fillStyle='#d88370';ctx.font=`bold ${Math.max(8,8*z)}px system-ui`;ctx.textAlign='center';ctx.fillText('BREACH',gp.x,gp.y-24*z)}T.draw(ctx,T.map('gate'),'idle',gate.x,gate.y,72*z,true,b.gateVulnerable?1:.62);if(b.gateVulnerable){ctx.strokeStyle=`rgba(231,182,77,${.45+.25*Math.sin(b.elapsed*5)})`;ctx.lineWidth=2*z;ctx.beginPath();ctx.arc(gate.x,gate.y,(25+Math.sin(b.elapsed*4)*3)*z,0,Math.PI*2);ctx.stroke()}hpBar(ctx,bp.x,bp.y+30*z,38*z,l.bastion/100,'#68ad9f');hpBar(ctx,gp.x,gp.y+28*z,38*z,l.guard/100,'#c36b65')}
function towerAttachment(ctx,t,x,y){const z=view.zoom;ctx.save();ctx.translate(x,y);ctx.scale(z,z);ctx.strokeStyle='#d9edf0';ctx.fillStyle='#8fcbd2';ctx.lineWidth=2;if(t.effect==='slow'||t.id==='frost'||t.id==='harpoon'){ctx.rotate(Math.PI/4);ctx.strokeRect(-5,-5,10,10);ctx.beginPath();ctx.moveTo(-8,0);ctx.lineTo(8,0);ctx.moveTo(0,-8);ctx.lineTo(0,8);ctx.stroke()}else if(t.effect==='swarm'||t.id==='scatter'||t.id==='pulsebell'){for(let i=-1;i<=1;i++){ctx.beginPath();ctx.moveTo(i*4,-7);ctx.lineTo(i*5,4);ctx.stroke()}}else if(t.effect==='amplify'||t.id==='pylon'||t.id==='beacon'){ctx.beginPath();ctx.moveTo(0,6);ctx.lineTo(0,-11);ctx.lineTo(8,-6);ctx.lineTo(0,-2);ctx.stroke()}else{ctx.fillRect(-3,-10,6,15);ctx.beginPath();ctx.moveTo(0,-10);ctx.lineTo(10,-14);ctx.stroke()}ctx.restore()}
function drawTower(ctx,m,b,lane){const l=b.lanes[lane],t=l.tower;if(!t?.id)return;const pos=t.slot==='forward'?.38:.22,p=lanePoint(m,lane,pos),dir=lane==='north'?-1:1,z=view.zoom,y=p.y+dir*48*z,alive=t.hp>0;ctx.strokeStyle='rgba(93,137,146,.17)';ctx.lineWidth=Math.max(1,z);ctx.beginPath();ctx.arc(p.x,y,Math.max(20*z,m.spanW*view.zoom*(L.cfg.towerRange/(WORLD_MAX-WORLD_MIN))),0,Math.PI*2);ctx.stroke();T.draw(ctx,T.map('tower'),'idle',p.x,y,48*z,false,alive?1:.3);if(alive)towerAttachment(ctx,t,p.x,y-15*z);ctx.fillStyle='#9ab0b4';ctx.font=`bold ${Math.max(6,6*z)}px system-ui`;ctx.textAlign='center';ctx.fillText((t.name?.split(' ')[0]||'TOWER').toUpperCase(),p.x,y+dir*30*z)}
function drawCommander(ctx,m,b){const c=b.commander;if(!c||c.incapacitated)return;const d=M.display(c),p=fieldPoint(m,d.pos,d.y),radius=clamp(m.spanW*view.zoom*(L.cfg.presenceRadius/(WORLD_MAX-WORLD_MIN)),44*view.zoom,260*view.zoom),state=d.moving?'march':'idle',z=view.zoom;ctx.strokeStyle='rgba(226,180,83,.32)';ctx.lineWidth=2*z;ctx.beginPath();ctx.arc(p.x,p.y,radius,0,Math.PI*2);ctx.stroke();ctx.fillStyle='rgba(226,180,83,.065)';ctx.fill();circle(ctx,p.x,p.y+10*z,13*z,'rgba(226,180,83,.25)','rgba(242,204,106,.8)');T.draw(ctx,T.map('warden'),state,p.x,p.y,43*z,false,1);ctx.fillStyle='#f0d479';ctx.font=`bold ${Math.max(7,7*z)}px system-ui`;ctx.textAlign='center';ctx.fillText(d.moving?`WARDEN · ${d.crossing?'CUTTING THROUGH':'MOVING'}`:'THE WARDEN',p.x,p.y+28*z)}
function drawLane(ctx,m,b,id,stamp){const z=view.zoom;traceLane(ctx,m,id);ctx.strokeStyle='rgba(7,13,15,.72)';ctx.lineWidth=62*z;ctx.stroke();traceLane(ctx,m,id);ctx.strokeStyle='#182b2d';ctx.lineWidth=50*z;ctx.stroke();traceLane(ctx,m,id);ctx.strokeStyle='#2e4543';ctx.lineWidth=35*z;ctx.stroke();traceLane(ctx,m,id);ctx.strokeStyle='rgba(108,131,111,.5)';ctx.lineWidth=2*z;ctx.setLineDash([10*z,13*z]);ctx.stroke();ctx.setLineDash([]);const label=lanePoint(m,id,.105);ctx.fillStyle='#9bad9e';ctx.font=`bold ${Math.max(8,8*z)}px system-ui`;ctx.textAlign='left';ctx.fillText(id.toUpperCase(),label.x,label.y-29*z);drawObjective(ctx,m,b,id);drawTower(ctx,m,b,id);const ll=b.living.lanes[id];drawEngagements(ctx,m,ll,b.elapsed,stamp);for(const c of [...ll.friendly,...ll.enemy].sort((a,q)=>a.x-q.x))drawCohort(ctx,m,c,b.elapsed,stamp)}
function centerField(m,pos,y,r){const p=fieldWorldPoint(m,pos,y);view.x=p.x-r.width/(2*view.zoom);view.y=p.y-r.height/(2*view.zoom);clampView(r)}
function centerCommander(){const b=active();if(!b)return;const r=base.getBoundingClientRect(),m=worldMetrics(r),d=M.display(b.commander);centerField(m,d.pos,d.y,r)}
function focusLane(lane){const b=active();if(!b)return;const r=base.getBoundingClientRect(),m=worldMetrics(r),pos=L.frontlinePos?.(b,lane)??b.lanes?.[lane]?.front??.5;centerField(m,pos,lane==='south'?1:0,r)}
function draw(stamp=performance.now()){const b=active(),r=base.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.floor(r.width*dpr)),h=Math.max(1,Math.floor(r.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,r.width,r.height);if(b&&!battleEl.hidden){const m=worldMetrics(r);if(view.battleKey!==b){view.battleKey=b;view.zoom=1;const d=M.display(b.commander);centerField(m,d.pos,d.y,r)}drawTerrain(ctx,m,r);drawCrossings(ctx,m);drawCampDetails(ctx,m);drawLane(ctx,m,b,'north',stamp);drawLane(ctx,m,b,'south',stamp);drawCommander(ctx,m,b);if(targetPing&&stamp-targetPing.at<850){const p=lanePoint(m,targetPing.lane,targetPing.pos);ctx.strokeStyle='rgba(226,180,83,.75)';ctx.lineWidth=2*view.zoom;ctx.beginPath();ctx.arc(p.x,p.y,(10+(stamp-targetPing.at)/55)*view.zoom,0,Math.PI*2);ctx.stroke()}ctx.fillStyle='rgba(172,183,164,.72)';ctx.font='bold 7px system-ui';ctx.textAlign='center';ctx.fillText('TAP TO MOVE · DRAG THE FIELD · PINCH TO INSPECT',r.width/2,r.height-68)}requestAnimationFrame(draw)}
function pointerPos(e){const r=base.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top,r}}
function startPinch(){if(view.pointers.size<2){view.pinch=null;return}const ps=[...view.pointers.values()].slice(0,2),mx=(ps[0].x+ps[1].x)/2,my=(ps[0].y+ps[1].y)/2;view.pinch={distance:Math.max(1,Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y)),zoom:view.zoom,anchorWorldX:view.x+mx/view.zoom,anchorWorldY:view.y+my/view.zoom};view.tap=null}
base.addEventListener('pointerdown',e=>{if(!active())return;e.stopImmediatePropagation();const p=pointerPos(e);base.setPointerCapture?.(e.pointerId);view.pointers.set(e.pointerId,{x:p.x,y:p.y,startX:p.x,startY:p.y,lastX:p.x,lastY:p.y,moved:false});if(view.pointers.size===1)view.tap={id:e.pointerId,moved:false};else startPinch()},true);
base.addEventListener('pointermove',e=>{const pt=view.pointers.get(e.pointerId);if(!pt)return;e.stopImmediatePropagation();const p=pointerPos(e),dx=p.x-pt.lastX,dy=p.y-pt.lastY;pt.x=p.x;pt.y=p.y;pt.lastX=p.x;pt.lastY=p.y;if(Math.hypot(p.x-pt.startX,p.y-pt.startY)>8){pt.moved=true;if(view.tap?.id===e.pointerId)view.tap.moved=true}if(view.pointers.size===1){if(pt.moved){view.x-=dx/view.zoom;view.y-=dy/view.zoom;clampView(p.r)}}else{if(!view.pinch)startPinch();const ps=[...view.pointers.values()].slice(0,2),dist=Math.max(1,Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y)),mx=(ps[0].x+ps[1].x)/2,my=(ps[0].y+ps[1].y)/2,newZoom=clamp(view.pinch.zoom*(dist/view.pinch.distance),.68,2.25);view.zoom=newZoom;view.x=view.pinch.anchorWorldX-mx/newZoom;view.y=view.pinch.anchorWorldY-my/newZoom;clampView(p.r)}},true);
function endPointer(e,cancel=false){const pt=view.pointers.get(e.pointerId);if(!pt)return;e.stopImmediatePropagation();const p=pointerPos(e),only=view.pointers.size===1,tap=view.tap?.id===e.pointerId&&!view.tap.moved&&!pt.moved&&!cancel;view.pointers.delete(e.pointerId);if(view.pointers.size<2)view.pinch=null;if(view.pointers.size===1){const q=[...view.pointers.values()][0];q.startX=q.x;q.startY=q.y;q.lastX=q.x;q.lastY=q.y;q.moved=true}view.tap=null;if(!tap||!only)return;const b=active();if(!b)return;const m=worldMetrics(p.r),lane=laneAtScreen(m,p.x,p.y),pos=clamp(normAtScreen(m,p.x),.12,.86);if(E.setCommanderPosition?.(b,lane,pos))targetPing={lane,pos,at:performance.now()}}
base.addEventListener('pointerup',e=>endPointer(e,false),true);base.addEventListener('pointercancel',e=>endPointer(e,true),true);
document.getElementById('recenter')?.addEventListener('click',()=>setTimeout(centerCommander,0));document.querySelectorAll('#laneStrip [data-lane]').forEach(btn=>btn.addEventListener('click',()=>setTimeout(()=>focusLane(btn.dataset.lane),0)));
const reg=document.getElementById('regression');if(reg){const t=E.selfTest();reg.textContent=`internal invariants: ${t.pass?'PASS':'FAIL'} · ${BUILD}`}
window.LW_LIVING_UI={build:BUILD,view,recenter:centerCommander,focusLane};requestAnimationFrame(draw);
})();
