(() => {
'use strict';
const E=window.LW_ENGINE,L=window.LW_LIVING;
if(!E||!L)return;
const BUILD='P2-0.15.2';
const base=document.getElementById('battlefield'),battleEl=document.getElementById('battle');if(!base||!battleEl)return;
const canvas=document.createElement('canvas');canvas.id='livingBattlefield';canvas.setAttribute('aria-hidden','true');Object.assign(canvas.style,{position:'absolute',inset:'0',width:'100%',height:'100%',zIndex:'1',pointerEvents:'none'});base.insertAdjacentElement('afterend',canvas);
const view={x:0,zoom:1,worldW:0,pointers:new Map(),pinch:null,tap:null,battleKey:null};
let targetPing=null;
function active(){const b=window.LW_ACTIVE_BATTLE;return b?.living?b:null}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function worldMetrics(r){view.worldW=Math.max(1700,r.width*2.55);const leftW=120,rightW=view.worldW-120;clampView(r);return{leftW,rightW,spanW:rightW-leftW,northY:r.height*.34,southY:r.height*.67}}
function clampView(r){const visible=r.width/view.zoom;view.x=clamp(view.x,0,Math.max(0,view.worldW-visible))}
function sx(wx){return(wx-view.x)*view.zoom}
function worldX(m,pos){return m.leftW+m.spanW*((pos-.09)/(.91-.09))}
function px(m,pos){return sx(worldX(m,pos))}
function normAtScreen(m,screenX){const wx=view.x+screenX/view.zoom;return .09+((wx-m.leftW)/m.spanW)*(.91-.09)}
function laneY(m,id){return id==='north'?m.northY:m.southY}
function hpBar(ctx,x,y,w,p,fill){ctx.fillStyle='rgba(2,7,10,.75)';ctx.fillRect(x-w/2,y,w,4);ctx.fillStyle=fill;ctx.fillRect(x-w/2,y,w*Math.max(0,Math.min(1,p)),4)}
function drawCohort(ctx,m,c,now){const x=px(m,c.x),y=laneY(m,c.lane),friendly=c.side==='friendly',isAlive=c.hp>0;let alpha=1;if(!isAlive&&c.deadAt!=null)alpha=Math.max(0,1-(now-c.deadAt)/1.4);ctx.save();ctx.globalAlpha=alpha;const pipCount=Math.max(3,Math.min(9,c.count||6));const spread=3.8;const stagger=c.id.charCodeAt(c.id.length-1)%3;for(let i=0;i<pipCount;i++){const row=i%2,col=Math.floor(i/2),dx=(col-(pipCount/4))*spread,dy=(row?5:-3)+(stagger-1);ctx.beginPath();ctx.arc(x+dx,y+dy,isAlive?3.3:2.7,0,Math.PI*2);ctx.fillStyle=friendly?(c.reinforced?'#d6c16b':'#79cabb'):(c.kind==='raider'?'#d98c66':c.kind==='brute'?'#b75252':'#c96762');ctx.fill()}
 if(c.state==='engaged'||c.state==='supporting'){ctx.strokeStyle=friendly?'rgba(121,202,187,.7)':'rgba(210,100,90,.7)';ctx.lineWidth=1.4;ctx.beginPath();ctx.arc(x,y,13,0,Math.PI*2);ctx.stroke()}
 hpBar(ctx,x,y-14,24,c.hp/c.maxHp,friendly?'#74c5b5':'#ce6b63');if(c.reinforced&&isAlive){ctx.fillStyle='#e0c76c';ctx.font='bold 7px system-ui';ctx.textAlign='center';ctx.fillText('REINF',x,y+18)}ctx.restore()}
function drawObjective(ctx,m,b,lane){const l=b.lanes[lane],y=laneY(m,lane),bx=px(m,.09),gx=px(m,.91),gate=px(m,.965);ctx.fillStyle=l.bastion>0?'#446e69':'#342a2b';ctx.fillRect(bx-12,y-26,24,52);ctx.fillStyle=l.guard>0?'#8e5552':'#3c2b2c';ctx.fillRect(gx-10,y-24,20,48);ctx.fillStyle=b.gateVulnerable?'#d6a64f':'#6c593a';ctx.fillRect(gate-6,y-31,12,62);hpBar(ctx,bx,y+31,34,l.bastion/100,'#68ad9f');hpBar(ctx,gx,y+29,34,l.guard/100,'#c36b65');ctx.fillStyle='#8ca0a3';ctx.font='bold 7px system-ui';ctx.textAlign='center';ctx.fillText('BASTION',bx,y-33);ctx.fillText(l.guard>0?'GUARD':'BREACHED',gx,y-31)}
function drawTower(ctx,m,b,lane){const l=b.lanes[lane],t=l.tower;if(!t?.id)return;const tx=px(m,t.slot==='forward'?.38:.22),y=laneY(m,lane)+(lane==='north'?-42:42);ctx.fillStyle=t.hp>0?'#5d8992':'#342f31';ctx.fillRect(tx-8,y-8,16,16);ctx.strokeStyle='rgba(93,137,146,.18)';ctx.beginPath();ctx.arc(tx,y,Math.max(20,m.spanW*view.zoom*(L.cfg.towerRange/.82)),0,Math.PI*2);ctx.stroke();ctx.fillStyle='#80989d';ctx.font='6px system-ui';ctx.textAlign='center';ctx.fillText(t.name?.split(' ')[0]||'TOWER',tx,y+(lane==='north'?-12:18))}
function commanderDisplay(c){let lane=c.lane||c.travel?.from||'north',pos=c.pos??.3,phase=null;if(c.travel){const p=1-c.travel.remaining/c.travel.total;phase=p;lane=p<.5?c.travel.from:c.travel.to;const junction=.38;if(p<.45){const q=p/.45;pos=(c.travel.fromPos??c.pos??.3)+(junction-(c.travel.fromPos??c.pos??.3))*q}else if(p<.55)pos=junction;else{const q=(p-.55)/.45;pos=junction+((c.travel.targetPos??.3)-junction)*q}}return{lane,pos,phase}}
function drawCommander(ctx,m,b){const c=b.commander;if(!c||c.incapacitated)return;const d=commanderDisplay(c),y0=laneY(m,d.lane);let y=y0;if(c.travel&&d.phase>=.45&&d.phase<.55){const q=(d.phase-.45)/.10;y=laneY(m,c.travel.from)+(laneY(m,c.travel.to)-laneY(m,c.travel.from))*q}const x=px(m,d.pos);ctx.strokeStyle='rgba(226,180,83,.25)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,m.spanW*view.zoom*(L.cfg.presenceRadius/.82),0,Math.PI*2);ctx.stroke();ctx.fillStyle='#e3b451';ctx.font='bold 25px system-ui';ctx.textAlign='center';ctx.fillText('◆',x,y-12);ctx.fillStyle='#e3c681';ctx.font='bold 7px system-ui';ctx.fillText(c.move||c.travel?'MOVING':'WARDEN',x,y+20)}
function drawLane(ctx,m,b,id){const y=laneY(m,id),left=sx(m.leftW),right=sx(m.rightW);ctx.strokeStyle='#1d3138';ctx.lineWidth=30;ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke();ctx.strokeStyle='#46625f';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke();ctx.fillStyle='#789095';ctx.font='bold 8px system-ui';ctx.textAlign='left';ctx.fillText(id.toUpperCase(),left,y-22);drawObjective(ctx,m,b,id);drawTower(ctx,m,b,id);const ll=b.living.lanes[id];for(const c of [...ll.friendly,...ll.enemy])drawCohort(ctx,m,c,b.elapsed)}
function centerNorm(pos){const r=base.getBoundingClientRect(),m=worldMetrics(r),wx=worldX(m,pos);view.x=wx-r.width/(2*view.zoom);clampView(r)}
function centerCommander(){const b=active();if(!b)return;const d=commanderDisplay(b.commander);centerNorm(d.pos)}
function focusLane(lane){const b=active();if(!b)return;centerNorm(L.frontlinePos?.(b,lane)??b.lanes?.[lane]?.front??.5)}
function draw(){const b=active(),r=base.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.floor(r.width*dpr)),h=Math.max(1,Math.floor(r.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,r.width,r.height);if(b&&!battleEl.hidden){if(view.battleKey!==b){view.battleKey=b;view.zoom=1;const m0=worldMetrics(r),d=commanderDisplay(b.commander);view.x=worldX(m0,d.pos)-r.width/2;clampView(r)}ctx.fillStyle='#091116';ctx.fillRect(0,0,r.width,r.height);const m=worldMetrics(r);drawLane(ctx,m,b,'north');drawLane(ctx,m,b,'south');ctx.strokeStyle='#314b54';ctx.lineWidth=14;const jx=px(m,.38);ctx.beginPath();ctx.moveTo(jx,m.northY);ctx.lineTo(jx,m.southY);ctx.stroke();ctx.fillStyle='#314b54';ctx.fillRect(jx-10,(m.northY+m.southY)/2-10,20,20);drawCommander(ctx,m,b);if(targetPing&&performance.now()-targetPing.at<850){ctx.strokeStyle='rgba(226,180,83,.75)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(px(m,targetPing.pos),laneY(m,targetPing.lane),10+(performance.now()-targetPing.at)/55,0,Math.PI*2);ctx.stroke()}ctx.fillStyle='rgba(145,165,168,.72)';ctx.font='bold 7px system-ui';ctx.textAlign='center';ctx.fillText('TAP TO MOVE · DRAG TO PAN · PINCH TO ZOOM',r.width/2,r.height-68)}requestAnimationFrame(draw)}

const baseSetPosition=E.setCommanderPosition?.bind(E),baseSetLane=E.setCommanderLane.bind(E),baseStep=E.stepBattle.bind(E);
function retargetTravel(b,lane,pos){const c=b.commander,t=c.travel;if(!t)return false;pos=clamp(pos,.12,.86);if(lane===t.to){t.targetPos=pos;t.postTargetPos=null;b.events.push({t:b.elapsed,type:'commander-travel-retarget',lane,pos,direction:'continue'});return true}if(lane===t.from){const p=clamp(1-t.remaining/t.total,0,1),oldFrom=t.from,oldTo=t.to,oldFromPos=t.fromPos??c.pos??.30,oldTarget=t.targetPos??.30,total=t.total;c.travel={from:oldTo,to:oldFrom,total,remaining:Math.max(.05,total*p),fromPos:oldTarget,targetPos:oldFromPos,postTargetPos:pos,retargeted:true};c.move=null;b.events.push({t:b.elapsed,type:'commander-travel-retarget',lane,pos,direction:'reverse'});return true}return false}
E.setCommanderPosition=(b,lane,pos)=>{if(!b?.commander)return false;if(b.commander.travel)return retargetTravel(b,lane,pos);return baseSetPosition?baseSetPosition(b,lane,pos):false};
E.setCommanderLane=(b,lane)=>{const c=b?.commander;if(!c)return false;if(c.travel)return retargetTravel(b,lane,L.frontlinePos?.(b,lane)??.30);return baseSetLane(b,lane)};
E.stepBattle=(b,dt)=>{const travelBefore=b?.commander?.travel?{...b.commander.travel}:null,out=baseStep(b,dt);if(travelBefore&&!b.commander.travel&&travelBefore.postTargetPos!=null&&!b.commander.incapacitated){const pos=clamp(travelBefore.postTargetPos,.12,.86);if(Math.abs((b.commander.pos??.30)-pos)>.01)baseSetPosition?.(b,b.commander.lane,pos)}return out};

function pointerPos(e){const r=base.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top,r}}
function startPinch(r){if(view.pointers.size<2){view.pinch=null;return}const ps=[...view.pointers.values()].slice(0,2),mx=(ps[0].x+ps[1].x)/2,my=(ps[0].y+ps[1].y)/2;view.pinch={distance:Math.max(1,Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y)),zoom:view.zoom,anchorWorld:view.x+mx/view.zoom,midX:mx,midY:my};view.tap=null}
base.addEventListener('pointerdown',e=>{const b=active();if(!b)return;e.stopImmediatePropagation();const p=pointerPos(e);base.setPointerCapture?.(e.pointerId);view.pointers.set(e.pointerId,{x:p.x,y:p.y,startX:p.x,startY:p.y,lastX:p.x,lastY:p.y,moved:false});if(view.pointers.size===1)view.tap={id:e.pointerId,startX:p.x,startY:p.y,moved:false};else startPinch(p.r)},true);
base.addEventListener('pointermove',e=>{const pt=view.pointers.get(e.pointerId);if(!pt)return;e.stopImmediatePropagation();const p=pointerPos(e),dx=p.x-pt.lastX;pt.x=p.x;pt.y=p.y;pt.lastX=p.x;pt.lastY=p.y;if(Math.hypot(p.x-pt.startX,p.y-pt.startY)>8){pt.moved=true;if(view.tap?.id===e.pointerId)view.tap.moved=true}if(view.pointers.size===1){if(pt.moved){view.x-=dx/view.zoom;clampView(p.r)}}else if(view.pointers.size>=2){if(!view.pinch)startPinch(p.r);const ps=[...view.pointers.values()].slice(0,2),dist=Math.max(1,Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y)),mx=(ps[0].x+ps[1].x)/2,newZoom=clamp(view.pinch.zoom*(dist/view.pinch.distance),.72,1.45);view.zoom=newZoom;view.x=view.pinch.anchorWorld-mx/newZoom;clampView(p.r)}},true);
function endPointer(e,cancel=false){const pt=view.pointers.get(e.pointerId);if(!pt)return;e.stopImmediatePropagation();const p=pointerPos(e),wasOnly=view.pointers.size===1,tap=view.tap&&view.tap.id===e.pointerId&&!view.tap.moved&&!pt.moved&&!cancel;view.pointers.delete(e.pointerId);if(view.pointers.size<2)view.pinch=null;if(view.pointers.size===1){const only=[...view.pointers.values()][0];only.startX=only.x;only.startY=only.y;only.lastX=only.x;only.lastY=only.y;only.moved=true}view.tap=null;if(!tap||!wasOnly)return;const b=active();if(!b)return;const m=worldMetrics(p.r),lane=Math.abs(p.y-m.northY)<=Math.abs(p.y-m.southY)?'north':'south',pos=clamp(normAtScreen(m,p.x),.12,.86);if(E.setCommanderPosition?.(b,lane,pos))targetPing={lane,pos,at:performance.now()}}
base.addEventListener('pointerup',e=>endPointer(e,false),true);base.addEventListener('pointercancel',e=>endPointer(e,true),true);
document.getElementById('recenter')?.addEventListener('click',()=>setTimeout(centerCommander,0));document.querySelectorAll('#laneStrip [data-lane]').forEach(btn=>btn.addEventListener('click',()=>setTimeout(()=>focusLane(btn.dataset.lane),0)));
const reg=document.getElementById('regression');if(reg){const t=E.selfTest();reg.textContent=`internal invariants: ${t.pass?'PASS':'FAIL'} · ${BUILD}`}
window.LW_LIVING_UI={build:BUILD,view,recenter:centerCommander,focusLane};requestAnimationFrame(draw);
})();