(() => {
'use strict';
const W=window.LW_REWARDS;if(!W)return;
const $=id=>document.getElementById(id),screens=['home','map','deployment','battle','resolution','lastStand','reward'];
let filtering=false,filterQueued=false;
function run(){return W.readSaved()}
function hideAll(){for(const id of screens){const el=$(id);if(el)el.hidden=true}cancelAnimationFrame(window.__lwRewardRAF||0)}
function quality(q){return String(q||'common').toUpperCase()}
function esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function renderReward(){const r=run(),p=r?.reward?.pendingPacket;if(!r||!p)return false;hideAll();$('reward').hidden=false;$('rewardGrant').textContent=`+${p.grantSalvage} SALVAGE GRANTED`;$('rewardSalvage').textContent=`${r.salvage} SALVAGE`;$('rewardEmbers').textContent=`${'◆'.repeat(r.embers)}${'◇'.repeat(Math.max(0,3-r.embers))}`;$('rewardThesis').textContent=r.thesis?`THESIS · ${r.thesis.toUpperCase()}`:'THESIS · OPEN';$('rewardReceipt').innerHTML=(p.receipt||[]).map(x=>`<span>${esc(x)}</span>`).join('');
 const host=$('rewardComponents');host.innerHTML='';for(const c of p.components){const card=document.createElement('article');card.className=`reward-component ${c.status!=='open'?'resolved':''}`;const avail=W.availability(r,p,c);let body='';if(c.status==='claimed'){body=`<div class="reward-resolved"><b>CLAIMED · ${esc(c.claimed?.name)}</b><span>${esc(c.claimed?.description||'Added to the run.')}</span></div>`}else if(c.status==='skipped'){body=`<div class="reward-resolved"><b>SKIPPED · +${c.skipSalvage} SALVAGE</b><span>The component was converted instead of diluting the build.</span></div>`}else{body=`<div class="reward-offers">${c.offers.map(o=>`<button class="reward-offer" data-claim="${esc(c.id)}" data-offer="${esc(o.id)}"><span class="quality ${esc(o.quality)}">${quality(o.quality)}</span><b>${esc(o.name)}</b><small>${esc((o.tags||[]).join(' · '))}</small><p>${esc(o.description)}</p><strong>CLAIM</strong></button>`).join('')}</div><div class="reward-controls"><button data-reroll="${esc(c.id)}" ${avail.componentFree+avail.componentCredits<=0?'disabled':''}>REROLL OFFERS · ${avail.componentFree?`${avail.componentFree} FREE`:`${avail.componentCredits} CREDIT${avail.componentCredits===1?'':'S'}`}</button>${c.categoryPool?`<button data-cat-reroll="${esc(c.id)}" ${avail.categoryCredits<=0?'disabled':''}>REROLL CATEGORY · ${avail.categoryCredits}</button>`:''}<button class="skip" data-skip="${esc(c.id)}">SKIP · +${avail.skipSalvage} SALVAGE</button></div>`}
 card.innerHTML=`<header><div><span class="component-kicker">${c.kind==='bonus'?'BONUS COMPONENT':'CHOICE COMPONENT'}</span><h2>${esc(c.category.toUpperCase())}</h2></div><div class="component-meta">${c.thesisApplied?'<b>THESIS MATCH GUARANTEED</b>':''}<span>${c.offers?.length||0} OFFER${(c.offers?.length||0)===1?'':'S'}</span></div></header>${body}`;host.appendChild(card)}
 host.querySelectorAll('[data-claim]').forEach(b=>b.onclick=()=>{W.claimSaved(b.dataset.claim,b.dataset.offer);renderReward()});host.querySelectorAll('[data-skip]').forEach(b=>b.onclick=()=>{W.skipSaved(b.dataset.skip);renderReward()});host.querySelectorAll('[data-reroll]').forEach(b=>b.onclick=()=>{W.rerollComponentSaved(b.dataset.reroll);renderReward()});host.querySelectorAll('[data-cat-reroll]').forEach(b=>b.onclick=()=>{W.rerollCategorySaved(b.dataset.catReroll);renderReward()});
 const packetBtn=$('packetReroll');packetBtn.hidden=!(r.reward.rerollCredits.packet>0&&!p.completed);packetBtn.textContent=`REROLL UNRESOLVED PACKET · ${r.reward.rerollCredits.packet||0}`;$('rewardContinue').hidden=!p.completed;$('rewardOpenCount').textContent=p.completed?'PACKET RESOLVED':`${p.components.filter(c=>c.status==='open').length} COMPONENT${p.components.filter(c=>c.status==='open').length===1?'':'S'} OPEN`;return true}
function filterDeployment(){if(filtering)return;filtering=true;try{const r=run(),dep=$('deployment');if(!r||!dep||dep.hidden)return;for(const row of dep.querySelectorAll('.unit-row')){const id=row.querySelector('button[data-i]')?.dataset.i;if(id&&!r.inventory.units.includes(id))row.remove()}for(const sel of dep.querySelectorAll('[data-tower]'))for(const o of [...sel.options])if(!r.inventory.towers.includes(o.value))o.remove();const eye=dep.querySelector('.eyebrow'),title=dep.querySelector('h2'),muted=dep.querySelector('.muted');if(r.currentNode==='A1-B2'){if(eye)eye.textContent='SPLIT CAUSEWAY · ROTATION / TRIAGE';if(title)title.textContent='Deploy for two living lanes under raid pressure.';if(muted)muted.textContent='Split Causeway now runs on Living Lanes: reinforcements and raiders move as cohorts, while the Warden’s real position determines whether incoming raids are intercepted.'}}finally{filtering=false}}
function scheduleFilter(){if(filterQueued)return;filterQueued=true;setTimeout(()=>{filterQueued=false;filterDeployment();decorateMap()},0)}
function decorateMap(){const r=run(),map=$('map');if(!r||!map||map.hidden)return;const footer=$('mapFooter');if(!footer)return;const picked=[...(r.inventory.relics||[]),...(r.inventory.commander||[]),...(r.inventory.upgrades||[])];const cap=(r.capacity.unitBonus||r.capacity.towerBonus)?` · CAP ${6+r.capacity.unitBonus}U/${4+r.capacity.towerBonus}T`:'';const extraUnits=(r.inventory.units||[]).filter(x=>!['ironjack','slingline','bulwark','zealot','ram'].includes(x)).length,extraTowers=(r.inventory.towers||[]).filter(x=>!['bolt','frost','scatter','pylon'].includes(x)).length;footer.textContent=`${footer.textContent.split(' · P2 BUILD:')[0]} · P2 BUILD: ${picked.length} rule upgrade${picked.length===1?'':'s'}, ${extraUnits} unit unlock${extraUnits===1?'':'s'}, ${extraTowers} tower unlock${extraTowers===1?'':'s'}${cap}`}
function wrapContinue(){const b=$('continueRun');if(!b||b.dataset.rewardWrapped)return;b.dataset.rewardWrapped='1';const old=b.onclick;b.onclick=e=>{if(renderReward())return;old?.call(b,e)}}
window.addEventListener('lw:reward-ready',()=>setTimeout(renderReward,0));
$('packetReroll').onclick=()=>{W.rerollPacketSaved();renderReward()};
$('rewardContinue').onclick=()=>{const r=W.finalizeSaved();if(!r)return;sessionStorage.setItem('lw-reward-return','1');location.reload()};
wrapContinue();
const obs=new MutationObserver(scheduleFilter);obs.observe(document.getElementById('app'),{subtree:true,childList:true,attributes:true,attributeFilter:['hidden']});
if(run()?.reward?.pendingPacket&&(!$('home')||$('home').hidden===false))wrapContinue();
if(sessionStorage.getItem('lw-reward-return')==='1'){sessionStorage.removeItem('lw-reward-return');setTimeout(()=>{$('continueRun')?.onclick?.()},0)}
setTimeout(()=>{const reg=$('regression'),t=window.LW_ENGINE?.selfTest?.(),build=window.LW_UPDATE?.currentBuild||W.build||'P2';if(reg&&t)reg.textContent=`internal invariants: ${t.pass?'PASS':'FAIL'} · ${build}`;scheduleFilter()},0);
})();
