(() => {
'use strict';
const E=window.LW_ENGINE,D=window.LW_DATA,RD=window.LW_REWARD_DATA;
if(!E||!D||!RD)return;
const BUILD='P2-0.21.0',SAVE='lane-warden-production-run-v1';
const BASE_UNITS=['ironjack','slingline','bulwark','zealot','ram'];
const BASE_TOWERS=['bolt','frost','scatter','pylon'];
for(const u of RD.units)if(!D.units.some(x=>x.id===u.id))D.units.push(u);
for(const t of RD.towers)if(!D.towers.some(x=>x.id===t.id))D.towers.push(t);
const POOLS={
 normalGrowth:{unit:20,tower:20,commander:15,relic:15,upgrade:15,capacity:10,logistics:5},
 normalBonus:{upgrade:30,logistics:30,relic:20,capacity:20},
 eliteSecondary:{unit:20,tower:20,commander:15,upgrade:20,capacity:15,logistics:10},
 gatekeeperGrowth:{unit:18,tower:18,commander:18,upgrade:20,capacity:16,logistics:10}
};
const QUALITY={normal:{common:75,uncommon:23,rare:2},normalBonus:{common:60,uncommon:35,rare:5},eliteRelic:{common:35,uncommon:50,rare:15},eliteSecondary:{common:55,uncommon:38,rare:7},gatekeeperRelic:{common:10,uncommon:55,rare:35},gatekeeperGrowth:{common:40,uncommon:45,rare:15}};
const original={newRun:E.newRun,validateDeployment:E.validateDeployment,createBattle:E.createBattle,stepBattle:E.stepBattle,useAbility:E.useAbility,setCommanderLane:E.setCommanderLane,purchaseStructure:E.purchaseStructure,resolveLastStand:E.resolveLastStand,resolveVictory:E.resolveVictory,selfTest:E.selfTest};
function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let a=seed>>>0;return()=>{let t=a+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function clone(v){return JSON.parse(JSON.stringify(v))}
function persist(run){run.updatedAt=new Date().toISOString();localStorage.setItem(SAVE,JSON.stringify(run));return run}
function readSaved(){try{const r=JSON.parse(localStorage.getItem(SAVE)||'null');return r?ensureRun(r):null}catch{return null}}
function ensureRun(run){
 if(!run)return run;run.schema=Math.max(3,run.schema||0);run.version=BUILD;
 run.act=run.act||{};if(!Number.isFinite(run.act.normalBattlesResolved))run.act.normalBattlesResolved=0;
 run.inventory=run.inventory||{};run.inventory.units=run.inventory.units||BASE_UNITS.slice();run.inventory.towers=run.inventory.towers||BASE_TOWERS.slice();run.inventory.commander=run.inventory.commander||[];run.inventory.relics=run.inventory.relics||[];run.inventory.upgrades=run.inventory.upgrades||[];run.inventory.capacity=run.inventory.capacity||[];run.inventory.rift=run.inventory.rift||[];
 run.capacity=run.capacity||{unitBonus:0,towerBonus:0};if(!Number.isFinite(run.capacity.unitBonus))run.capacity.unitBonus=0;if(!Number.isFinite(run.capacity.towerBonus))run.capacity.towerBonus=0;
 run.reward=run.reward||{};run.reward.pendingPacket=run.reward.pendingPacket||null;run.reward.lastPacket=run.reward.lastPacket||null;run.reward.rerollCredits=run.reward.rerollCredits||{component:0,category:0,packet:0};for(const k of ['component','category','packet'])if(!Number.isFinite(run.reward.rerollCredits[k]))run.reward.rerollCredits[k]=0;run.reward.revealState=Number(run.reward.revealState||0);run.reward.nextSkipBonus=Number(run.reward.nextSkipBonus||0);run.reward.packetSequence=Number(run.reward.packetSequence||0);run.reward.history=run.reward.history||[];
 run.thesis=run.thesis||null;return run
}
E.newRun=(seed)=>ensureRun(original.newRun(seed));
function owned(run,kind,id){run=ensureRun(run);if(kind==='unit')return run.inventory.units.includes(id);if(kind==='tower')return run.inventory.towers.includes(id);return false}
function caps(run){run=ensureRun(run||readSaved()||E.newRun('capacity-fallback'));return{unit:D.deployment.unitCapacity+(run.capacity.unitBonus||0),tower:D.deployment.towerCapacity+(run.capacity.towerBonus||0)}}
E.validateDeployment=(dep)=>{
 const run=readSaved(),c=E.deploymentCost(dep),cap=caps(run),reasons=[];
 if(c.unitCost>cap.unit)reasons.push(`Unit points ${c.unitCost}/${cap.unit}`);if(c.towerCost>cap.tower)reasons.push(`Tower points ${c.towerCost}/${cap.tower}`);
 for(const lane of ['north','south']){const count=Object.values(dep[lane].units||{}).reduce((a,b)=>a+b,0);if(count<1)reasons.push(`${lane} needs at least one committed unit`);for(const [id,n] of Object.entries(dep[lane].units||{}))if(n>0&&run&&!run.inventory.units.includes(id))reasons.push(`${id} is not owned`);if(dep[lane].tower&&run&&!run.inventory.towers.includes(dep[lane].tower))reasons.push(`${dep[lane].tower} is not owned`);if(dep[lane].tower&&!D.towers.some(t=>t.id===dep[lane].tower))reasons.push(`${lane} tower is invalid`)}
 return{legal:reasons.length===0,reasons,...c,unitCapacity:cap.unit,towerCapacity:cap.tower}
};
function inferThesis(b){let siege=0,pulse=0,hold=0;for(const lane of ['north','south']){const u=b.deployment?.[lane]?.units||{};siege+=(u.ram||0)+(u.sapper||0);pulse+=(u.drummer||0)+(u.slingline||0);hold+=(u.bulwark||0)+(u['lantern-guard']||0)}if(siege>0)return'siege';if(pulse>=3)return'pulse';if(hold>=2)return'hold';return'rotation'}
function mods(run){const rel=new Set(run.inventory.relics);return{offerDelta:rel.has('relic-broadside-ledger')?1:0,freeComponent:rel.has('relic-quartermaster-token')?1:0,bonusChance:.25+(rel.has('relic-lucky-ash')?.20:0),skipMultiplier:rel.has('relic-salvagers-seal')?1.5:1,receipt:[rel.has('relic-broadside-ledger')&&'Broadside Ledger · +1 Growth offer',rel.has('relic-quartermaster-token')&&'Quartermaster’s Token · first component reroll free',rel.has('relic-lucky-ash')&&'Lucky Ash · +20% Bonus chance',rel.has('relic-salvagers-seal')&&'Salvager’s Seal · +50% skip Salvage'].filter(Boolean)}}
function uniqueOwned(run,item,cat){if(item.repeatable)return false;if(cat==='unit')return run.inventory.units.includes(item.contentId);if(cat==='tower')return run.inventory.towers.includes(item.contentId);if(cat==='commander')return run.inventory.commander.includes(item.id);if(cat==='relic')return run.inventory.relics.includes(item.id);if(cat==='upgrade')return run.inventory.upgrades.includes(item.id);if(cat==='capacity')return run.inventory.capacity.includes(item.id);return false}
function targetOwned(run,item){if(!item.target)return true;return owned(run,item.target.kind,item.target.id)}
function eligible(run,cat){if(cat==='tower'&&run.catalogue?.towersAllowed===false)return[];return(RD.catalog[cat]||[]).filter(i=>!uniqueOwned(run,i,cat)&&targetOwned(run,i))}
function weighted(obj,r,allowed){const pairs=Object.entries(obj).filter(([k,w])=>w>0&&(!allowed||allowed.includes(k)));const total=pairs.reduce((s,[,w])=>s+w,0);if(!total)return null;let x=r()*total;for(const[k,w]of pairs){x-=w;if(x<=0)return k}return pairs[pairs.length-1][0]}
function quality(policy,r){return weighted(QUALITY[policy]||QUALITY.normal,r)}
function legalCategories(run,pool){return Object.keys(POOLS[pool]).filter(c=>eligible(run,c).length>0)}
function rollCategory(run,pool,r,affinity=[]){const legal=legalCategories(run,pool);if(!legal.length)return'logistics';const weights={...POOLS[pool]};for(const a of affinity||[])if(weights[a])weights[a]*=1.5;return weighted(weights,r,legal)||legal[0]}
function offerSet(run,cat,count,policy,seed,thesisFloor){let items=eligible(run,cat),r=rng(seed),out=[],applied=false;if(!items.length){cat=eligible(run,'upgrade').length?'upgrade':'logistics';items=eligible(run,cat)}
 if(thesisFloor&&run.thesis){const compat=items.filter(i=>(i.thesis||[]).includes(run.thesis));if(compat.length){const pick=compat[Math.floor(r()*compat.length)];out.push(clone(pick));items=items.filter(i=>i.id!==pick.id);applied=true}}
 while(out.length<count&&items.length){const targetQ=quality(policy,r),same=items.filter(i=>i.quality===targetQ),pool=same.length?same:items,pick=pool[Math.floor(r()*pool.length)];out.push(clone(pick));items=items.filter(i=>i.id!==pick.id)}
 return{category:cat,offers:out,thesisApplied:applied}
}
function makeComponent(run,packet,spec,index){const r=rng(hash(`${packet.seedKey}|component|${spec.id}|${index}|0`)),cat=spec.category||rollCategory(run,spec.pool,r,spec.affinity||[]),count=spec.offerCount+(spec.standardGrowth?packet.modifiers.offerDelta:0),set=offerSet(run,cat,count,spec.policy,hash(`${packet.seedKey}|offers|${spec.id}|0`),!!spec.thesisFloor);return{id:spec.id,kind:spec.kind||'choice',category:set.category,categoryPool:spec.pool||null,fixedCategory:!!spec.category,qualityPolicy:spec.policy,baseOfferCount:spec.offerCount,offerCount:count,standardGrowth:!!spec.standardGrowth,thesisFloorEligible:!!spec.thesisFloor,thesisApplied:set.thesisApplied,offers:set.offers,status:'open',claimed:null,rerollIndex:0,categoryRerollIndex:0,skipBase:spec.skipBase||40}}
function nextNode(nodeId,type='normal'){if(type==='gatekeeper'||nodeId==='A1-GK')return'A1-END';return nodeId==='A1-B1'?'A1-B2':nodeId==='A1-B2'?'A1-F1':nodeId==='A1-B3'?'A1-R1':'A1-F1'}
function generatePacket(run,nodeId,type='normal',opts={}){run=ensureRun(run);const seq=run.reward.packetSequence||0,seedKey=`${run.seed}|${nodeId}|${type}|${seq}`,m=mods(run),packet={schema:1,id:`${nodeId}-${seq}`,nodeId,type,seedKey,generatedAt:new Date().toISOString(),grantSalvage:type==='normal'?140:type==='elite'?220:260,modifiers:m,freeComponentRerollsRemaining:m.freeComponent,components:[],completed:false,nextNode:nextNode(nodeId,type),receipt:[]};
 let specs=[];if(type==='normal')specs=[{id:'growth',pool:'normalGrowth',offerCount:3,policy:'normal',standardGrowth:true,thesisFloor:true,skipBase:40}];else if(type==='elite')specs=[{id:'elite-relic',category:'relic',offerCount:3,policy:'eliteRelic',skipBase:55},{id:'elite-secondary',pool:'eliteSecondary',offerCount:3,policy:'eliteSecondary',thesisFloor:true,skipBase:50}];else specs=[{id:'gatekeeper-relic',category:'relic',offerCount:3,policy:'gatekeeperRelic',skipBase:70},{id:'gatekeeper-growth',pool:'gatekeeperGrowth',offerCount:3,policy:'gatekeeperGrowth',thesisFloor:true,skipBase:60}];
 let thesisFloorUnused=true;specs.forEach((s,i)=>{const c=makeComponent(run,packet,{...s,thesisFloor:s.thesisFloor&&thesisFloorUnused},i);if(c.thesisApplied)thesisFloorUnused=false;packet.components.push(c)});
 if(type==='normal'){const r=rng(hash(`${seedKey}|bonus`));if(r()<Math.min(.95,m.bonusChance)){const s={id:'normal-bonus',pool:'normalBonus',offerCount:2,policy:'normalBonus',skipBase:30};packet.components.push(makeComponent(run,packet,s,packet.components.length));packet.receipt.push(`Bonus component rolled at ${Math.round(m.bonusChance*100)}% chance`)}}
 packet.receipt.push(...m.receipt);if(packet.components.some(c=>c.thesisApplied))packet.receipt.push(`Thesis floor · one ${run.thesis} compatible offer guaranteed`);run.reward.packetSequence=seq+1;return packet}
function history(run,type,data){run.reward.history.push({at:new Date().toISOString(),type,...data});if(run.reward.history.length>120)run.reward.history.splice(0,run.reward.history.length-120)}
function resolveVictory(run,b){run=ensureRun(run);if(run.reward.pendingPacket)return{reward:run.reward.pendingPacket,nextNode:run.reward.pendingPacket.nextNode};run.thesis=run.thesis||inferThesis(b);const type=b.nodeId==='A1-GK'?'gatekeeper':'normal';if(type==='normal')run.act.normalBattlesResolved++;if(!run.resolvedNodes.some(x=>x.id===b.nodeId))run.resolvedNodes.push({id:b.nodeId,result:'victory',at:new Date().toISOString()});const packet=generatePacket(run,b.nodeId,type,{affinity:b.rewardAffinity||[]});run.salvage+=packet.grantSalvage;run.reward.pendingPacket=packet;run.currentNode=b.nodeId;b.result=b.result||{kind:'victory',at:b.elapsed};history(run,'packet-generated',{packetId:packet.id,nodeId:b.nodeId,type,grantSalvage:packet.grantSalvage,categories:packet.components.map(c=>c.category),offers:packet.components.map(c=>c.offers.map(o=>o.id))});persist(run);setTimeout(()=>window.dispatchEvent(new CustomEvent('lw:reward-ready',{detail:{packetId:packet.id}})),0);return{reward:packet,nextNode:packet.nextNode}}
E.resolveVictory=resolveVictory;
E.resolveLastStand=(run,b)=>{ensureRun(run);const out=original.resolveLastStand(run,b);if(out?.kind==='last-stand-advance'){run.currentNode=nextNode(b.nodeId,'normal');if(['A1-B1','A1-B2','A1-B3'].includes(b.nodeId))run.act.normalBattlesResolved++;history(run,'payable-last-stand',{nodeId:b.nodeId,salvage:120,nextNode:run.currentNode});persist(run)}return out};
function componentBy(packet,id){return packet?.components?.find(c=>c.id===id)}
function skipValue(run,packet,c){return Math.round(c.skipBase*(packet.modifiers?.skipMultiplier||1))+(run.reward.nextSkipBonus||0)}
function applyOffer(run,cat,o){if(cat==='unit'&&!run.inventory.units.includes(o.contentId))run.inventory.units.push(o.contentId);else if(cat==='tower'&&!run.inventory.towers.includes(o.contentId))run.inventory.towers.push(o.contentId);else if(cat==='commander'&&!run.inventory.commander.includes(o.id))run.inventory.commander.push(o.id);else if(cat==='relic'&&!run.inventory.relics.includes(o.id))run.inventory.relics.push(o.id);else if(cat==='upgrade'&&!run.inventory.upgrades.includes(o.id))run.inventory.upgrades.push(o.id);else if(cat==='capacity'&&!run.inventory.capacity.includes(o.id)){run.inventory.capacity.push(o.id);run.capacity.unitBonus+=o.capacity?.unit||0;run.capacity.towerBonus+=o.capacity?.tower||0}else if(cat==='logistics'){run.reward.rerollCredits.component+=o.logistics?.component||0;run.reward.rerollCredits.category+=o.logistics?.category||0;run.reward.rerollCredits.packet+=o.logistics?.packet||0;run.reward.revealState+=o.logistics?.reveal||0;run.reward.nextSkipBonus+=o.logistics?.nextSkipBonus||0}}
function updateCompleted(packet){packet.completed=packet.components.every(c=>c.status!=='open');if(packet.completed)packet.completedAt=packet.completedAt||new Date().toISOString()}
function claimSaved(componentId,offerId){const run=readSaved(),packet=run?.reward?.pendingPacket,c=componentBy(packet,componentId);if(!run||!packet||!c||c.status!=='open')return null;const o=c.offers.find(x=>x.id===offerId);if(!o)return null;applyOffer(run,c.category,o);c.status='claimed';c.claimed=clone(o);history(run,'reward-claimed',{packetId:packet.id,componentId:c.id,category:c.category,offerId:o.id});updateCompleted(packet);persist(run);return{run,packet}}
function skipSaved(componentId){const run=readSaved(),packet=run?.reward?.pendingPacket,c=componentBy(packet,componentId);if(!run||!packet||!c||c.status!=='open')return null;const amount=skipValue(run,packet,c);run.salvage+=amount;if(run.reward.nextSkipBonus>0)run.reward.nextSkipBonus=0;c.status='skipped';c.skipSalvage=amount;history(run,'reward-skipped',{packetId:packet.id,componentId:c.id,category:c.category,salvage:amount});updateCompleted(packet);persist(run);return{run,packet}}
function rerollOffers(run,packet,c){c.rerollIndex++;const count=c.baseOfferCount+(c.standardGrowth?packet.modifiers.offerDelta:0),set=offerSet(run,c.category,count,c.qualityPolicy,hash(`${packet.seedKey}|offers|${c.id}|reroll|${c.rerollIndex}`),c.thesisFloorEligible);c.category=set.category;c.offerCount=count;c.offers=set.offers;c.thesisApplied=set.thesisApplied}
function rerollComponentSaved(componentId){const run=readSaved(),packet=run?.reward?.pendingPacket,c=componentBy(packet,componentId);if(!run||!packet||!c||c.status!=='open')return null;let source=null;if(packet.freeComponentRerollsRemaining>0){packet.freeComponentRerollsRemaining--;source='free'}else if(run.reward.rerollCredits.component>0){run.reward.rerollCredits.component--;source='credit'}else return null;rerollOffers(run,packet,c);history(run,'component-rerolled',{packetId:packet.id,componentId:c.id,source,offers:c.offers.map(o=>o.id)});persist(run);return{run,packet}}
function rerollCategorySaved(componentId){const run=readSaved(),packet=run?.reward?.pendingPacket,c=componentBy(packet,componentId);if(!run||!packet||!c||c.status!=='open'||!c.categoryPool||run.reward.rerollCredits.category<=0)return null;run.reward.rerollCredits.category--;c.categoryRerollIndex++;const r=rng(hash(`${packet.seedKey}|category|${c.id}|${c.categoryRerollIndex}`)),legal=legalCategories(run,c.categoryPool).filter(x=>x!==c.category);c.category=weighted(POOLS[c.categoryPool],r,legal.length?legal:legalCategories(run,c.categoryPool))||c.category;c.rerollIndex++;const count=c.baseOfferCount+(c.standardGrowth?packet.modifiers.offerDelta:0),set=offerSet(run,c.category,count,c.qualityPolicy,hash(`${packet.seedKey}|cat-offers|${c.id}|${c.categoryRerollIndex}`),c.thesisFloorEligible);c.category=set.category;c.offers=set.offers;c.offerCount=count;c.thesisApplied=set.thesisApplied;history(run,'category-rerolled',{packetId:packet.id,componentId:c.id,category:c.category,offers:c.offers.map(o=>o.id)});persist(run);return{run,packet}}
function rerollPacketSaved(){const run=readSaved(),packet=run?.reward?.pendingPacket;if(!run||!packet||packet.completed||run.reward.rerollCredits.packet<=0)return null;run.reward.rerollCredits.packet--;packet.packetRerollIndex=(packet.packetRerollIndex||0)+1;for(const c of packet.components){if(c.status!=='open')continue;if(c.categoryPool&&!c.fixedCategory){const r=rng(hash(`${packet.seedKey}|packet-cat|${packet.packetRerollIndex}|${c.id}`));c.category=rollCategory(run,c.categoryPool,r)}c.rerollIndex++;const count=c.baseOfferCount+(c.standardGrowth?packet.modifiers.offerDelta:0),set=offerSet(run,c.category,count,c.qualityPolicy,hash(`${packet.seedKey}|packet-offers|${packet.packetRerollIndex}|${c.id}`),c.thesisFloorEligible);c.category=set.category;c.offers=set.offers;c.offerCount=count;c.thesisApplied=set.thesisApplied}history(run,'packet-rerolled',{packetId:packet.id,index:packet.packetRerollIndex});persist(run);return{run,packet}}
function finalizeSaved(){const run=readSaved(),packet=run?.reward?.pendingPacket;if(!run||!packet||!packet.completed)return null;run.reward.lastPacket=packet;run.reward.pendingPacket=null;run.currentNode=packet.nextNode;if(run.currentNode==='A1-END'){run.completedAt=run.completedAt||new Date().toISOString();run.endedAt=run.endedAt||run.completedAt;run.endReason=run.endReason||'gatekeeper-victory'}history(run,'packet-resolved',{packetId:packet.id,nextNode:run.currentNode});persist(run);return run}
function availability(run,packet,c){return{componentFree:packet.freeComponentRerollsRemaining||0,componentCredits:run.reward.rerollCredits.component||0,categoryCredits:run.reward.rerollCredits.category||0,packetCredits:run.reward.rerollCredits.packet||0,skipSalvage:skipValue(run,packet,c)}}
function laneUnitCount(b,lane,id){return b.deployment?.[lane]?.units?.[id]||0}
function applyRunBattle(run,b){ensureRun(run);b.rewardBuild=BUILD;b.runEffects={relics:run.inventory.relics.slice(),commander:run.inventory.commander.slice(),upgrades:run.inventory.upgrades.slice(),rift:run.inventory.rift.slice(),misersCogUsed:false,gatebiteUsed:false,bastionOathUsed:false};if(run.inventory.relics.includes('relic-reclamation-clock'))b.reclamation.trigger+=15;return b}
E.createBattle=(run,deployment)=>{run=ensureRun(run);const v=E.validateDeployment(deployment);if(!v.legal)throw new Error(`Illegal deployment: ${v.reasons.join(', ')}`);const oldU=D.deployment.unitCapacity,oldT=D.deployment.towerCapacity,cap=caps(run);D.deployment.unitCapacity=cap.unit;D.deployment.towerCapacity=cap.tower;let b;try{b=original.createBattle(run,deployment)}finally{D.deployment.unitCapacity=oldU;D.deployment.towerCapacity=oldT}b.nodeId=run.currentNode||'A1-B1';return applyRunBattle(run,b)};
function hasEffect(b,list,id){return b.runEffects?.[list]?.includes(id)}
function markBreak(b,lane,before){if(before>0&&lane.guard<=0){lane.guardDestroyedEver=true;b.gateVulnerabilityLatched=true;b.gateVulnerable=true;if(hasEffect(b,'relics','relic-gatebite-sigil')&&!b.runEffects.gatebiteUsed){b.runEffects.gatebiteUsed=true;b.gate=Math.max(0,b.gate-8);b.events.push({t:b.elapsed,type:'reward-effect',id:'relic-gatebite-sigil',lane:lane.id})}}}
E.useAbility=(b,id,targetLane)=>{const laneId=targetLane||b.commander?.lane,lane=laneId&&b.lanes?.[laneId],guardBefore=lane?.guard??0,gateBefore=b.gate,ok=original.useAbility(b,id,targetLane);if(!ok)return false;if(id==='rally'&&hasEffect(b,'commander','cmd-rally-standard'))lane.reinforcementPulses+=1;if(id==='sunder'&&lane){const sappers=laneUnitCount(b,laneId,'sapper');if(sappers){if(lane.guard>0)lane.guard=Math.max(0,lane.guard-4*sappers);else if(b.gateVulnerabilityLatched)b.gate=Math.max(0,b.gate-3*sappers)}if(hasEffect(b,'commander','cmd-sunder-echo')){if(lane.guard>0)lane.guard=Math.max(0,lane.guard-6);else if(b.gateVulnerabilityLatched)b.gate=Math.max(0,b.gate-5)}if(hasEffect(b,'upgrades','upgrade-ram-hook')&&laneUnitCount(b,laneId,'ram')>0&&guardBefore<=0&&b.gateVulnerabilityLatched)b.gate=Math.max(0,b.gate-4);markBreak(b,lane,guardBefore)}if(id==='waypoint'){if(hasEffect(b,'commander','cmd-waypoint-reserve'))b.readReserve=Math.min(4,b.readReserve+1.5);if(hasEffect(b,'upgrades','upgrade-pylon-relay')&&b.deployment?.[laneId]?.tower==='pylon')b.effects[laneId].rally=Math.max(b.effects[laneId].rally,4)}if(id==='conscript'&&hasEffect(b,'commander','cmd-conscript-draft'))lane.reinforcementPulses+=1;if(gateBefore>0&&b.gate<=0&&!b.result)b.result={kind:'victory',at:b.elapsed};return true};
E.setCommanderLane=(b,lane)=>{const from=b.commander?.lane,ok=original.setCommanderLane(b,lane);if(ok&&b.commander.travel){let mult=1;if(hasEffect(b,'relics','relic-junction-spurs'))mult*=.8;if(laneUnitCount(b,from,'wardrunner')||laneUnitCount(b,lane,'wardrunner'))mult*=.85;if(b.deployment?.[from]?.tower==='beacon'||b.deployment?.[lane]?.tower==='beacon')mult*=.85;b.commander.travel.total*=mult;b.commander.travel.remaining*=mult}return ok};
E.stepBattle=(b,dt)=>{const before={};for(const id of ['north','south'])before[id]={pulse:b.lanes[id].pulseCount,guard:b.lanes[id].guard,bastion:b.lanes[id].bastion};const travel=!!b.commander.travel;const out=original.stepBattle(b,dt);for(const id of ['north','south']){const l=b.lanes[id],pulsed=l.pulseCount>before[id].pulse;if(pulsed){const drummers=laneUnitCount(b,id,'drummer');if(drummers)l.front=Math.min(.92,l.front+.006*drummers);const lantern=laneUnitCount(b,id,'lantern-guard');if(lantern)l.bastion=Math.min(100,l.bastion+3*lantern);if(b.deployment?.[id]?.tower==='pulsebell')b.gold=Math.min(99,b.gold+3);if(b.deployment?.[id]?.tower==='bastionloom')l.bastion=Math.min(100,l.bastion+5);if(hasEffect(b,'upgrades','upgrade-slingline-drums')&&laneUnitCount(b,id,'slingline')>0&&l.pulseCount%3===0)l.front=Math.min(.92,l.front+.018);if(hasEffect(b,'relics','relic-pulse-prism')&&!b.commander.incapacitated&&!b.commander.travel&&!b.commander.siteTravel&&!b.commander.atSite&&!b.commander.work&&b.commander.lane===id&&l.pulseCount%3===0)b.effects[id].conscript=Math.max(b.effects[id].conscript,6)}if(b.deployment?.[id]?.tower==='harpoon'&&l.front>.70&&l.guard>0)l.guard=Math.max(0,l.guard-l.regen*dt*.28);markBreak(b,l,before[id].guard);if(hasEffect(b,'relics','relic-bastion-oath')&&!b.runEffects.bastionOathUsed&&l.bastion>0&&l.bastion<35){b.runEffects.bastionOathUsed=true;l.bastion=Math.min(100,l.bastion+20);b.events.push({t:b.elapsed,type:'reward-effect',id:'relic-bastion-oath',lane:id})}}if(travel&&!b.commander.travel&&!b.commander.incapacitated&&hasEffect(b,'commander','cmd-field-triage'))b.commander.health=Math.min(b.commander.maxHealth,b.commander.health+20);return out};
E.purchaseStructure=(b,laneId,kind)=>{let discount=0;if(hasEffect(b,'relics','relic-misers-cog')&&!b.runEffects.misersCogUsed)discount=8;if(discount)b.gold+=discount;const out=original.purchaseStructure(b,laneId,kind);if(discount&&!out.ok)b.gold-=discount;if(out.ok&&discount){b.runEffects.misersCogUsed=true;b.events.push({t:b.elapsed,type:'reward-effect',id:'relic-misers-cog',saved:discount})}const l=b.lanes[laneId];if(out.ok&&kind==='overcharge'&&hasEffect(b,'upgrades','upgrade-frost-condenser')&&b.deployment?.[laneId]?.tower==='frost')l.baseEnemyPower*=.95;if(out.ok&&kind==='reinforce'&&hasEffect(b,'upgrades','upgrade-bulwark-entrench')&&laneUnitCount(b,laneId,'bulwark')>0)l.bastion=Math.min(100,l.bastion+8);return out};
E.selfTest=()=>{const base=original.selfTest(),a=ensureRun(original.newRun('reward-determinism')),b=ensureRun(original.newRun('reward-determinism'));a.thesis=b.thesis='siege';const pa=generatePacket(a,'A1-B1','normal'),pb=generatePacket(b,'A1-B1','normal');const checks={rewardCatalog:Object.entries(RD.catalog).every(([k,v])=>v.length>=({unit:4,tower:4,commander:4,relic:8,upgrade:4,capacity:3,logistics:4}[k]||0)),rewardDeterministic:JSON.stringify(pa.components.map(c=>[c.category,c.offers.map(o=>o.id)]))===JSON.stringify(pb.components.map(c=>[c.category,c.offers.map(o=>o.id)])),rewardPersistentShape:!!pa.id&&pa.components.length>=1,thesisBounded:pa.components.filter(c=>c.thesisApplied).length<=1};return{pass:base.pass&&Object.values(checks).every(Boolean),checks:{...base.checks,...checks}}};
window.LW_REWARDS={build:BUILD,ensureRun,readSaved,persist,generatePacket,claimSaved,skipSaved,rerollComponentSaved,rerollCategorySaved,rerollPacketSaved,finalizeSaved,availability,eligible,mods,nextNode};
})();
