(() => {
'use strict';
const R=window.LW_RIFT;if(!R)return;
const $=id=>document.getElementById(id),screens=['home','map','deployment','battle','resolution','lastStand','reward','forge','rift','actComplete'];
let current=null;
function hideAll(){for(const id of screens){const el=$(id);if(el)el.hidden=true}}
function receipt(result){const c=result.receipt;hideAll();$('rift').hidden=false;$('riftChoice').hidden=true;$('riftReceipt').hidden=false;if(c.choice==='power'){$('riftReceiptMark').textContent='◆';$('riftReceiptEyebrow').textContent='EMBER OFFERED · RIFT IMPRINT REVEALED';$('riftReceiptName').textContent=c.boon.name;$('riftReceiptEffect').textContent=c.boon.description;$('riftReceiptCost').textContent=`1 EMBER SPENT · ${result.run.embers} REMAIN · SAVED FOR THIS RUN`}else{$('riftReceiptMark').textContent='◇';$('riftReceiptEyebrow').textContent='RIFT STRIPPED · EMBERS PRESERVED';$('riftReceiptName').textContent=`+${c.salvage} SALVAGE`;$('riftReceiptEffect').textContent='The company takes the certain value and preserves its failure budget for the Ironbound Gate.';$('riftReceiptCost').textContent=`${result.run.embers} EMBERS REMAIN · RUN SAVED`}}
function render(){const opened=R.openSaved();if(!opened)return false;current=opened.run;hideAll();$('rift').hidden=false;$('riftChoice').hidden=false;$('riftReceipt').hidden=true;$('riftEmbers').textContent=`${'◆'.repeat(current.embers)}${'◇'.repeat(Math.max(0,3-current.embers))} · ${current.embers} EMBERS`;$('riftSalvage').textContent=`${current.salvage} SALVAGE`;$('riftPower').disabled=current.embers<1;$('riftPower').querySelector('strong').textContent=current.embers>0?'OFFER 1 EMBER':'NO EMBER TO OFFER';$('riftFeedback').textContent=current.embers>0?'The Ember outcome is deterministic for this run, but remains unknown until committed.':'Only the certain Salvage route remains.';return true}
function choose(kind){const result=R.resolveSaved(kind);if(result.ok)receipt(result);else $('riftFeedback').textContent=result.reason}
addEventListener('lw:node-open',e=>{if(e.detail?.nodeId===R.nodeId)render()});$('riftPower').onclick=()=>choose('power');$('riftSalvageChoice').onclick=()=>choose('salvage');$('riftReturn').onclick=()=>{sessionStorage.setItem('lw-rift-return','1');location.reload()};if(sessionStorage.getItem('lw-rift-return')==='1'){sessionStorage.removeItem('lw-rift-return');setTimeout(()=>document.getElementById('continueRun')?.onclick?.(),0)}window.LW_RIFT_UI={build:'P2-0.20.0',render};
})();
