(() => {
'use strict';
const SAVE='lane-warden-production-run-v1',$=id=>document.getElementById(id);
function saved(){try{return JSON.parse(localStorage.getItem(SAVE)||'null')}catch{return null}}
function battle(){return window.LW_ACTIVE_BATTLE||saved()?.battle?.state||null}
function bar(){let el=$('routePressureBar');if(el)return el;const prompt=$('battlePrompt');if(!prompt)return null;el=document.createElement('div');el.id='routePressureBar';el.className='route-pressure-bar';el.hidden=true;prompt.insertAdjacentElement('afterend',el);return el}
function clearLane(id){const el=$(id+'Extra');if(el&&/route-/.test(el.className)){el.textContent='';el.className=''}}
function laneMark(id,active,text,kind){const el=$(id+'Extra');if(!el||!active)return;el.textContent=text;el.className=`route-${kind}`}
function paintSwitchback(b,el){const s=b.switchback,target=s.target||s.lastTarget||s.nextTarget||'south',time=s.timer.toFixed(1);el.hidden=false;el.className=`route-pressure-bar ${s.phase}${s.protected?' protected':''}`;el.innerHTML=`<b>${s.phase==='warning'?'FALL LINE':s.phase==='surge'?(s.protected?'BRACED':'COLLAPSE'):'RIDGE SHIFT'} · ${target.toUpperCase()}</b><span>${time}s · ${s.message}</span>`;if(s.phase==='warning')laneMark(target,true,`FALL ${Math.ceil(s.timer)}`,'warning');else if(s.phase==='surge')laneMark(target,true,s.source==='warden'?'BRACED':s.source==='fieldworks'?'WORKS HOLD':'COLLAPSE',s.protected?'protected':'surge');else laneMark(s.nextTarget,true,'NEXT FALL','next');const hud=document.querySelector('#battle .hud-top > b');if(hud)hud.textContent='THE WARDEN · BROKEN SWITCHBACK'}
function paintGatekeeper(b,el){const g=b.gatekeeper,target=g.target||g.lastTarget||'north',time=g.timer.toFixed(1);el.hidden=false;el.className=`route-pressure-bar gatekeeper ${g.phase}${g.protected?' protected':''}`;el.innerHTML=`<b>${g.phase==='warning'?'IRON EDICT':g.phase==='surge'?(g.protected?'EDICT BROKEN':'CONDEMNED'):'GATEKEEPER WATCH'} · ${target.toUpperCase()}</b><span>${time}s · ${g.message}${g.rage?` · RAGE ${g.rage}`:''}</span>`;if(g.phase==='warning')laneMark(target,true,`EDICT ${Math.ceil(g.timer)}`,'warning');else if(g.phase==='surge')laneMark(target,true,g.source==='warden'?'PRESENCE':g.source==='fieldworks'?'WORKS HOLD':'CONDEMNED',g.protected?'protected':'surge');const hud=document.querySelector('#battle .hud-top > b');if(hud)hud.textContent='THE WARDEN · IRONBOUND GATE'}
function lastStand(b){if(!b?.lastStand?.active||b.nodeId!=='A1-GK')return;const run=saved(),eye=document.querySelector('#lastStand .eyebrow'),title=document.querySelector('#lastStand h1'),copy=document.querySelector('#lastStand p'),btn=$('resolveLastStand');if(eye)eye.textContent='IRONBOUND GATE · LAST STAND';if(title)title.textContent='TWO EMBERS. ONE BREACH.';if(copy)copy.textContent=run?.embers>=2?'Bulwark Detonation can break the Gatekeeper. The act ends and two Embers are spent.':'The Gatekeeper demands two Embers. Detonation opens the road, but this run cannot continue.';if(btn)btn.textContent='DETONATE · 2 EMBERS'}
function loop(){const b=battle(),el=bar();clearLane('north');clearLane('south');if(el){if(b?.nodeId==='A1-B3'&&b.switchback)paintSwitchback(b,el);else if(b?.nodeId==='A1-GK'&&b.gatekeeper)paintGatekeeper(b,el);else el.hidden=true}lastStand(b);requestAnimationFrame(loop)}
requestAnimationFrame(loop);window.LW_ROUTE_UI={build:'P2-0.21.0'};
})();
