const BUILD='P2-0.21.0';
const CACHE=`lane-warden-prod-live-${BUILD}-r2`;
const SHELL_MARKER=`<meta name="lw-shell-build" content="${BUILD}"`;
const V='0.21.0';
const ASSETS=[
  './index.html','./layout.css','./ui-patch.css','./conscript-ui.css','./reward.css','./encounter.css','./fieldworks.css','./forge.css','./act-route.css',
  './data.js','./engine.js','./balance-patch.js','./reward-data.js','./reward-engine.js','./forge-engine.js','./living-lanes.js','./movement-model.js','./fieldworks.js','./encounter-patch.js','./switchback-patch.js','./gatekeeper-patch.js','./rift-engine.js','./app.js','./updater.js','./ui-patch.js','./conscript-ui.js','./reward-ui.js','./forge-ui.js','./rift-ui.js','./encounter-ui.js','./route-ui.js','./tactical-models.js','./living-ui.js','./fieldworks-ui.js',
  './assets/manifests/tactical-models.json','./assets/models/processed/sprites/tactical-models-atlas.json','./assets/models/processed/sprites/tactical-models-atlas.png','./manifest.webmanifest','./VERSION','./P2-0.19.0-BROKEN-SWITCHBACK.md','./P2-0.20.0-ASHEN-RIFT.md','./P2-0.21.0-IRONBOUND-GATE.md','../lane-warden/styles.css'
].map((url,i)=>`${url}${url.includes('?')?'&':'?'}v=${V}${i?'':'-shell'}`);
const CRITICAL=['living-lanes.js','movement-model.js','fieldworks.js','fieldworks-ui.js','forge-engine.js','forge-ui.js','switchback-patch.js','gatekeeper-patch.js','rift-engine.js','rift-ui.js','route-ui.js','tactical-models.js','living-ui.js'];
function validShell(text){return text.includes(SHELL_MARKER)&&CRITICAL.every(name=>text.includes(name))}
async function fetchForCache(url){const r=await fetch(url,{cache:'reload'});if(!r.ok)throw new Error(url);if(url.startsWith('./index.html')){const text=await r.clone().text();if(!validShell(text))throw new Error('stale-shell')}return r}
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(async cache=>{for(const url of ASSETS){const r=await fetchForCache(url);await cache.put(url,r)}}).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('lane-warden-prod-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('message',event=>{if(event.data?.type==='GET_BUILD')event.ports?.[0]?.postMessage({build:BUILD});if(event.data?.type==='SKIP_WAITING')self.skipWaiting()});
async function fetchFreshNavigation(req){const first=await fetch(req,{cache:'no-store'});let text='';try{text=await first.clone().text()}catch{}if(validShell(text)){caches.open(CACHE).then(c=>c.put(ASSETS[0],first.clone()));return first}const u=new URL('./index.html',self.location.href);u.searchParams.set('lw-shell',BUILD);u.searchParams.set('t',Date.now());try{const fresh=await fetch(u.href,{cache:'reload'}),freshText=await fresh.clone().text();if(fresh.ok&&validShell(freshText)){caches.open(CACHE).then(c=>c.put(ASSETS[0],fresh.clone()));return fresh}}catch{}return first}
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.pathname.endsWith('/build.json')){event.respondWith(fetch(req,{cache:'no-store'}));return}if(req.mode==='navigate'){event.respondWith(fetchFreshNavigation(req).catch(()=>caches.match(ASSETS[0])));return}event.respondWith(caches.match(req).then(hit=>hit||fetch(req).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(req,copy));return r})))})
