const BUILD='P2-0.18.0';
const CACHE=`lane-warden-prod-live-${BUILD}-r1`;
const SHELL_MARKER=`<meta name="lw-shell-build" content="${BUILD}"`;
const ASSETS=['./index.html','./layout.css?v=0.18.0','./ui-patch.css?v=0.18.0','./conscript-ui.css?v=0.18.0','./reward.css?v=0.18.0','./encounter.css?v=0.18.0','./fieldworks.css?v=0.18.0','./forge.css?v=0.18.0','./data.js?v=0.18.0','./engine.js?v=0.18.0','./balance-patch.js?v=0.18.0','./reward-data.js?v=0.18.0','./reward-engine.js?v=0.18.0','./forge-engine.js?v=0.18.0','./living-lanes.js?v=0.18.0','./movement-model.js?v=0.18.0','./fieldworks.js?v=0.18.0','./encounter-patch.js?v=0.18.0','./app.js?v=0.18.0','./updater.js?v=0.18.0','./ui-patch.js?v=0.18.0','./conscript-ui.js?v=0.18.0-r1','./reward-ui.js?v=0.18.0','./forge-ui.js?v=0.18.0','./encounter-ui.js?v=0.18.0-r1','./tactical-models.js?v=0.18.0','./living-ui.js?v=0.18.0-r1','./fieldworks-ui.js?v=0.18.0-r1','./assets/manifests/tactical-models.json?v=0.18.0','./assets/models/processed/sprites/tactical-models-atlas.json?v=0.18.0','./assets/models/processed/sprites/tactical-models-atlas.png?v=0.18.0','./manifest.webmanifest','./VERSION','../lane-warden/styles.css?v=0.18.0'];
async function fetchForCache(url){const r=await fetch(url,{cache:'reload'});if(!r.ok)throw new Error(url);if(url==='./index.html'){const text=await r.clone().text();if(!text.includes(SHELL_MARKER)||!text.includes('living-lanes.js')||!text.includes('movement-model.js')||!text.includes('fieldworks.js')||!text.includes('fieldworks-ui.js')||!text.includes('forge-engine.js')||!text.includes('forge-ui.js')||!text.includes('tactical-models.js')||!text.includes('living-ui.js'))throw new Error('stale-shell')}return r}
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(async cache=>{for(const url of ASSETS){const r=await fetchForCache(url);await cache.put(url,r)}}).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('lane-warden-prod-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('message',event=>{if(event.data?.type==='GET_BUILD'){const port=event.ports?.[0];if(port)port.postMessage({build:BUILD})}if(event.data?.type==='SKIP_WAITING')self.skipWaiting()});
async function fetchFreshNavigation(req){const first=await fetch(req,{cache:'no-store'});let text='';try{text=await first.clone().text()}catch{}if(text.includes(SHELL_MARKER)){caches.open(CACHE).then(c=>c.put('./index.html',first.clone()));return first}const u=new URL('./index.html',self.location.href);u.searchParams.set('lw-shell',BUILD);u.searchParams.set('t',Date.now());try{const fresh=await fetch(u.href,{cache:'reload'}),freshText=await fresh.clone().text();if(fresh.ok&&freshText.includes(SHELL_MARKER)&&freshText.includes('movement-model.js')&&freshText.includes('fieldworks.js')&&freshText.includes('fieldworks-ui.js')&&freshText.includes('forge-engine.js')&&freshText.includes('forge-ui.js')&&freshText.includes('tactical-models.js')){caches.open(CACHE).then(c=>c.put('./index.html',fresh.clone()));return fresh}}catch{}return first}
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.pathname.endsWith('/build.json')){event.respondWith(fetch(req,{cache:'no-store'}));return}if(req.mode==='navigate'){event.respondWith(fetchFreshNavigation(req).catch(()=>caches.match('./index.html')));return}event.respondWith(caches.match(req).then(hit=>hit||fetch(req).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(req,copy));return r})))})
