(() => {
  'use strict';
  const $=id=>document.getElementById(id),stage=$('stage'),ctx=stage.getContext('2d');
  const ui={hint:$('hint'),badge:$('badge'),loading:$('loading'),draw:$('drawControls'),demo:$('demoControls'),undo:$('undoBtn'),finish:$('finishBtn'),back:$('backBtn'),next:$('nextBtn'),play:$('playBtn'),restart:$('restartBtn'),count:$('stepCount'),title:$('stepTitle'),text:$('stepText'),speed:$('speedBtn'),info:$('infoBtn'),dialog:$('infoDialog'),closeInfo:$('closeInfo')};
  let dpr=1,W=0,H=0,points=[],mode='draw',solution=null,steps=[],stepIndex=0,playing=false,animToken=0,speed=1;
  const speeds=[.7,1,1.35],visual={foldStage:0,creases:0,cut:0,reveal:0};
  const V={add:(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]],sub:(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]],mul:(a,s)=>[a[0]*s,a[1]*s,a[2]*s],dot:(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2],cross:(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm:a=>{const l=Math.hypot(...a)||1;return a.map(x=>x/l)}};
  const I=()=>[[1,0,0],[0,1,0],[0,0,1]],M={apply:(A,v)=>[A[0][0]*v[0]+A[0][1]*v[1]+A[0][2]*v[2],A[1][0]*v[0]+A[1][1]*v[1]+A[1][2]*v[2],A[2][0]*v[0]+A[2][1]*v[1]+A[2][2]*v[2]],mul:(A,B)=>A.map(r=>B[0].map((_,j)=>r[0]*B[0][j]+r[1]*B[1][j]+r[2]*B[2][j])),T:A=>[[A[0][0],A[1][0],A[2][0]],[A[0][1],A[1][1],A[2][1]],[A[0][2],A[1][2],A[2][2]]]};
  const TI=()=>({R:I(),t:[0,0,0]}),TA=(T,p)=>V.add(M.apply(T.R,p),T.t),TC=(A,B)=>({R:M.mul(A.R,B.R),t:V.add(M.apply(A.R,B.t),A.t)}),TInv=A=>{const R=M.T(A.R);return{R,t:V.mul(M.apply(R,A.t),-1)}};
  function rotAxis(a,ang){const[x,y,z]=V.norm(a),c=Math.cos(ang),s=Math.sin(ang),q=1-c;return[[c+x*x*q,x*y*q-z*s,x*z*q+y*s],[y*x*q+z*s,c+y*y*q,y*z*q-x*s],[z*x*q-y*s,z*y*q+x*s,c+z*z*q]]}
  function rotLine(a,b,ang){const R=rotAxis(V.sub(b,a),ang);return{R,t:V.sub(a,M.apply(R,a))}}
  function resize(){const r=stage.parentElement.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;stage.width=Math.max(1,Math.round(W*dpr));stage.height=Math.max(1,Math.round(H*dpr));stage.style.width=W+'px';stage.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0);render()}
  new ResizeObserver(resize).observe(stage.parentElement);
  function paperRect(){const m=Math.max(24,Math.min(W,H)*.075);return{x:m,y:m+12,w:W-2*m,h:H-2*m-18}}
  function pointerPoint(e){const r=stage.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
  function insidePaper(p){const r=paperRect();return p.x>r.x+8&&p.x<r.x+r.w-8&&p.y>r.y+8&&p.y<r.y+r.h-8}
  const d2=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),orient=(a,b,c)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);
  function segIntersect(a,b,c,d){const o1=orient(a,b,c),o2=orient(a,b,d),o3=orient(c,d,a),o4=orient(c,d,b);return((o1>0&&o2<0)||(o1<0&&o2>0))&&((o3>0&&o4<0)||(o3<0&&o4>0))}
  function simplePolygon(p){const n=p.length;if(n<3)return false;for(let i=0;i<n;i++)for(let j=i+1;j<n;j++){if(Math.abs(i-j)<=1||(i===0&&j===n-1))continue;if(segIntersect(p[i],p[(i+1)%n],p[j],p[(j+1)%n]))return false}return true}
  stage.addEventListener('pointerup',e=>{if(mode!=='draw')return;const p=pointerPoint(e);if(!insidePaper(p)||(points.length&&d2(points.at(-1),p)<12))return;points.push(p);updateDrawUI();render()});
  ui.undo.onclick=()=>{points.pop();updateDrawUI();render()};ui.finish.onclick=finishShape;ui.restart.onclick=restart;ui.back.onclick=()=>goStep(stepIndex-1);ui.next.onclick=()=>goStep(stepIndex+1);ui.play.onclick=()=>playing?stopPlay():startPlay();ui.speed.onclick=()=>{speed=speeds[(speeds.indexOf(speed)+1)%speeds.length];ui.speed.textContent=(speed===1?'1':speed.toFixed(2).replace(/0$/,''))+'×'};ui.info.onclick=()=>ui.dialog.showModal();ui.closeInfo.onclick=()=>ui.dialog.close();
  function updateDrawUI(){ui.undo.disabled=!points.length;ui.finish.disabled=points.length<3;ui.hint.textContent=points.length===0?'Tap the paper to place your first vertex.':points.length<3?'Keep tapping to add vertices.':'Add vertices, then tap Finish shape.'}
  function restart(){animToken++;playing=false;points=[];solution=null;steps=[];stepIndex=0;mode='draw';Object.assign(visual,{foldStage:0,creases:0,cut:0,reveal:0});ui.draw.classList.remove('hidden');ui.demo.classList.add('hidden');ui.badge.classList.add('hidden');ui.hint.classList.remove('hidden');ui.loading.classList.add('hidden');updateDrawUI();render()}
  function toSolverPoints(pts){const r=paperRect(),sx=560/r.w,sy=420/r.h;return pts.map(p=>({x:80+(p.x-r.x)*sx,y:70+(r.y+r.h-p.y)*sy}))}
  async function finishShape(){if(points.length<3)return;if(!simplePolygon(points)){ui.hint.textContent='That outline crosses itself. Undo a point and try a simple polygon.';return}mode='busy';ui.loading.classList.remove('hidden');ui.hint.textContent='Building solver-derived fold packets…';await new Promise(r=>setTimeout(r,60));try{solution=solveWithMIT(points);buildSteps();mode='demo';ui.loading.classList.add('hidden');ui.draw.classList.add('hidden');ui.demo.classList.remove('hidden');ui.hint.classList.add('hidden');ui.badge.classList.remove('hidden');goStep(0,true)}catch(err){console.error(err);mode='draw';ui.loading.classList.add('hidden');ui.hint.classList.remove('hidden');ui.hint.textContent='This shape hit a geometry limitation. Try moving one vertex slightly and finish again.'}}
  function solveWithMIT(pts){if(typeof Point!=='function'||typeof foldAndCut!=='function'||typeof computeCorridors!=='function')throw Error('Geometry library did not load');const raw=toSolverPoints(pts),editor=raw.map(p=>new Point(p.x,p.y));editor.push(editor[0]);editor.push('marker');const seq=typeof removeMarkers==='function'?removeMarkers(editor):editor.slice(0,-1);const oldAlert=alert;let msg='';window.alert=m=>msg=String(m);let out;try{out=foldAndCut(seq)}finally{window.alert=oldAlert}if(msg)throw Error(msg);const CP=out[0];if(!CP||!CP.cPVs||!CP.cPEs||out[4])throw Error('No usable crease pattern');const corridorsRaw=computeCorridors(CP),index=new Map(CP.cPVs.map((v,i)=>[v,i])),edgeIndex=new Map(CP.cPEs.map((e,i)=>[e,i]));let fs;try{fs=foldedState(CP);fold(CP,fs[2],fs[3])}catch(e){throw Error('Could not compute final folded state')}
    const vertices=CP.cPVs.map((v,i)=>({id:i,x:v.x,y:v.y,fx:v.foldedPos?.x??v.x,fy:v.foldedPos?.y??v.y,type:v.type})),edges=CP.cPEs.map((e,i)=>({id:i,a:index.get(e.endpt1),b:index.get(e.endpt2),type:e.type,assignment:(e.assignment||'u').toLowerCase()})).filter(e=>Number.isInteger(e.a)&&Number.isInteger(e.b));
    const faces=[],faceByKey=new Map();function faceIds(df){const arr=Array.isArray(df?.[0])?df[0]:[],ids=[];for(const v of arr){const id=index.get(v);if(Number.isInteger(id)&&ids.at(-1)!==id)ids.push(id)}if(ids.length>2&&ids[0]===ids.at(-1))ids.pop();return ids}function getFaceId(df){const ids=faceIds(df);if(ids.length<3)return-1;const k=ids.slice().sort((a,b)=>a-b).join(',');if(!faceByKey.has(k)){faceByKey.set(k,faces.length);faces.push({id:faces.length,verts:ids})}return faceByKey.get(k)}
    const corridors=[];corridorsRaw.forEach((corr,ci)=>{const ids=corr.faces.map(getFaceId).filter(i=>i>=0);if(ids.length)corridors.push({id:ci,faceIds:ids,raw:corr})});if(!faces.length)throw Error('No paper faces');
    const ops=[],byRound=[];corridors.forEach(c=>{const cf=c.raw.faces;let round=0;for(let i=0;i<cf.length-1;i++){const eo=(cf[i][1]||[]).find(e=>(cf[i+1][1]||[]).includes(e));if(!eo)continue;const as=(eo.assignment||'u').toLowerCase();if(as!=='m'&&as!=='v')continue;const ei=edgeIndex.get(eo),stationary=c.faceIds[i],moving=c.faceIds.slice(i+1).filter(Number.isInteger);if(!Number.isInteger(ei)||!Number.isInteger(stationary)||!moving.length)continue;const op={id:ops.length,corridor:c.id,round:round++,edgeIndex:ei,stationary,moving,assignment:as,angle:as==='m'?-Math.PI:Math.PI};ops.push(op);(byRound[op.round]??=[]).push(op)}});if(!ops.length)throw Error('No solver fold packets');return prepare({vertices,edges,faces,corridors,ops,groups:byRound.filter(Boolean),targetPolygon:raw})}
  function edgeKind(e){if(e.type==='graph'||e.type==='quasiGraph')return'target';if(e.type==='boundary')return'paper';if(e.type==='skeleton'||e.type==='perp'||e.type==='quasiSkeleton')return'crease';return'other'}
  function basis(u,v,n){return[[u[0],v[0],n[0]],[u[1],v[1],n[1]],[u[2],v[2],n[2]]]}
  function rigidMap(face,vs){const ids=face.verts,p0=[vs[ids[0]].x,vs[ids[0]].y,0],q0=[vs[ids[0]].fx,vs[ids[0]].fy,0];let i1=1;while(i1<ids.length&&Math.hypot(vs[ids[i1]].x-p0[0],vs[ids[i1]].y-p0[1])<1e-6)i1++;if(i1>=ids.length)return TI();const p1=[vs[ids[i1]].x,vs[ids[i1]].y,0],q1=[vs[ids[i1]].fx,vs[ids[i1]].fy,0],us=V.norm(V.sub(p1,p0)),ut=V.norm(V.sub(q1,q0)),ns=[0,0,1],vsrc=V.cross(ns,us);let parity=1;for(let i=i1+1;i<ids.length;i++){const s=vs[ids[i]],src=(p1[0]-p0[0])*(s.y-p0[1])-(p1[1]-p0[1])*(s.x-p0[0]),tgt=(q1[0]-q0[0])*(s.fy-q0[1])-(q1[1]-q0[1])*(s.fx-q0[0]);if(Math.abs(src)>1e-5){parity=src*tgt<0?-1:1;break}}const nt=[0,0,parity],vt=V.cross(nt,ut),R=M.mul(basis(ut,vt,nt),M.T(basis(us,vsrc,ns)));return{R,t:V.sub(q0,M.apply(R,p0))}}
  function prepare(sol){sol.faces.forEach((f,i)=>{f.id=i;f.set=new Set(f.verts)});sol.edgeFaces=sol.edges.map(()=>[]);sol.edges.forEach((e,ei)=>sol.faces.forEach((f,fi)=>{if(f.set.has(e.a)&&f.set.has(e.b))sol.edgeFaces[ei].push(fi)}));sol.edgeOwner=sol.edgeFaces.map(a=>a[0]??0);sol.targetTransforms=sol.faces.map(f=>rigidMap(f,sol.vertices));const xs=sol.vertices.map(v=>v.x),ys=sol.vertices.map(v=>v.y);sol.bounds={minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys)};sol.center=[(sol.bounds.minX+sol.bounds.maxX)/2,(sol.bounds.minY+sol.bounds.maxY)/2,0];sol.fullTransforms=computeTransforms(sol,sol.groups.length);sol.sequenceError=seqError(sol);sol.cutLine=cutLine(sol,sol.fullTransforms);sol.badge=`corridor packets · ${sol.groups.length} fold${sol.groups.length===1?'':'s'}`;return sol}
  function applyOp(sol,Ts,op,t){if(t<=0)return;const e=sol.edges[op.edgeIndex],st=Ts[op.stationary]||TI(),a=TA(st,[sol.vertices[e.a].x,sol.vertices[e.a].y,0]),b=TA(st,[sol.vertices[e.b].x,sol.vertices[e.b].y,0]),H=rotLine(a,b,op.angle*t);for(const fi of op.moving)Ts[fi]=TC(H,Ts[fi]||TI())}
  function computeTransforms(sol,stage){const Ts=sol.faces.map(()=>TI());for(let g=0;g<sol.groups.length;g++){const t=Math.max(0,Math.min(1,stage-g));if(t<=0)break;for(const op of sol.groups[g])applyOp(sol,Ts,op,t);if(t<1)break}return Ts}
  function seqError(sol){const sim=sol.fullTransforms,tgt=sol.targetTransforms,G=TC(tgt[0],TInv(sim[0]));let sum=0,n=0;sol.faces.forEach((f,fi)=>f.verts.forEach(id=>{const p=[sol.vertices[id].x,sol.vertices[id].y,0],a=TA(TC(G,sim[fi]),p),b=TA(tgt[fi],p),d=V.sub(a,b);sum+=V.dot(d,d);n++}));return Math.sqrt(sum/Math.max(1,n))}
  function cutLine(sol,Ts){const pts=[];sol.edges.forEach((e,ei)=>{if(edgeKind(e)!=='target')return;const T=Ts[sol.edgeOwner[ei]]||TI();pts.push(TA(T,[sol.vertices[e.a].x,sol.vertices[e.a].y,0]),TA(T,[sol.vertices[e.b].x,sol.vertices[e.b].y,0]))});if(pts.length<2)return null;const c=pts.reduce((s,p)=>V.add(s,p),[0,0,0]).map(x=>x/pts.length);let xx=0,xy=0,yy=0;for(const p of pts){const x=p[0]-c[0],y=p[1]-c[1];xx+=x*x;xy+=x*y;yy+=y*y}const ang=.5*Math.atan2(2*xy,xx-yy),dir=[Math.cos(ang),Math.sin(ang),0];let mn=Infinity,mx=-Infinity,r=0;for(const p of pts){const d=V.sub(p,c),t=V.dot(d,dir),perp=d[0]*-dir[1]+d[1]*dir[0];mn=Math.min(mn,t);mx=Math.max(mx,t);r+=perp*perp}return{start:V.add(c,V.mul(dir,mn-35)),end:V.add(c,V.mul(dir,mx+35)),rms:Math.sqrt(r/pts.length)}}
  function buildSteps(){steps=[{title:'Your shape',text:'This is the straight-line cut pattern you drew.',foldStage:0,creases:0,cut:0,reveal:0,group:-1},{title:'Crease construction',text:'The theorem solver builds the straight-skeleton crease network and divides the paper into rigid faces.',foldStage:0,creases:1,cut:0,reveal:0,group:-1}];solution.groups.forEach((group,g)=>{const packets=group.length,faces=new Set(group.flatMap(op=>op.moving)).size;steps.push({title:packets>1?`Compound fold ${g+1}`:`Packet fold ${g+1}`,text:packets>1?`${packets} solver corridors collapse together. Each hinge carries its entire already-folded packet instead of moving a single face.`:`Fold the whole ${faces}-face packet around the solver-selected crease.`,foldStage:g+1,creases:1,cut:0,reveal:0,group:g})});steps.push({title:'One flat stack',text:'The solver-derived packet folds are complete and the target edges are gathered for the cut.',foldStage:solution.groups.length,creases:1,cut:0,reveal:0,group:-1},{title:'Make one straight cut',text:'The blade passes once through the folded stack along the shared cutting line.',foldStage:solution.groups.length,creases:1,cut:1,reveal:0,group:-1},{title:'Unfold the result',text:'Reverse the same packet folds. The one cut opens back out into the shape you drew.',foldStage:0,creases:0,cut:0,reveal:1,group:-1})}
  function goStep(i,instant=false){i=Math.max(0,Math.min(steps.length-1,i));stepIndex=i;const s=steps[i];updateStepUI();const end={foldStage:s.foldStage,creases:s.creases,cut:s.cut,reveal:s.reveal};if(instant){Object.assign(visual,end);render();return}animate({...visual},end,1050/speed)}
  function animate(start,end,dur){const token=++animToken,t0=performance.now();function f(now){if(token!==animToken)return;let t=Math.min(1,(now-t0)/dur);t=t*t*(3-2*t);for(const k in end)visual[k]=start[k]+(end[k]-start[k])*t;render();if(t<1)requestAnimationFrame(f)}requestAnimationFrame(f)}
  function updateStepUI(){const s=steps[stepIndex];ui.count.textContent=`Step ${stepIndex+1} of ${steps.length}`;ui.title.textContent=s.title;ui.text.textContent=s.text;ui.back.disabled=stepIndex===0;ui.next.disabled=stepIndex===steps.length-1;ui.badge.textContent=solution.badge}
  async function startPlay(){if(stepIndex===steps.length-1)goStep(0,true);playing=true;ui.play.textContent='Ⅱ';while(playing&&stepIndex<steps.length-1){await sleep(1450/speed);if(!playing)break;goStep(stepIndex+1);await sleep(950/speed)}if(stepIndex===steps.length-1)stopPlay()}
  function stopPlay(){playing=false;ui.play.textContent='▶'}const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  function project(p){const c=solution.center,d=V.sub(p,c),yaw=-.34,pitch=.72,cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),x=cy*d[0]-sy*d[1],y=sy*d[0]+cy*d[1],z=d[2],yy=cp*y-sp*z,zz=sp*y+cp*z,span=Math.max(solution.bounds.maxX-solution.bounds.minX,solution.bounds.maxY-solution.bounds.minY),scale=Math.min(W,H)*.72/Math.max(1,span),cam=850,persp=cam/(cam-zz);return{x:W/2+x*scale*persp,y:H*.53-yy*scale*persp,depth:zz}}
  function faceWorld(f,T){return f.verts.map(id=>TA(T,[solution.vertices[id].x,solution.vertices[id].y,0]))}
  function faceNormal(w){return w.length<3?[0,0,1]:V.norm(V.cross(V.sub(w[1],w[0]),V.sub(w[2],w[0])))}
  function edgeWorld(e,Ts){const T=Ts[solution.edgeOwner[e.id]]||TI();return[TA(T,[solution.vertices[e.a].x,solution.vertices[e.a].y,0]),TA(T,[solution.vertices[e.b].x,solution.vertices[e.b].y,0])]}
  function render(){if(!W||!H)return;ctx.clearRect(0,0,W,H);if(mode==='draw'||mode==='busy'||!solution){drawInput();return}draw3D()}
  function drawInput(){const r=paperRect();ctx.save();ctx.fillStyle='#fffdf7';ctx.shadowColor='rgba(58,45,27,.14)';ctx.shadowBlur=18;ctx.shadowOffsetY=8;ctx.beginPath();ctx.roundRect?ctx.roundRect(r.x,r.y,r.w,r.h,6):ctx.rect(r.x,r.y,r.w,r.h);ctx.fill();ctx.restore();if(!points.length)return;ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#28251f';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(let i=1;i<points.length;i++)ctx.lineTo(points[i].x,points[i].y);ctx.stroke();points.forEach((p,i)=>{ctx.beginPath();ctx.arc(p.x,p.y,i===0?6:5,0,Math.PI*2);ctx.fillStyle=i===0?'#bb3f31':'#28251f';ctx.fill()});ctx.restore()}
  function draw3D(){const Ts=computeTransforms(solution,visual.foldStage),draw=solution.faces.map((f,i)=>{const w=faceWorld(f,Ts[i]),avg=w.reduce((s,p)=>s+project(p).depth,0)/w.length,raise=w.reduce((s,p)=>s+Math.abs(p[2]),0)/w.length;return{f,i,w,avg,raise}}).sort((a,b)=>a.avg-b.avg);draw.forEach(o=>{if(o.raise<.2)return;const pp=o.w.map(p=>project([p[0],p[1],0]));ctx.save();ctx.globalAlpha=Math.min(.13,.025+o.raise/650);ctx.fillStyle='#51483d';ctx.beginPath();pp.forEach((p,i)=>i?ctx.lineTo(p.x+5,p.y+8):ctx.moveTo(p.x+5,p.y+8));ctx.closePath();ctx.fill();ctx.restore()});draw.forEach(o=>{const pp=o.w.map(project);ctx.save();ctx.beginPath();pp.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle=faceNormal(o.w)[2]>=0?'#fffdf7':'#f1e6d2';ctx.fill();ctx.strokeStyle='rgba(83,72,56,.22)';ctx.stroke();ctx.restore()});solution.edges.forEach(e=>{if(edgeKind(e)!=='target')return;const[a,b]=edgeWorld(e,Ts),pa=project(a),pb=project(b);ctx.save();ctx.strokeStyle='#25231f';ctx.lineWidth=3;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.stroke();ctx.restore()});if(visual.creases>.02){const s=steps[stepIndex]||{},active=s.group>=0?new Set(solution.groups[s.group].map(op=>op.edgeIndex)):new Set();solution.edges.forEach((e,ei)=>{if(edgeKind(e)!=='crease')return;const[a,b]=edgeWorld(e,Ts),pa=project(a),pb=project(b),on=active.has(ei);ctx.save();ctx.globalAlpha=Math.max(.15,visual.creases*(on?1:.48));ctx.strokeStyle=e.assignment==='m'?'#bd4a3d':e.assignment==='v'?'#3d718e':'#948c80';ctx.lineWidth=on?3.2:1.15;ctx.setLineDash(on?[]:[5,5]);ctx.beginPath();ctx.moveTo(pa.x,pa.y);ctx.lineTo(pb.x,pb.y);ctx.stroke();ctx.restore()})}if(visual.cut>.01&&solution.cutLine){const a=project(solution.cutLine.start),b=project(solution.cutLine.end),t=visual.cut,x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t;ctx.save();ctx.strokeStyle='rgba(187,63,49,.28)';ctx.lineWidth=9;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(x,y);ctx.stroke();ctx.strokeStyle='#8c261f';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(x,y);ctx.stroke();ctx.translate(x,y);ctx.rotate(Math.atan2(b.y-a.y,b.x-a.x));ctx.fillStyle='#25231f';ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(-18,-7);ctx.lineTo(-13,7);ctx.closePath();ctx.fill();ctx.restore()}if(visual.reveal>.01){ctx.save();ctx.globalAlpha=visual.reveal*.18;ctx.fillStyle='#bb3f31';ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);for(let i=1;i<points.length;i++)ctx.lineTo(points[i].x,points[i].y);ctx.closePath();ctx.fill();ctx.globalAlpha=visual.reveal;ctx.strokeStyle='#8c261f';ctx.lineWidth=4;ctx.stroke();ctx.restore()}}
  updateDrawUI();resize();
})();