(function(){
'use strict';
var KEY='ips-audio-v1',ctx=null,master=null,ambience=null,windSrc=null,noiseBuf=null,armed=false,lastPeg=0,activeVoices=0,MAX_VOICES=18,specialPegLast={};
function read(){try{return Object.assign({master:.75,sfx:.72,ambience:.12,muted:false},JSON.parse(localStorage.getItem(KEY)||'{}'));}catch(e){return{master:.75,sfx:.72,ambience:.12,muted:false};}}
var cfg=read();
function save(){try{localStorage.setItem(KEY,JSON.stringify(cfg));}catch(e){}apply();}
function apply(){if(master)master.gain.value=cfg.muted?0:cfg.master;if(ambience)ambience.gain.value=cfg.ambience;}
function buildNoise(){if(!ctx||noiseBuf)return;var len=Math.max(1,Math.floor(ctx.sampleRate*1.25)),d,i;noiseBuf=ctx.createBuffer(1,len,ctx.sampleRate);d=noiseBuf.getChannelData(0);for(i=0;i<len;i++)d[i]=Math.random()*2-1;}
function ensure(){if(ctx){if(ctx.state==='suspended')ctx.resume();return;}var AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;try{ctx=new AC({latencyHint:'interactive'});}catch(e){ctx=new AC();}master=ctx.createGain();master.gain.value=cfg.muted?0:cfg.master;master.connect(ctx.destination);ambience=ctx.createGain();ambience.gain.value=cfg.ambience;ambience.connect(master);buildNoise();startWind();}
window.__ipsAudioCore={ensure:ensure,getContext:function(){ensure();return ctx;},getMaster:function(){ensure();return master;},isMuted:function(){return !!cfg.muted;}};
function startWind(){if(!ctx||windSrc)return;buildNoise();if(!noiseBuf)return;var src=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();filter.type='lowpass';filter.frequency.value=420;gain.gain.value=.25;src.buffer=noiseBuf;src.loop=true;src.connect(filter);filter.connect(gain);gain.connect(ambience);src.start();windSrc=src;}
function env(g,t,a,d){var now=ctx.currentTime;g.gain.cancelScheduledValues(now);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(Math.max(.0002,t),now+a);g.gain.exponentialRampToValueAtTime(.0001,now+a+d);}
function takeVoice(node){if(activeVoices>=MAX_VOICES)return false;activeVoices++;node.onended=function(){activeVoices=Math.max(0,activeVoices-1);};return true;}
function tone(freq,dur,vol,type,slide){if(!ctx||cfg.muted||activeVoices>=MAX_VOICES)return;var o=ctx.createOscillator(),g=ctx.createGain();if(!takeVoice(o))return;o.type=type||'sine';o.frequency.setValueAtTime(freq,ctx.currentTime);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,slide),ctx.currentTime+dur);g.gain.value=0;o.connect(g);g.connect(master);env(g,vol*cfg.sfx,.006,Math.max(.018,dur-.006));o.start();o.stop(ctx.currentTime+dur+.02);}
function noise(dur,vol,high){if(!ctx||cfg.muted||activeVoices>=MAX_VOICES)return;buildNoise();if(!noiseBuf)return;var s=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain(),maxOffset=Math.max(0,noiseBuf.duration-dur-.01),offset=maxOffset?Math.random()*maxOffset:0;if(!takeVoice(s))return;f.type=high?'highpass':'bandpass';f.frequency.value=high?1800:650;f.Q.value=.7;s.buffer=noiseBuf;s.connect(f);f.connect(g);g.connect(master);env(g,vol*cfg.sfx,.003,Math.max(.018,dur));s.start(ctx.currentTime,offset,Math.min(dur,noiseBuf.duration-offset));}
function pegAllowed(type){var now=performance.now(),gap=type==='normal'?70:45,last;if(type==='normal'){if(now-lastPeg<gap)return false;lastPeg=now;return true;}last=specialPegLast[type]||0;if(now-last<gap)return false;specialPegLast[type]=now;return true;}
function sfx(name,d){ensure();if(!ctx||cfg.muted)return;switch(name){case'ballLaunch':tone(440,.05,.045,'triangle',320);break;case'slot':tone(d.value>=7?760:d.value<=2?340:520,d.value>=7?.08:.05,d.value>=7?.05:.028,'triangle',d.value>=7?460:300);break;case'peg':if(!pegAllowed(d.type||'normal'))return;if(d.type==='normal')tone(860,.022,.014,'sine');else if(d.type==='pin')tone(610,.035,.024,'triangle',430);else if(d.type==='fire'){tone(190,.065,.045,'sawtooth',120);noise(.045,.018,false);}else if(d.type==='split'){tone(720,.045,.038,'square');tone(980,.04,.025,'square');}else if(d.type==='pierce')tone(1250,.07,.032,'triangle',540);else if(d.type==='boom'){tone(90,.1,.065,'sine',45);noise(.085,.042,false);}else if(d.type==='chain'){tone(1300,.08,.035,'square',240);noise(.05,.018,true);}break;case'shot':if(d.kind==='boom'){tone(72,.14,.095,'sine',38);noise(.095,.055,false);}else if(d.kind==='chain'){tone(1150,.085,.055,'square',180);}else if(d.kind==='fire'){noise(.06,.04,true);tone(220,.07,.032,'sawtooth',100);}else{noise(.045,d.crit?.07:.043,true);tone(d.crit?120:155,.06,d.crit?.07:.043,'triangle',80);}break;case'enemyHit':tone(d.crit?260:190,.035,d.crit?.035:.018,'sine',110);break;case'enemyDeath':noise(.12,d.boss?.08:.04,false);tone(d.boss?70:100,.12,d.boss?.07:.034,'sawtooth',45);break;case'heroHit':tone(d.mode==='cannon'?55:85,.1,.07,'sawtooth',40);noise(.06,.04,false);break;case'heroDeath':tone(180,.65,.055,'sawtooth',45);setTimeout(function(){tone(90,.55,.04,'sine',35);},120);break;case'waveClear':tone(520,.09,.035,'triangle');setTimeout(function(){tone(680,.1,.038,'triangle');},80);break;case'loot':tone(380,.1,.035,'triangle');setTimeout(function(){tone(570,.13,.045,'triangle');},90);setTimeout(function(){tone(780,.18,.05,'sine');},180);break;case'upgrade':tone(520,.07,.032,'triangle');setTimeout(function(){tone(720,.085,.036,'triangle');},55);break;case'focus':tone(d.id?920:520,.04,.028,'sine');break;case'menu':tone(360,.03,.016,'triangle');break;case'reloadStart':tone(240,.035,.02,'square');break;case'reloadComplete':tone(420,.04,.024,'triangle');break;case'ammoLoad':tone(680,.035,.028,'triangle');break;case'lootChoice':tone(d.equip?620:420,.065,.032,'triangle');break;}}
['ballLaunch','slot','peg','shot','enemyHit','enemyDeath','heroHit','heroDeath','waveClear','loot','upgrade','focus','menu','reloadStart','reloadComplete','ammoLoad','lootChoice'].forEach(function(n){document.addEventListener('ips:'+n,function(e){sfx(n,e.detail||{});});});
function inject(){var modal=document.getElementById('settingsModal');if(!modal||modal.querySelector('.audio-settings'))return;var sections=modal.querySelector('.settings-section'),box=document.createElement('div');box.className='settings-section audio-settings';box.innerHTML='<h3>Audio</h3><p>Sound begins after your first tap. Peg sounds are voice-limited for smooth mobile play.</p><label>Master volume <input id="ipsMaster" type="range" min="0" max="1" step="0.05" value="'+cfg.master+'"></label><label>Sound effects <input id="ipsSfx" type="range" min="0" max="1" step="0.05" value="'+cfg.sfx+'"></label><label>Frontier ambience <input id="ipsAmbience" type="range" min="0" max="0.5" step="0.025" value="'+cfg.ambience+'"></label><button id="ipsMute" class="secondary" type="button">'+(cfg.muted?'UNMUTE AUDIO':'MUTE AUDIO')+'</button>';sections.parentNode.insertBefore(box,sections.nextSibling);function bind(id,key){var el=document.getElementById(id);el.addEventListener('input',function(){cfg[key]=Number(this.value);save();});}bind('ipsMaster','master');bind('ipsSfx','sfx');bind('ipsAmbience','ambience');document.getElementById('ipsMute').onclick=function(){cfg.muted=!cfg.muted;this.textContent=cfg.muted?'UNMUTE AUDIO':'MUTE AUDIO';save();ensure();};}
function arm(){if(armed)return;armed=true;ensure();}
document.addEventListener('pointerdown',arm,{once:true,capture:true});document.addEventListener('touchstart',arm,{once:true,capture:true,passive:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();
