(function(){
'use strict';
var KEY='ips-audio-v1',ctx=null,master=null,ambience=null,windSrc=null,armed=false,lastPeg=0;
function read(){try{return Object.assign({master:.75,sfx:.72,ambience:.12,muted:false},JSON.parse(localStorage.getItem(KEY)||'{}'));}catch(e){return{master:.75,sfx:.72,ambience:.12,muted:false};}}
var cfg=read();
function save(){try{localStorage.setItem(KEY,JSON.stringify(cfg));}catch(e){}apply();}
function apply(){if(master)master.gain.value=cfg.muted?0:cfg.master;if(ambience)ambience.gain.value=cfg.ambience;}
function ensure(){if(ctx){if(ctx.state==='suspended')ctx.resume();return;}var AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;ctx=new AC();master=ctx.createGain();master.gain.value=cfg.muted?0:cfg.master;master.connect(ctx.destination);ambience=ctx.createGain();ambience.gain.value=cfg.ambience;ambience.connect(master);startWind();}
function startWind(){if(!ctx||windSrc)return;var len=Math.floor(ctx.sampleRate*2),buf=ctx.createBuffer(1,len,ctx.sampleRate),d=buf.getChannelData(0),i;for(i=0;i<len;i++)d[i]=(Math.random()*2-1)*.25;var src=ctx.createBufferSource(),filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=420;src.buffer=buf;src.loop=true;src.connect(filter);filter.connect(ambience);src.start();windSrc=src;}
function env(g,t,a,d){var now=ctx.currentTime;g.gain.cancelScheduledValues(now);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(Math.max(.0002,t),now+a);g.gain.exponentialRampToValueAtTime(.0001,now+a+d);}
function tone(freq,dur,vol,type,slide){if(!ctx||cfg.muted)return;var o=ctx.createOscillator(),g=ctx.createGain();o.type=type||'sine';o.frequency.setValueAtTime(freq,ctx.currentTime);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,slide),ctx.currentTime+dur);g.gain.value=0;o.connect(g);g.connect(master);env(g,vol*cfg.sfx,.008,Math.max(.02,dur-.008));o.start();o.stop(ctx.currentTime+dur+.03);}
function noise(dur,vol,high){if(!ctx||cfg.muted)return;var len=Math.max(1,Math.floor(ctx.sampleRate*dur)),buf=ctx.createBuffer(1,len,ctx.sampleRate),d=buf.getChannelData(0),i;for(i=0;i<len;i++)d[i]=Math.random()*2-1;var s=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain();f.type=high?'highpass':'bandpass';f.frequency.value=high?1800:650;f.Q.value=.7;s.buffer=buf;s.connect(f);f.connect(g);g.connect(master);env(g,vol*cfg.sfx,.004,dur);s.start();}
function sfx(name,d){ensure();if(!ctx)return;switch(name){case'ballLaunch':tone(440,.055,.055,'triangle',320);break;case'peg':var now=performance.now();if(now-lastPeg<28)return;lastPeg=now;if(d.type==='normal')tone(860,.025,.018,'sine');else if(d.type==='fire'){tone(190,.08,.055,'sawtooth',120);noise(.06,.025,false);}else if(d.type==='split'){tone(720,.05,.05,'square');tone(980,.05,.035,'square');}else if(d.type==='pierce')tone(1250,.09,.04,'triangle',540);else if(d.type==='boom'){tone(90,.13,.085,'sine',45);noise(.12,.06,false);}else if(d.type==='chain'){tone(1300,.1,.045,'square',240);noise(.07,.025,true);}break;case'shot':if(d.kind==='boom'){tone(72,.16,.11,'sine',38);noise(.12,.07,false);}else if(d.kind==='chain'){tone(1150,.1,.065,'square',180);}else if(d.kind==='fire'){noise(.08,.055,true);tone(220,.08,.04,'sawtooth',100);}else{noise(.055,d.crit?.09:.055,true);tone(d.crit?120:155,.07,d.crit?.09:.055,'triangle',80);}break;case'enemyHit':tone(d.crit?260:190,.04,d.crit?.045:.025,'sine',110);break;case'enemyDeath':noise(.16,d.boss?.1:.055,false);tone(d.boss?70:100,.15,d.boss?.09:.045,'sawtooth',45);break;case'heroHit':tone(d.mode==='cannon'?55:85,.13,.09,'sawtooth',40);noise(.08,.055,false);break;case'heroDeath':tone(180,.8,.07,'sawtooth',45);setTimeout(function(){tone(90,.75,.05,'sine',35);},120);break;case'waveClear':tone(520,.1,.04,'triangle');setTimeout(function(){tone(680,.12,.045,'triangle');},80);break;case'loot':tone(380,.12,.04,'triangle');setTimeout(function(){tone(570,.16,.055,'triangle');},90);setTimeout(function(){tone(780,.22,.06,'sine');},180);break;case'upgrade':tone(520,.08,.04,'triangle');setTimeout(function(){tone(720,.1,.045,'triangle');},55);break;case'focus':tone(d.id?920:520,.045,.035,'sine');break;case'menu':tone(360,.035,.02,'triangle');break;case'reloadStart':tone(240,.04,.025,'square');break;case'reloadComplete':tone(420,.05,.03,'triangle');break;case'ammoLoad':tone(680,.04,.035,'triangle');break;case'lootChoice':tone(d.equip?620:420,.08,.04,'triangle');break;}}
['ballLaunch','peg','shot','enemyHit','enemyDeath','heroHit','heroDeath','waveClear','loot','upgrade','focus','menu','reloadStart','reloadComplete','ammoLoad','lootChoice'].forEach(function(n){document.addEventListener('ips:'+n,function(e){sfx(n,e.detail||{});});});
function inject(){var modal=document.getElementById('settingsModal');if(!modal||modal.querySelector('.audio-settings'))return;var sections=modal.querySelector('.settings-section'),box=document.createElement('div');box.className='settings-section audio-settings';box.innerHTML='<h3>Audio</h3><p>Sound begins after your first tap, as required by mobile browsers.</p><label>Master volume <input id="ipsMaster" type="range" min="0" max="1" step="0.05" value="'+cfg.master+'"></label><label>Sound effects <input id="ipsSfx" type="range" min="0" max="1" step="0.05" value="'+cfg.sfx+'"></label><label>Frontier ambience <input id="ipsAmbience" type="range" min="0" max="0.5" step="0.025" value="'+cfg.ambience+'"></label><button id="ipsMute" class="secondary" type="button">'+(cfg.muted?'UNMUTE AUDIO':'MUTE AUDIO')+'</button>';sections.parentNode.insertBefore(box,sections.nextSibling);function bind(id,key){var el=document.getElementById(id);el.addEventListener('input',function(){cfg[key]=Number(this.value);save();});}bind('ipsMaster','master');bind('ipsSfx','sfx');bind('ipsAmbience','ambience');document.getElementById('ipsMute').onclick=function(){cfg.muted=!cfg.muted;this.textContent=cfg.muted?'UNMUTE AUDIO':'MUTE AUDIO';save();ensure();};}
function arm(){if(armed)return;armed=true;ensure();}
document.addEventListener('pointerdown',arm,{once:true,capture:true});document.addEventListener('touchstart',arm,{once:true,capture:true,passive:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();
