(function(){
'use strict';
var META_KEY='ips-campaign-v1',CONTRACT_KEY='ips-contracts-v1',COMBAT_KEY='ips-combat-telemetry-v1';
var STAGES=[
  {name:'DUSTWATER GULCH',boss:'THE UNDERTAKER',className:'stage-dustwater'},
  {name:'BOOT HILL MIDNIGHT',boss:'MADAME DEAD-EYE',className:'stage-boothill'},
  {name:'BONE ORCHARD',boss:'BIG HANK',className:'stage-orchard'},
  {name:'CINDER JUNCTION',boss:'SHERIFF NEVERMORE',className:'stage-cinder'},
  {name:'HOLLOW MESA',boss:'THE LAST TRAIN',className:'stage-hollow'}
];
var GATES={gold:4,fire:3,split:5,pierce:8,boom:11,chain:16};
var currentWave=1,lastWave=1,waveStarted=Date.now(),waveDamage=0,reloadCount=0;
function $(id){return document.getElementById(id);}
function read(key,fallback){try{var r=localStorage.getItem(key);return r?JSON.parse(r):fallback;}catch(e){return fallback;}}
function write(key,v){try{localStorage.setItem(key,JSON.stringify(v));}catch(e){}}
function meta(){return read(META_KEY,{tutorialDone:false,stageIntros:{},unlockSeen:{},stageCaches:{}});}
function saveMeta(m){write(META_KEY,m);}
function snapshot(){return window.__ipsAPI&&window.__ipsAPI.snapshot?window.__ipsAPI.snapshot():{};}
function stageIndex(w){return Math.floor((Math.max(1,w)-1)/10)%STAGES.length;}
function applyStage(w){var combat=$('combat'),s=STAGES[stageIndex(w)],i;if(!combat)return;for(i=0;i<STAGES.length;i++)combat.classList.remove(STAGES[i].className);combat.classList.add(s.className);var sign=document.querySelector('.town-sign');if(sign)sign.textContent=s.name;var r=$('regionBadge');if(r)r.textContent='REGION '+(stageIndex(w)+1)+' · '+s.name;var boss=$('bossBadge');if(boss&&w%10===0)boss.textContent='BOSS · '+s.boss;}
function showToast(title,text){var box=$('campaignToast');if(!box)return;box.innerHTML='<b>'+title+'</b><span>'+text+'</span>';box.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(function(){box.classList.remove('show');},3600);}
function stageIntro(w){if(w%10!==1||w===1)return;var idx=stageIndex(w),m=meta(),key=String(idx);if(m.stageIntros[key])return;m.stageIntros[key]=1;saveMeta(m);showToast('NEW REGION',STAGES[idx].name+' · Boss: '+STAGES[idx].boss);}
function stageCache(prev,w){if(prev%10!==0||w!==prev+1)return;var cleared=Math.floor(prev/10),m=meta(),key=String(cleared);if(m.stageCaches[key])return;m.stageCaches[key]=1;saveMeta(m);var xp=75+cleared*55,coins=110+cleared*85;if(window.__ipsAPI)window.__ipsAPI.grant(xp,coins,'STAGE CACHE');showToast('FRONTIER SECURED','Stage '+cleared+' cache: +'+xp+' XP · +'+coins+' coins');}
function unlockNotice(w){var m=meta(),labels={fire:'INCENDIARY + FIRE PEG',gold:'GOLDEN AMMO',split:'SPLITTER PEG',pierce:'PIERCING',boom:'DYNAMITE',chain:'STORM / CHAIN LIGHTNING'},k;for(k in GATES){if(w>=GATES[k]&&!m.unlockSeen[k]){m.unlockSeen[k]=1;saveMeta(m);showToast('NEW BLUEPRINT',labels[k]+' unlocked');break;}}}
function applyLocks(){var s=snapshot(),highest=Number(s.highest||1),k,els,i,owned,unlocked,btn;for(k in GATES){els=document.querySelectorAll('[data-board="'+k+'"]');owned=Number(s[k]||0)>0;for(i=0;i<els.length;i++){btn=els[i];if(!owned&&highest<GATES[k]){btn.disabled=true;if(btn.textContent!=='UNLOCK WAVE '+GATES[k])btn.textContent='UNLOCK WAVE '+GATES[k];}}els=document.querySelectorAll('[data-ammo-unlock="'+k+'"]');unlocked=s.ammoUnlock&&Number(s.ammoUnlock[k]||0)>0;for(i=0;i<els.length;i++){btn=els[i];if(!unlocked&&highest<GATES[k]){btn.disabled=true;if(btn.textContent!=='UNLOCK WAVE '+GATES[k])btn.textContent='UNLOCK WAVE '+GATES[k];}}}}
function contracts(){var c=read(CONTRACT_KEY,null);if(c)return c;var s=snapshot(),h=Number(s.highest||1);c={waves:{progress:0,target:5,tier:1},reloads:{progress:0,target:10,tier:1},boss:{progress:0,target:1,tier:1},lastHighest:h};write(CONTRACT_KEY,c);return c;}
function contractReward(type,tier){var s=snapshot(),scale=1+Math.floor(Number(s.highest||1)/10)*.35;if(type==='waves')return{xp:Math.round((45+tier*15)*scale),coins:Math.round((65+tier*20)*scale)};if(type==='reloads')return{xp:Math.round((35+tier*12)*scale),coins:Math.round((55+tier*18)*scale)};return{xp:Math.round((90+tier*30)*scale),coins:Math.round((130+tier*40)*scale)};}
function contractName(type){return type==='waves'?'TRAILBLAZER':type==='reloads'?'KEEP IT HOT':'BOSS HUNTER';}
function contractDesc(type,c){return type==='waves'?'Clear '+c.target+' waves.':type==='reloads'?'Complete '+c.target+' reload cycles.':'Reach '+c.target+' boss loot screen.';}
function renderBounties(){var title=$('sheetTitle'),content=$('sheetContent');if(!title||!content)return;var c=contracts(),s=snapshot(),types=['waves','reloads','boss'],h='<div class="balance-card"><span>Repeatable frontier contracts</span><b>Highest Wave '+Number(s.highest||1)+'</b></div><div class="contract-grid">',i,t,x,r,pct,ready;for(i=0;i<types.length;i++){t=types[i];x=c[t];r=contractReward(t,x.tier);pct=Math.min(100,Math.round(x.progress/x.target*100));ready=x.progress>=x.target;h+='<article class="contract-card '+(ready?'ready':'')+'"><div class="contract-kicker">TIER '+x.tier+'</div><h3>'+contractName(t)+'</h3><p>'+contractDesc(t,x)+'</p><div class="contract-progress"><i style="width:'+pct+'%"></i></div><small>'+Math.min(x.progress,x.target)+' / '+x.target+'</small><div class="contract-reward">✦ '+r.xp+' · ● '+r.coins+'</div><button data-contract-claim="'+t+'" '+(ready?'':'disabled')+'>'+ (ready?'CLAIM CONTRACT':'IN PROGRESS') +'</button></article>';}h+='</div><div class="info-card"><h3>Campaign</h3><p>Five authored regions · checkpoints every five waves · bosses every ten. Offline patrols never clear bosses or claim contracts.</p></div>';title.textContent='Bounties';content.innerHTML=h;var claims=document.querySelectorAll('[data-contract-claim]');for(i=0;i<claims.length;i++)claims[i].onclick=function(){claimContract(this.getAttribute('data-contract-claim'));};}
function claimContract(type){var c=contracts(),x=c[type];if(!x||x.progress<x.target)return;var r=contractReward(type,x.tier);if(window.__ipsAPI)window.__ipsAPI.grant(r.xp,r.coins,'CONTRACT PAID');x.progress=0;x.tier++;if(type==='waves')x.target=Math.min(12,5+Math.floor(x.tier/2));if(type==='reloads')x.target=Math.min(24,10+x.tier*2);if(type==='boss')x.target=1;write(CONTRACT_KEY,c);renderBounties();showToast('BOUNTY PAID','+'+r.xp+' XP · +'+r.coins+' coins');}
function addContract(type,n){var c=contracts();c[type].progress+=n;write(CONTRACT_KEY,c);if($('sheetTitle')&&$('sheetTitle').textContent==='Bounties')renderBounties();}
function recordWave(prev,w){var t=read(COMBAT_KEY,{waves:[],totalDamage:0});var duration=Date.now()-waveStarted;if(prev!==w&&prev>0){t.waves.push({wave:prev,ms:duration,damage:Math.round(waveDamage),reloads:reloadCount,endedAt:Date.now()});if(t.waves.length>30)t.waves=t.waves.slice(-30);t.totalDamage=Number(t.totalDamage||0)+waveDamage;write(COMBAT_KEY,t);}waveStarted=Date.now();waveDamage=0;reloadCount=0;}
function parseWave(){var m=(($('waveBadge')&&$('waveBadge').textContent)||'').match(/(\d+)/);return m?Number(m[1]):1;}
function onWaveChange(w){var prev=currentWave;lastWave=prev;currentWave=w;recordWave(prev,w);if(w>prev)addContract('waves',w-prev);applyStage(w);stageCache(prev,w);stageIntro(w);unlockNotice(w);setTimeout(applyLocks,40);}
function observeWave(){var el=$('waveBadge');if(!el)return;currentWave=lastWave=parseWave();applyStage(currentWave);var o=new MutationObserver(function(){var w=parseWave();if(w!==currentWave)onWaveChange(w);});o.observe(el,{childList:true,subtree:true,characterData:true});}
function observeReload(){var el=$('reloadLabel');if(!el)return;var prev=el.textContent||'';var o=new MutationObserver(function(){var cur=el.textContent||'';if(cur.indexOf('RELOADING')===0&&prev.indexOf('RELOADING')!==0){reloadCount++;addContract('reloads',1);}prev=cur;});o.observe(el,{childList:true,subtree:true,characterData:true});}
function observeLoot(){var el=$('lootModal');if(!el)return;var hidden=el.classList.contains('hidden');var o=new MutationObserver(function(){var nowHidden=el.classList.contains('hidden');if(hidden&&!nowHidden)addContract('boss',1);hidden=nowHidden;});o.observe(el,{attributes:true,attributeFilter:['class']});}
function observeDamage(){var el=$('damageFeed');if(!el)return;var o=new MutationObserver(function(ms){var i,j,n,txt,v;for(i=0;i<ms.length;i++)for(j=0;j<ms[i].addedNodes.length;j++){n=ms[i].addedNodes[j];txt=(n.textContent||'').trim();if(/^\d+$/.test(txt)){v=Number(txt);waveDamage+=v;}}});o.observe(el,{childList:true});}
function observeSheets(){var content=$('sheetContent');if(content){var o=new MutationObserver(function(){setTimeout(applyLocks,0);});o.observe(content,{childList:true,subtree:true});}var b=document.querySelector('[data-sheet="bounties"]');if(b)b.addEventListener('click',function(){setTimeout(renderBounties,20);});}
function tutorial(){var m=meta(),modal=$('tutorialModal'),ret=$('returnModal');if(m.tutorialDone||!modal)return;if(ret&&!ret.classList.contains('hidden')){setTimeout(tutorial,1200);return;}var steps=[['THE BOARD IS YOUR GUN','Rounds fall automatically. Every peg can change the shot; the slot at the bottom sets its power.'],['BUILD THE CYLINDER','XP improves the Gunslinger. Bounty Coins improve the board and unlock ammunition. Special rounds and special pegs stack.'],['DEATH IS PROGRESS','Enemies advance during reloads. When they finally put you down, you keep your resources and restart from the latest secured checkpoint.']];var i=0;function show(){$('tutorialKicker').textContent='QUICK DRAW '+(i+1)+' / '+steps.length;$('tutorialTitle').textContent=steps[i][0];$('tutorialText').textContent=steps[i][1];$('tutorialNext').textContent=i===steps.length-1?'RIDE':'NEXT';}modal.classList.remove('hidden');show();$('tutorialNext').onclick=function(){i++;if(i>=steps.length){modal.classList.add('hidden');m.tutorialDone=true;saveMeta(m);}else show();};$('tutorialSkip').onclick=function(){modal.classList.add('hidden');m.tutorialDone=true;saveMeta(m);};}
function enhanceTelemetry(){var btn=$('devButton');if(!btn)return;btn.addEventListener('click',function(){setTimeout(function(){var root=$('telemetryContent');if(!root||root.querySelector('.combat-telemetry'))return;var t=read(COMBAT_KEY,{waves:[]}),arr=t.waves||[],last=arr.slice(-5),sumD=0,sumMs=0,i;for(i=0;i<last.length;i++){sumD+=Number(last[i].damage||0);sumMs+=Number(last[i].ms||0);}var dps=sumMs>0?sumD/(sumMs/1000):0,box=document.createElement('div');box.className='telemetry-section combat-telemetry';box.innerHTML='<h3>Observed combat output</h3><p><b>'+dps.toFixed(1)+' damage/sec</b> across the last '+last.length+' completed waves.</p><pre>'+last.map(function(x){return'Wave '+x.wave+' · '+(x.ms/1000).toFixed(1)+'s · '+x.damage+' dmg · '+x.reloads+' reloads';}).join('\n')+'</pre><small>Measurement only. v1.0 does not dynamically scale enemy HP from this value.</small>';root.appendChild(box);},40);});}
function boot(){observeWave();observeReload();observeLoot();observeDamage();observeSheets();enhanceTelemetry();setTimeout(function(){applyLocks();tutorial();unlockNotice(currentWave);},1000);}
window.addEventListener('DOMContentLoaded',function(){var tries=0,t=setInterval(function(){tries++;if(window.__ipsAPI){clearInterval(t);boot();}else if(tries>80)clearInterval(t);},100);});
})();
