(function(){
'use strict';
var BP_KEY='ips-blueprints-v1',TYPES=['concuss','shrapnel','poison'];
function $(id){return document.getElementById(id);}function readBp(){try{var v=JSON.parse(localStorage.getItem(BP_KEY)||'{}');v.bought=v.bought||{};v.seen=v.seen||{};v.history=v.history||{};return v;}catch(e){return{bought:{},seen:{},history:{}};}}function writeBp(v){try{localStorage.setItem(BP_KEY,JSON.stringify(v));}catch(e){}}
function show(msg){var box=$('campaignToast');if(!box)return;box.innerHTML='<b>DEV TEST KIT</b><span>'+msg+'</span>';box.classList.add('show');clearTimeout(show.t);show.t=setTimeout(function(){box.classList.remove('show');},3600);}
function prepare(){if(!window.__ipsAPI)return;var b=readBp(),now=Date.now(),i;for(i=0;i<TYPES.length;i++){b.bought[TYPES[i]]=1;b.seen[TYPES[i]]=1;b.history[TYPES[i]]=b.history[TYPES[i]]||{dev:true,at:now,wave:0,cost:0};}writeBp(b);window.__ipsAPI.grant(0,25000,'DEV TEST FUNDS');window.__ipsAPI.openSheet('ammo');setTimeout(function(){var buttons=[],btn,j;for(j=0;j<TYPES.length;j++){btn=document.querySelector('[data-ammo-unlock="'+TYPES[j]+'"]');if(btn)buttons.push(btn);}for(j=0;j<buttons.length;j++){buttons[j].disabled=false;buttons[j].click();}window.__ipsAPI.openSheet('ammo');show('Concussive, Shrapnel, and Poison Cloud are researched and unlocked. Load them into the cylinder from Ammo Lab.');},120);}
function inject(){var root=$('telemetryContent');if(!root||root.querySelector('.v17-dev-tools'))return;var box=document.createElement('div');box.className='telemetry-section v17-dev-tools';box.innerHTML='<h3>v1.7 specialty-round test</h3><p>Testing helper only. This bypasses blueprint milestones so the new ammunition can be exercised immediately.</p><button id="v17PrepareAmmo" type="button">PREPARE V1.7 AMMO TEST</button><button id="v17KillWave" type="button">CLEAR CURRENT WAVE</button>';root.appendChild(box);$('v17PrepareAmmo').onclick=prepare;$('v17KillWave').onclick=function(){if(window.__ipsDebug&&window.__ipsDebug.killWave)window.__ipsDebug.killWave();};}
function bind(){var d=$('devButton');if(d)d.addEventListener('click',function(){setTimeout(inject,60);});var c=$('telemetryContent');if(c)new MutationObserver(function(){if(!$('telemetryModal').classList.contains('hidden'))setTimeout(inject,0);}).observe(c,{childList:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
})();
