(function(){
'use strict';
var C=document.getElementById('board'),X=C&&C.getContext?C.getContext('2d'):null;
if(!C||!X)throw new Error('Canvas failed to initialize');
var S=[10,7,4,2,1,2,4,7,10],K='ips-v3';
function $(x){return document.getElementById(x)}
function R(a,b){return a+Math.random()*(b-a)}
function L(v,a,b){return Math.max(a,Math.min(b,v))}
function ID(){return 'i'+Date.now().toString(36)+Math.random().toString(36).slice(2)}
var save={xp:0,coins:0,checkpoint:1,power:0,reload:0,mag:0,slot:0,fire:0,split:0,pierce:0,boom:0,chain:0};
try{var z=JSON.parse(localStorage.getItem(K)||'{}'),q;for(q in save)if(typeof z[q]==='number')save[q]=z[q]}catch(e){}
function persist(){try{localStorage.setItem(K,JSON.stringify(save))}catch(e){}wallet()}
function st(){return{power:7*Math.pow(1.09,save.power),reload:Math.max(2200,6200*Math.pow(.92,save.reload)),mag:5+save.mag,slot:Math.pow(1.08,save.slot)}}
var G=null,B=[],P=[],last=performance.now(),sheet=null;
var types=[['Zombie Outlaw','🧟',30,8,3,9],['Ghoul Rustler','👺',24,7,2,10],['Ghost Gunhand','👻',28,10,3,11],['Troll Prospector','👹',48,13,4,14]];
function enemy(w,i,n){var boss=w%10===0,t=boss?['The Undertaker','💀',230,20,3,90]:types[(w+i)%types.length],sc=Math.pow(1.14,w-1),hp=t[2]*sc*(n>1?.82:1);return{id:ID(),name:t[0],icon:t[1],hp:hp,max:hp,dmg:t[3]*Math.pow(1.08,w-1),step:t[4],c:0,d:0,reward:Math.round(t[5]*(1+w*.1)),boss:boss}}
function living(){return G.enemies.filter(function(e){return e.hp>0})}
function newGame(){var a=st();G={wave:save.checkpoint,hp:100,max:100,enemies:[],state:'fire',mag:a.mag,launched:0,resolved:0,next:performance.now()+400,rs:0,re:0,kills:0};B=[];pegs();wave();$('deathModal').classList.add('hidden')}
function wave(){var n=G.wave%10===0?1:(G.wave<3?1:(G.wave<6?2:3)),i;G.enemies=[];for(i=0;i<n;i++)G.enemies.push(enemy(G.wave,i,n));G.state='fire';G.mag=st().mag;G.launched=0;G.resolved=0;G.next=performance.now()+450;enemies();hud();queue()}
function pegs(){P=[];var r,c,n,g,i,m={fire:[11,22,34,49],split:[17,30,45],pierce:[25,39,52],boom:[20,37,55],chain:[14,33,48]},k;for(r=0;r<8;r++){n=r%2?8:9;g=(C.width-56)/8;for(c=0;c<n;c++)P.push({x:28+c*g+(r%2?g/2:0),y:70+r*44,r:6,t:'n'})}for(k in m)for(i=0;i<save[k];i++)if(P[m[k][i%m[k].length]])P[m[k][i%m[k].length]].t=k}
function tag(b,t){if(b.tags.indexOf(t)<0)b.tags.push(t)}
function launch(src){if(B.length>30)return;var a=st(),b={x:src?src.x:C.width/2+R(-12,12),y:src?src.y:24,vx:src?-src.vx:R(-22,22),vy:src?-90:R(8,28),r:5.5,tags:src?src.tags.slice():[],mult:src?src.mult*.6:1,depth:src?src.depth+1:0,hit:{},life:18,done:false,p:a.power};if(!src&&Math.random()<.03)tag(b,'gold');B.push(b)}
function effect(b,p){var c;if(p.t==='n')return;if(p.t==='fire'||p.t==='pierce'||p.t==='boom'||p.t==='chain')tag(b,p.t);if(p.t==='split'&&b.depth<2&&b.tags.indexOf('lock')<0){tag(b,'lock');b.mult*=.6;c={x:b.x+1,y:b.y,vx:Math.abs(b.vx||55)+55,vy:b.vy,r:b.r,tags:b.tags.slice(),mult:b.mult,depth:b.depth+1,hit:{},life:b.life,done:false,p:b.p};b.vx=-Math.abs(b.vx||55)-55;b.depth++;B.push(c)}}
function phys(dt){var i,j,b,p,dx,dy,d2,m,d,nx,ny,dot,push;for(i=0;i<B.length;i++){b=B[i];if(b.done)continue;b.life-=dt;b.vy+=360*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<b.r+7){b.x=b.r+7;b.vx=Math.abs(b.vx)*.82}if(b.x>C.width-b.r-7){b.x=C.width-b.r-7;b.vx=-Math.abs(b.vx)*.82}for(j=0;j<P.length;j++){p=P[j];dx=b.x-p.x;dy=b.y-p.y;d2=dx*dx+dy*dy;m=b.r+p.r;if(d2<m*m&&d2>.01){d=Math.sqrt(d2);nx=dx/d;ny=dy/d;dot=b.vx*nx+b.vy*ny;if(dot<0){b.vx-=1.72*dot*nx;b.vy-=1.72*dot*ny;b.vx+=R(-14,14);b.vy*=.95;push=m-d+.2;b.x+=nx*push;b.y+=ny*push}if(!b.hit[j]){b.hit[j]=1;effect(b,p)}}}if(b.y>C.height-31||b.life<=0)resolve(b)}B=B.filter(function(x){return!x.done})}
function resolve(b){if(b.done)return;b.done=true;var v=S[L(Math.floor(b.x/(C.width/9)),0,8)],d=b.p*v*b.mult*st().slot,crit=Math.random()<.06;if(crit)d*=2;shoot(d,b.tags,crit);G.resolved++;queue()}
function hit(e,d,crit,gold,label){if(!e||e.hp<=0)return;var before=e.hp;e.hp-=d;pop(Math.round(d),crit,label||'');if(before>0&&e.hp<=0){var x=Math.round(e.reward*.75),c=e.reward*(gold?2:1);save.xp+=x;save.coins+=c;G.kills++;persist();if(gold)pop('2× BOUNTY',0,'GOLD')}enemies();if(!living().length)setTimeout(doneWave,350)}
function shoot(raw,t,crit){var a=living(),i,x,primary=raw;if(!a.length)return;if(t.indexOf('chain')>=0)primary*=.78;if(t.indexOf('fire')>=0)primary*=.72;hit(a[0],primary,crit,t.indexOf('gold')>=0,'');if(t.indexOf('pierce')>=0){x=raw*.65;for(i=1;i<Math.min(4,a.length);i++){hit(a[i],x,0,0,'PIERCE');x*=.65}}if(t.indexOf('boom')>=0)for(i=1;i<Math.min(3,a.length);i++)hit(a[i],raw*(i===1?.5:.25),0,0,'BOOM');if(t.indexOf('chain')>=0){x=raw*.55;for(i=1;i<Math.min(4,a.length);i++){hit(a[i],x,0,0,'⚡');x*=.62}}if(t.indexOf('fire')>=0)for(i=1;i<=3;i++)setTimeout(function(){var e=living();if(e.length)hit(e[0],raw*.13,0,0,'BURN')},i*650)}
function doneWave(){if(living().length)return;B=[];var w=G.wave;if(w%5===0)save.checkpoint=w+1;save.coins+=20+w*4;persist();G.wave++;wave()}
function reload(){var a=living(),i,e;for(i=0;i<a.length;i++){e=a[i];e.c++;if(e.c>=e.step){e.c=0;if(e.d<3)e.d++;else{G.hp-=e.dmg;pop('-'+Math.round(e.dmg)+' HP',0,'HIT')}}}if(G.hp<=0){G.state='dead';$('deathSummary').textContent='Reached Wave '+G.wave+' with '+G.kills+' kills. Checkpoint: '+save.checkpoint+'.';$('deathModal').classList.remove('hidden')}else{G.state='fire';G.mag=st().mag;G.launched=0;G.resolved=0;G.next=performance.now()+220}enemies();queue()}
function frame(now){var dt=Math.min(.033,(now-last)/1000);last=now;if(G&&G.state!=='dead'){phys(dt);if(G.state==='fire'&&now>=G.next&&G.launched<G.mag){launch(null);G.launched++;G.next=now+650;queue()}if(G.state==='fire'&&G.launched>=G.mag&&G.resolved>=G.mag&&!B.length&&living().length){G.state='reload';G.rs=now;G.re=now+st().reload}if(G.state==='reload'&&now>=G.re)reload()}draw();hud();requestAnimationFrame(frame)}
function draw(){var W=C.width,H=C.height,i,p,b,c,g=X.createLinearGradient(0,0,0,H);g.addColorStop(0,'#2b1d15');g.addColorStop(1,'#15100d');X.clearRect(0,0,W,H);X.fillStyle=g;X.fillRect(0,0,W,H);var co={n:'#9a7e5d',fire:'#ff6b2b',split:'#62d6c8',pierce:'#70cfe0',boom:'#e34d2e',chain:'#b67cff'};for(i=0;i<P.length;i++){p=P[i];c=co[p.t];X.beginPath();X.arc(p.x,p.y,p.t==='n'?5.3:7.2,0,Math.PI*2);X.fillStyle=c;X.shadowBlur=p.t==='n'?0:10;X.shadowColor=c;X.fill();X.shadowBlur=0;X.strokeStyle='#362116';X.stroke()}X.strokeStyle='rgba(220,174,99,.35)';for(i=1;i<9;i++){X.beginPath();X.moveTo(i*(W/9),H-57);X.lineTo(i*(W/9),H-4);X.stroke()}for(i=0;i<B.length;i++){b=B[i];c=b.tags.indexOf('chain')>=0?'#c89aff':b.tags.indexOf('boom')>=0?'#ff7348':b.tags.indexOf('fire')>=0?'#ff9a3d':b.tags.indexOf('pierce')>=0?'#7de3ed':b.tags.indexOf('gold')>=0?'#ffd957':'#e1bd73';X.beginPath();X.arc(b.x,b.y,b.r,0,Math.PI*2);X.fillStyle=c;X.shadowBlur=9;X.shadowColor=c;X.fill();X.shadowBlur=0;X.strokeStyle='#5b351d';X.stroke()}}
function wallet(){$('xpValue').textContent=Math.floor(save.xp);$('coinValue').textContent=Math.floor(save.coins)}
function slots(){$('slotLabels').innerHTML=S.map(function(v,i){return'<div class="slot-label '+(i===0||i===8?'edge':'')+'">'+v+'</div>'}).join('')}
function queue(){var q=$('bulletQueue'),i,s;q.innerHTML='';for(i=0;i<G.mag;i++){s=document.createElement('span');s.className='queue-bullet'+(i<G.launched?' spent':'');q.appendChild(s)}}
function hud(){if(!G)return;$('heroHpFill').style.width=L(G.hp/G.max*100,0,100)+'%';$('heroHpText').textContent=Math.max(0,Math.round(G.hp))+' / '+G.max;$('magText').textContent=Math.max(0,G.mag-G.launched)+' / '+G.mag;$('waveBadge').textContent='WAVE '+G.wave;$('bossBadge').textContent=G.wave%10===0?'BOSS':'BOSS IN '+(10-G.wave%10);if(G.state==='reload'){var p=L((performance.now()-G.rs)/(G.re-G.rs),0,1);$('reloadFill').style.width=p*100+'%';$('reloadLabel').textContent='RELOADING '+(Math.max(0,G.re-performance.now())/1000).toFixed(1)+'s'}else{$('reloadFill').style.width='0%';$('reloadLabel').textContent=G.state==='dead'?'DOWN':'FIRING'}}
function enemies(){var l=$('enemyLane'),a=living(),i,e,d;l.innerHTML='';for(i=0;i<a.length;i++){e=a[i];d=document.createElement('div');d.className='enemy'+(e.boss?' boss':'');d.style.transform='translateX('+(-e.d*13)+'px)';d.innerHTML='<div class="unit-figure">'+e.icon+'</div><div class="enemy-name">'+e.name+'</div><div class="hp-track"><div class="hp-fill" style="width:'+L(e.hp/e.max*100,0,100)+'%"></div></div><div class="unit-meta"><span>'+Math.max(0,Math.round(e.hp))+' HP</span><span>'+['FAR','MID','NEAR','COVER'][e.d]+'</span></div>';l.appendChild(d)}}
function pop(v,crit,label){var d=document.createElement('div');d.className='damage-number'+(crit?' crit':'')+(label?' effect':'');d.style.right=R(12,42)+'%';d.style.top=R(35,62)+'%';d.textContent=(crit?'CRIT ':'')+v;$('damageFeed').appendChild(d);setTimeout(function(){if(d.parentNode)d.parentNode.removeChild(d)},800)}
function cost(base,rank){return Math.round(base*Math.pow(1.7,rank))}
function open(name){sheet=name;$('sheet').classList.add('open');$('sheet').setAttribute('aria-hidden','false');var t=$('sheetTitle'),c=$('sheetContent'),h='';if(name==='hero'){t.textContent='Gunslinger';[['power','High Caliber','Bullet damage',40],['reload','Quick Hands','Reload speed',55],['mag','Deep Pockets','Bullets per reload',100]].forEach(function(a){h+='<article class="upgrade-card"><h3>'+a[1]+'</h3><p>'+a[2]+'</p><button data-u="'+a[0]+'">✦ '+cost(a[3],save[a[0]])+'</button></article>'});c.innerHTML='<div class="balance-card">✦ '+save.xp+' XP</div><div class="upgrade-grid">'+h+'</div>'}else if(name==='board'){t.textContent='Pachinko Board';[['slot','Sharpen Slots',50],['fire','Fire Peg',90],['split','Splitter Peg',120],['pierce','Piercing Peg',150],['boom','Dynamite Peg',190],['chain','Storm Peg',240]].forEach(function(a){h+='<article class="upgrade-card"><h3>'+a[1]+'</h3><button data-b="'+a[0]+'">🪙 '+cost(a[2],save[a[0]])+'</button></article>'});c.innerHTML='<div class="balance-card">🪙 '+save.coins+' coins</div><div class="upgrade-grid">'+h+'</div>'}else if(name==='ammo'){t.textContent='Ammo Lab';c.innerHTML='<div class="info-card"><h3>🩵 Piercing</h3><p>100% → 65% → 42% → 27%.</p><h3>💥 Explosive</h3><p>100% / 50% / 25% splash.</p><h3>⚡ Chain Lightning</h3><p>Lower damage across many enemies.</p></div>'}else{t.textContent=name==='gear'?'Gear':'Bounties';c.innerHTML='<div class="info-card"><p>'+ (name==='gear'?'Boss gear drops arrive in the next build.':'Checkpoint: Wave '+save.checkpoint) +'</p></div>'}bind()}
function bind(){var a=document.querySelectorAll('[data-u]'),i;for(i=0;i<a.length;i++)a[i].onclick=function(){var k=this.getAttribute('data-u'),base=k==='power'?40:k==='reload'?55:100,n=cost(base,save[k]);if(save.xp<n)return;save.xp-=n;save[k]++;persist();open('hero')};a=document.querySelectorAll('[data-b]');for(i=0;i<a.length;i++)a[i].onclick=function(){var k=this.getAttribute('data-b'),base={slot:50,fire:90,split:120,pierce:150,boom:190,chain:240}[k],n=cost(base,save[k]);if(save.coins<n)return;save.coins-=n;save[k]++;persist();pegs();open('board')}}
var nav=document.querySelectorAll('.dock button'),i;for(i=0;i<nav.length;i++)nav[i].onclick=function(){open(this.getAttribute('data-sheet'))};$('closeSheet').onclick=function(){$('sheet').classList.remove('open')};$('rideAgain').onclick=newGame;$('deathHero').onclick=function(){$('deathModal').classList.add('hidden');open('hero')};$('deathBoard').onclick=function(){$('deathModal').classList.add('hidden');open('board')};$('equipNew').onclick=$('sellNew').onclick=function(){$('lootModal').classList.add('hidden')};
slots();wallet();newGame();window.__IPS_BOOTED__=true;requestAnimationFrame(frame);
})();