const canvas=document.getElementById('board'),ctx=canvas.getContext('2d');
const SLOTS=[10,7,4,2,1,2,4,7,10],KEY='idle-pachinko-shootout-v01';
const $=id=>document.getElementById(id),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),chance=p=>Math.random()<p;
const HERO={power:['High Caliber','+8% base weapon power per rank.',40,1.55],crit:['Deadeye','+2% critical chance per rank.',50,1.6],critDamage:['Mean Streak','+15% critical damage per rank.',65,1.6],reload:['Quick Hands','-5% reload time per rank.',55,1.65],magazine:['Deep Pockets','+1 bullet per rank.',110,2],health:['Grit','+15 max HP per rank.',45,1.55]};
const BOARD={slot:['Sharpen Slots','+8% damage from every landing slot.',50,1.55],fire:['Fire Peg','Burning shot: reduced impact, then 3 damage ticks.',90,1.8],splitter:['Splitter Peg','Splits a bullet into two 60% branches.',120,1.9],pierce:['Piercing Peg','Hits a line of enemies with diminishing damage.',150,1.9],explosive:['Dynamite Peg','Splash damage falls off across nearby enemies.',190,1.95],chain:['Storm Peg','Lower impact, then diminishing lightning jumps.',240,2]};
const GEAR=[{name:'Service Revolver',rarity:'Common',power:1,crit:0,reload:0},{name:'Ember Colt',rarity:'Rare',power:1.18,crit:.03,reload:0,fireBonus:.05},{name:'Marshal’s Vengeance',rarity:'Legendary',power:1.35,crit:.05,reload:.08},{name:'The Widowmaker',rarity:'Mythic',power:1.42,crit:.02,reload:.03,ricochet:.3}];
const freshSave=()=>({xp:0,coins:0,checkpoint:1,highestWave:1,heroRanks:Object.fromEntries(Object.keys(HERO).map(k=>[k,0])),boardRanks:Object.fromEntries(Object.keys(BOARD).map(k=>[k,0])),gearIndex:0});
let save;try{save={...freshSave(),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{save=freshSave()}
save.heroRanks={...freshSave().heroRanks,...save.heroRanks};save.boardRanks={...freshSave().boardRanks,...save.boardRanks};
let state,balls=[],pegs=[],last=performance.now(),sheetOpen=null,dmgWindow=[];
function persist(){localStorage.setItem(KEY,JSON.stringify(save));wallet()}
function stats(){const h=save.heroRanks,g=GEAR[save.gearIndex]||GEAR[0];return{maxHp:100+h.health*15,power:7*Math.pow(1.08,h.power)*g.power,crit:clamp(.05+h.crit*.02+(g.crit||0),0,.72),critMult:2+h.critDamage*.15,reload:Math.max(2500,8000*Math.pow(.95,h.reload)*(1-(g.reload||0))),mag:5+h.magazine,slotMult:Math.pow(1.08,save.boardRanks.slot),fireBonus:g.fireBonus||0,ricochet:g.ricochet||0}}
function newState(){const s=stats();return{wave:save.checkpoint,hp:s.maxHp,maxHp:s.maxHp,enemies:[],status:'firing',mag:s.mag,launched:0,resolved:0,nextLaunch:performance.now()+600,reloadStart:0,reloadEnd:0,kills:0,runXp:0,runCoins:0,lootPause:false}}
const enemyTypes=[['Zombie Outlaw','🧟',28,8,3,8],['Ghoul Rustler','👺',21,7,2,9],['Ghost Gunhand','👻',24,10,3,10],['Troll Prospector','👹',44,13,4,13]];
function makeEnemy(wave,i,count){const boss=wave%10===0,elite=wave%5===0&&!boss,scale=Math.pow(1.15,wave-1);let t=enemyTypes[(wave+i)%enemyTypes.length];if(boss)t=['The Undertaker','💀',210,20,3,85];const m=boss?1+(wave/10-1)*.55:elite?1.75:1,hp=t[2]*scale*m*(count>1?.82:1);return{id:crypto.randomUUID(),name:t[0],icon:t[1],maxHp:hp,hp,damage:t[3]*Math.pow(1.1,wave-1)*(elite?1.2:1),advanceEvery:Math.max(1,t[4]-Math.floor(wave/15)),advanceCounter:0,distance:0,reward:Math.round(t[5]*(1+wave*.12)*(elite?1.8:1)),boss,elite}}
function spawnWave(){state.status='firing';state.launched=state.resolved=0;state.mag=stats().mag;state.nextLaunch=performance.now()+850;const boss=state.wave%10===0,count=boss?1:state.wave<3?1:state.wave<6?2:3;state.enemies=Array.from({length:count},(_,i)=>makeEnemy(state.wave,i,count));renderEnemies();hud();queue()}
function buildPegs(){pegs=[];const W=canvas.width;for(let r=0;r<8;r++){const cols=r%2?8:9,gap=(W-56)/8;for(let c=0;c<cols;c++)pegs.push({x:28+c*gap+(r%2?gap/2:0),y:70+r*44,r:6,type:'normal'})}const spots={fire:[11,22,34,49,57],splitter:[17,30,45,53],pierce:[25,39,52,60],explosive:[20,37,55],chain:[14,33,48]};for(const type of Object.keys(spots))for(let i=0;i<save.boardRanks[type];i++){const a=spots[type];pegs[a[i%a.length]].type=type}}
function reset(){balls=[];state=newState();buildPegs();spawnWave();$('deathModal').classList.add('hidden')}
function launch(parent){if(balls.length>28)return;const golden=parent?parent.tags.has('gold'):chance(.03),b={id:crypto.randomUUID(),x:parent?parent.x:canvas.width/2+rnd(-13,13),y:parent?parent.y:30,vx:parent?-parent.vx*rnd(.65,1.05):rnd(-18,18),vy:parent?-95:rnd(10,30),r:5.5,tags:parent?new Set(parent.tags):new Set(golden?['gold']:[]),mult:parent?parent.mult*.6:1,splitDepth:parent?parent.splitDepth+1:0,hit:new Set(),ttl:18,resolved:false,power:stats().power};balls.push(b)}
function pegEffect(b,p){if(p.type==='normal')return;if(p.type==='fire'||p.type==='pierce'||p.type==='explosive'||p.type==='chain')b.tags.add(p.type);if(p.type==='splitter'&&b.splitDepth<2&&!b.tags.has('splitLock')){b.tags.add('splitLock');b.mult*=.6;const c={...b,id:crypto.randomUUID(),tags:new Set(b.tags),hit:new Set(b.hit),vx:Math.abs(b.vx||55)+55,x:b.x+1,splitDepth:b.splitDepth+1};b.vx=-Math.abs(b.vx||55)-55;b.splitDepth++;balls.push(c)}}
function physics(dt){for(const b of balls){if(b.resolved)continue;b.ttl-=dt;b.vy+=360*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<b.r+7){b.x=b.r+7;b.vx=Math.abs(b.vx)*.82}if(b.x>canvas.width-b.r-7){b.x=canvas.width-b.r-7;b.vx=-Math.abs(b.vx)*.82}for(let i=0;i<pegs.length;i++){const p=pegs[i],dx=b.x-p.x,dy=b.y-p.y,d2=dx*dx+dy*dy,min=b.r+p.r;if(d2<min*min&&d2>.01){const d=Math.sqrt(d2),nx=dx/d,ny=dy/d,dot=b.vx*nx+b.vy*ny;if(dot<0){b.vx-=1.72*dot*nx;b.vy-=1.72*dot*ny;b.vx+=rnd(-14,14);b.vy*=.95;const push=min-d+.2;b.x+=nx*push;b.y+=ny*push}if(!b.hit.has(i)){b.hit.add(i);pegEffect(b,p)}}}if(b.y>canvas.height-31||b.ttl<=0)resolve(b)}balls=balls.filter(b=>!b.resolved)}
function living(){return state.enemies.filter(e=>e.hp>0)}
function resolve(b){if(b.resolved)return;b.resolved=true;const slot=clamp(Math.floor(b.x/(canvas.width/SLOTS.length)),0,8),v=SLOTS[slot],s=stats();let d=b.power*v*b.mult*s.slotMult,crit=chance(s.crit);if(crit)d*=s.critMult;shoot(d,b.tags,crit);state.resolved++;queue()}
function shoot(raw,tags,crit){let es=living();if(!es.length)return;const s=stats();let primary=raw;if(tags.has('chain'))primary*=.78;if(tags.has('fire'))primary*=.72;damage(es[0],primary,crit,tags.has('gold'));let total=primary;if(tags.has('pierce')){let x=raw*.65;for(let i=1;i<Math.min(4,es.length);i++){damage(es[i],x,false,false,'PIERCE');total+=x;x*=.65}}if(tags.has('explosive'))for(let i=1;i<Math.min(3,es.length);i++){const x=raw*(i===1?.5:.25);damage(es[i],x,false,false,'BOOM');total+=x}if(tags.has('chain')){let x=raw*.55;for(let i=1;i<Math.min(4,es.length);i++){damage(es[i],x,false,false,'⚡ CHAIN');total+=x;x*=.62}}if(tags.has('fire')){const burn=raw*(.13+s.fireBonus);for(let t=1;t<=3;t++)setTimeout(()=>{const target=living()[0];if(target)damage(target,burn,false,false,'BURN')},t*720)}if(s.ricochet&&crit)for(let i=1;i<es.length;i++)damage(es[i],raw*s.ricochet,false,false,'RICOCHET');dmgWindow.push({t:performance.now(),d:total});dmgWindow=dmgWindow.filter(x=>performance.now()-x.t<10000)}
function damage(e,n,crit=false,gold=false,effect=''){if(!e||e.hp<=0)return;const before=e.hp;e.hp-=n;pop(Math.round(n),crit,effect);if(before>0&&e.hp<=0){const mult=gold?2:1,xp=Math.round(e.reward*.75),coins=e.reward*mult;save.xp+=xp;save.coins+=coins;state.runXp+=xp;state.runCoins+=coins;state.kills++;persist();if(gold)pop('2× BOUNTY',false,'GOLD')}renderEnemies();if(!living().length)setTimeout(finishWave,420)}
function finishWave(){if(state.lootPause||living().length)return;balls=[];state.resolved=state.mag;const done=state.wave;save.highestWave=Math.max(save.highestWave,done+1);if(done%5===0)save.checkpoint=done+1;const bonus=20+done*4;save.coins+=bonus;state.runCoins+=bonus;persist();if(done%10===0){state.lootPause=true;showLoot();return}state.wave++;spawnWave()}
function reloadDone(){for(const e of living()){e.advanceCounter++;if(e.advanceCounter>=e.advanceEvery){e.advanceCounter=0;if(e.distance<3)e.distance++;else hitHero(e.damage)}}renderEnemies();state.status='firing';state.launched=state.resolved=0;state.mag=stats().mag;state.nextLaunch=performance.now()+250;queue()}
function hitHero(n){state.hp-=n;pop(`-${Math.round(n)} HP`,false,'HIT');hud();if(state.hp<=0)die()}
function die(){state.status='dead';balls=[];$('deathSummary').textContent=`You reached Wave ${state.wave}, killed ${state.kills} enemies, and banked ${state.runXp} XP + ${state.runCoins} coins. Your checkpoint is Wave ${save.checkpoint}.`;$('deathModal').classList.remove('hidden')}
function tick(now){const dt=Math.min(.033,(now-last)/1000);last=now;if(state&&state.status!=='dead'&&!state.lootPause){physics(dt);if(state.status==='firing'&&now>=state.nextLaunch&&state.launched<state.mag){launch();state.launched++;state.nextLaunch=now+650;queue()}if(state.status==='firing'&&state.launched>=state.mag&&state.resolved>=state.mag&&!balls.length&&living().length){state.status='reloading';state.reloadStart=now;state.reloadEnd=now+stats().reload}if(state.status==='reloading'&&now>=state.reloadEnd)reloadDone()}draw();hud();requestAnimationFrame(tick)}
function draw(){const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#2b1d15');g.addColorStop(1,'#15100d');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.strokeStyle='rgba(232,169,76,.16)';ctx.lineWidth=2;ctx.strokeRect(6,6,W-12,H-12);const colors={normal:'#9a7e5d',fire:'#ff6b2b',splitter:'#62d6c8',pierce:'#70cfe0',explosive:'#e34d2e',chain:'#b67cff'},letters={fire:'F',splitter:'×2',pierce:'P',explosive:'D',chain:'⚡'};for(const p of pegs){const c=colors[p.type];ctx.beginPath();ctx.arc(p.x,p.y,p.type==='normal'?5.3:7.2,0,Math.PI*2);ctx.fillStyle=c;ctx.shadowBlur=p.type==='normal'?0:12;ctx.shadowColor=c;ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#362116';ctx.stroke();if(p.type!=='normal'){ctx.fillStyle='#1d120d';ctx.font='bold 7px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(letters[p.type],p.x,p.y+.5)}}const sw=W/9;ctx.strokeStyle='rgba(220,174,99,.35)';for(let i=1;i<9;i++){ctx.beginPath();ctx.moveTo(i*sw,H-57);ctx.lineTo(i*sw,H-4);ctx.stroke()}for(const b of balls){const has=t=>b.tags.has(t),c=has('chain')?'#c89aff':has('explosive')?'#ff7348':has('fire')?'#ff9a3d':has('pierce')?'#7de3ed':has('gold')?'#ffd957':'#e1bd73';ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fillStyle=c;ctx.shadowBlur=10;ctx.shadowColor=c;ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#5b351d';ctx.stroke()}}
function wallet(){$('xpValue').textContent=Math.floor(save.xp);$('coinValue').textContent=Math.floor(save.coins)}
function queue(){const q=$('bulletQueue');q.innerHTML='';const n=state?.mag||stats().mag;for(let i=0;i<n;i++){const s=document.createElement('span');s.className='queue-bullet'+(i<state.launched?' spent':'');q.appendChild(s)}}
function hud(){if(!state)return;$('heroHpFill').style.width=clamp(state.hp/state.maxHp*100,0,100)+'%';$('heroHpText').textContent=`${Math.max(0,Math.round(state.hp))} / ${Math.round(state.maxHp)}`;$('magText').textContent=`${Math.max(0,state.mag-state.launched)} / ${state.mag}`;$('waveBadge').textContent=`WAVE ${state.wave}`;$('bossBadge').textContent=state.wave%10===0?'BOSS':'BOSS IN '+(10-state.wave%10);if(state.status==='reloading'){const p=clamp((performance.now()-state.reloadStart)/(state.reloadEnd-state.reloadStart),0,1);$('reloadFill').style.width=p*100+'%';$('reloadLabel').textContent=`RELOADING ${(Math.max(0,state.reloadEnd-performance.now())/1000).toFixed(1)}s`}else{$('reloadFill').style.width='0%';$('reloadLabel').textContent=state.status==='dead'?'DOWN':'FIRING'}}
function renderEnemies(){const lane=$('enemyLane');lane.innerHTML='';for(const e of state.enemies.filter(x=>x.hp>0)){const d=document.createElement('div');d.className='enemy'+(e.boss?' boss':'');d.style.transform=`translateX(${-e.distance*13}px)`;d.innerHTML=`<div class="unit-figure">${e.icon}</div><div class="enemy-name">${e.name}</div><div class="hp-track"><div class="hp-fill" style="width:${clamp(e.hp/e.maxHp*100,0,100)}%"></div></div><div class="unit-meta"><span>${Math.max(0,Math.round(e.hp))} HP</span><span>${['FAR','MID','NEAR','COVER'][e.distance]}</span></div>`;lane.appendChild(d)}}
function pop(v,crit=false,effect=''){const d=document.createElement('div');d.className='damage-number'+(crit?' crit':'')+(effect?' effect':'');d.style.right=rnd(12,42)+'%';d.style.top=rnd(35,62)+'%';d.textContent=typeof v==='number'?(crit?`CRIT ${v}`:`${v}`):v;$('damageFeed').appendChild(d);setTimeout(()=>d.remove(),850)}
function renderSlots(){$('slotLabels').innerHTML=SLOTS.map((v,i)=>`<div class="slot-label ${i===0||i===8?'edge':''}">${v}</div>`).join('')}
const cost=(d,r)=>Math.round(d[2]*Math.pow(d[3],r));
function card(k,d,r,currency){const n=cost(d,r),ok=(currency==='xp'?save.xp:save.coins)>=n;return `<article class="upgrade-card"><h3>${d[0]}</h3><div class="rank">RANK ${r}</div><p>${d[1]}</p><button class="buy-btn" data-buy="${currency}:${k}" ${ok?'':'disabled'}>${currency==='xp'?'✦':'🪙'} ${n}</button></article>`}
function openSheet(name){sheetOpen=name;$('sheet').classList.add('open');$('sheet').setAttribute('aria-hidden','false');const c=$('sheetContent'),title=$('sheetTitle');if(name==='hero'){title.textContent='Gunslinger';c.innerHTML=`<div class="balance-card"><span>Permanent hero upgrades</span><b>✦ ${Math.floor(save.xp)} XP</b></div><div class="upgrade-grid">${Object.entries(HERO).map(([k,d])=>card(k,d,save.heroRanks[k],'xp')).join('')}</div>`}if(name==='board'){title.textContent='Pachinko Board';c.innerHTML=`<div class="balance-card"><span>Board, peg & damage upgrades</span><b>🪙 ${Math.floor(save.coins)}</b></div><div class="upgrade-grid">${Object.entries(BOARD).map(([k,d])=>card(k,d,save.boardRanks[k],'coins')).join('')}</div>`}if(name==='ammo'){title.textContent='Ammo Lab';c.innerHTML=`<div class="ammo-list"><div class="info-card effect-pierce"><h3>🩵 Piercing</h3><p>100% primary, then <b>65% retention per target</b>: 100 → 65 → 42 → 27. Dense waves reward it, but it never becomes free full damage to everything.</p></div><div class="info-card effect-explode"><h3>💥 Explosive</h3><p>Full target damage, then <b>50% adjacent / 25% next-adjacent</b>. Future upgrades can improve blast width or flatten falloff.</p></div><div class="info-card effect-chain"><h3>⚡ Chain Lightning</h3><p>Primary impact is <b>78%</b>; first jump is <b>55%</b> and each later jump retains <b>62%</b>. It trades boss DPS for crowd clearing.</p></div><div class="info-card"><h3>🔥 Burning</h3><p>Reduced initial hit, then three repeated damage ticks. Built for long-lived enemies and burn-trigger synergies.</p></div></div>`}if(name==='gear'){const g=GEAR[save.gearIndex];title.textContent='Gear';c.innerHTML=`<div class="gear-list"><div class="info-card"><h3>🔫 ${g.name}</h3><p><span class="tag">${g.rarity}</span><span class="tag">+${Math.round((g.power-1)*100)}% power</span><span class="tag">+${Math.round((g.crit||0)*100)}% crit</span><span class="tag">+${Math.round((g.reload||0)*100)}% reload</span></p><p>Bosses pause progression and offer a side-by-side equip-or-sell choice.</p></div></div>`}if(name==='bounties'){const dps=Math.round(dmgWindow.reduce((a,x)=>a+x.d,0)/10);title.textContent='Bounties';c.innerHTML=`<div class="ammo-list"><div class="info-card"><h3>Frontier Progress</h3><p>Highest wave: <b>${save.highestWave}</b><br>Secured checkpoint: <b>${save.checkpoint}</b><br>Recent damage rate: <b>~${dps}/s</b></p></div><div class="info-card"><h3>Checkpoint Rule</h3><p>Wave 5 elites and Wave 10 bosses secure the next checkpoint. Death sends you there after upgrades.</p></div></div>`}bindBuys()}
function closeSheet(){sheetOpen=null;$('sheet').classList.remove('open');$('sheet').setAttribute('aria-hidden','true')}
function bindBuys(){document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const [currency,k]=b.dataset.buy.split(':'),table=currency==='xp'?HERO:BOARD,ranks=currency==='xp'?save.heroRanks:save.boardRanks,price=cost(table[k],ranks[k]),bal=currency==='xp'?'xp':'coins';if(save[bal]<price)return;save[bal]-=price;ranks[k]++;persist();buildPegs();if(k==='health'){const old=state.maxHp;state.maxHp=stats().maxHp;state.hp+=state.maxHp-old}if(k==='magazine')state.mag=stats().mag;openSheet(sheetOpen)}})}
function showLoot(){const cur=GEAR[save.gearIndex],idx=Math.min(GEAR.length-1,save.gearIndex+1),next=GEAR[idx],fmt=g=>`Power: +${Math.round((g.power-1)*100)}%<br>Crit: +${Math.round((g.crit||0)*100)}%<br>Reload: +${Math.round((g.reload||0)*100)}%`;$('currentLootName').textContent=`${cur.name} (${cur.rarity})`;$('newLootName').textContent=`${next.name} (${next.rarity})`;$('currentLootStats').innerHTML=fmt(cur);$('newLootStats').innerHTML=fmt(next);$('lootModal').dataset.next=idx;$('lootModal').classList.remove('hidden')}
function finishLoot(equip){const m=$('lootModal'),idx=Number(m.dataset.next||0);if(equip)save.gearIndex=idx;else save.coins+=100+state.wave*15;persist();m.classList.add('hidden');state.lootPause=false;state.wave++;spawnWave()}
document.querySelectorAll('.dock button').forEach(b=>b.onclick=()=>openSheet(b.dataset.sheet));$('closeSheet').onclick=closeSheet;$('deathHero').onclick=()=>{$('deathModal').classList.add('hidden');openSheet('hero')};$('deathBoard').onclick=()=>{$('deathModal').classList.add('hidden');openSheet('board')};$('rideAgain').onclick=()=>{closeSheet();reset()};$('equipNew').onclick=()=>finishLoot(true);$('sellNew').onclick=()=>finishLoot(false);
renderSlots();wallet();reset();requestAnimationFrame(tick);
