(function(){
'use strict';
var C=document.getElementById('board'),X=C&&C.getContext?C.getContext('2d'):null;
if(!C||!X){throw new Error('Canvas failed to initialize');}
var SLOTS=[10,7,4,2,1,2,4,7,10],KEY='ips-v4',OLD='ips-v3';
function $(id){return document.getElementById(id);}function clamp(v,a,b){return Math.max(a,Math.min(b,v));}function rnd(a,b){return a+Math.random()*(b-a);}function id(){return 'i'+Date.now().toString(36)+Math.random().toString(36).slice(2);}function has(a,v){return a.indexOf(v)>=0;}
var defaults={xp:0,coins:0,checkpoint:1,highest:1,power:0,reload:0,mag:0,crit:0,hp:0,slot:0,fire:0,split:0,pierce:0,boom:0,chain:0,placements:{fire:[],split:[],pierce:[],boom:[],chain:[]}};
function copyNumbers(dst,src){var k;for(k in dst){if(typeof dst[k]==='number'&&typeof src[k]==='number')dst[k]=src[k];}}
var save=JSON.parse(JSON.stringify(defaults));
try{var raw=localStorage.getItem(KEY),oldRaw,parsed;if(raw){parsed=JSON.parse(raw);copyNumbers(save,parsed);if(parsed.placements){var pk;for(pk in save.placements)if(parsed.placements[pk]&&parsed.placements[pk].slice)save.placements[pk]=parsed.placements[pk].slice(0);}}else{oldRaw=localStorage.getItem(OLD);if(oldRaw){parsed=JSON.parse(oldRaw);copyNumbers(save,parsed);save.highest=parsed.checkpoint||1;}}}catch(e){}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(save));}catch(e){}wallet();}
function stats(){return{maxHp:100+save.hp*15,power:7*Math.pow(1.09,save.power),reload:Math.max(2100,6200*Math.pow(.92,save.reload)),mag:5+save.mag,crit:Math.min(.45,.06+save.crit*.02),slot:Math.pow(1.08,save.slot)};}
var G=null,B=[],P=[],FX=[],last=performance.now(),sheet=null,placing=null;
var TYPES=[['zombie','Zombie Outlaw',30,8,3,9],['ghoul','Ghoul Rustler',24,7,2,10],['ghost','Ghost Gunhand',28,10,3,11],['troll','Troll Prospector',48,13,4,14]];
var DEFAULT_SPOTS={fire:[11,22,34,49],split:[17,30,45],pierce:[25,39,52],boom:[20,37,55],chain:[14,33,48]};
function enemy(w,i,n){var boss=w%10===0,t=boss?['boss','The Undertaker',230,20,3,90]:TYPES[(w+i)%TYPES.length],scale=Math.pow(1.14,w-1),elite=w%5===0&&!boss,hp=t[2]*scale*(n>1?.82:1)*(elite?1.55:1);return{id:id(),kind:t[0],name:t[1],hp:hp,max:hp,dmg:t[3]*Math.pow(1.08,w-1)*(elite?1.15:1),step:Math.max(1,t[4]-Math.floor(w/18)),counter:0,distance:0,reward:Math.round(t[5]*(1+w*.1)*(elite?1.6:1)),boss:boss,elite:elite};}
function living(){var out=[],i;if(!G)return out;for(i=0;i<G.enemies.length;i++)if(G.enemies[i].hp>0)out.push(G.enemies[i]);return out;}
function newGame(){var a=stats();G={wave:save.checkpoint,hp:a.maxHp,max:a.maxHp,enemies:[],state:'fire',mag:a.mag,launched:0,resolved:0,next:performance.now()+400,rs:0,re:0,kills:0,runXp:0,runCoins:0};B=[];buildPegs();spawnWave();$('deathModal').classList.add('hidden');}
function spawnWave(){var n=G.wave%10===0?1:(G.wave<3?1:(G.wave<6?2:3)),i;G.enemies=[];for(i=0;i<n;i++)G.enemies.push(enemy(G.wave,i,n));G.state='fire';G.mag=stats().mag;G.launched=0;G.resolved=0;G.next=performance.now()+450;renderEnemies();hud();queue();}
function placementUsed(type){return save.placements[type]?save.placements[type].length:0;}
function buildPegs(){P=[];var r,c,n,g,i,k,idx,arr,occupied={};for(r=0;r<8;r++){n=r%2?8:9;g=(C.width-56)/8;for(c=0;c<n;c++)P.push({x:28+c*g+(r%2?g/2:0),y:70+r*44,r:6,t:'n'});}for(k in save.placements){arr=save.placements[k];for(i=arr.length-1;i>=0;i--){idx=arr[i];if(idx<0||idx>=P.length||occupied[idx])arr.splice(i,1);else occupied[idx]=k;}}for(k in save.placements){arr=save.placements[k];while(arr.length<save[k]){var candidates=DEFAULT_SPOTS[k],picked=-1,j;for(j=0;j<candidates.length;j++){idx=candidates[j];if(idx<P.length&&!occupied[idx]){picked=idx;break;}}if(picked<0)break;arr.push(picked);occupied[picked]=k;}while(arr.length>save[k])arr.pop();}for(k in save.placements){arr=save.placements[k];for(i=0;i<arr.length;i++){idx=arr[i];if(P[idx])P[idx].t=k;}}}
function tag(b,t){if(!has(b.tags,t))b.tags.push(t);}
function launch(src){if(B.length>32)return;var a=stats(),b={x:src?src.x:C.width/2+rnd(-12,12),y:src?src.y:24,vx:src?-src.vx:rnd(-22,22),vy:src?-90:rnd(8,28),r:5.5,tags:src?src.tags.slice():[],mult:src?src.mult*.6:1,depth:src?src.depth+1:0,hit:{},life:18,done:false,p:a.power};if(!src&&Math.random()<.03)tag(b,'gold');B.push(b);}
function addBoardFx(x,y,type){FX.push({x:x,y:y,type:type,life:.28,max:.28});}
function pegEffect(b,p){var c;if(p.t==='n')return;addBoardFx(p.x,p.y,p.t);if(p.t==='fire'||p.t==='pierce'||p.t==='boom'||p.t==='chain')tag(b,p.t);if(p.t==='split'&&b.depth<2&&!has(b.tags,'split-lock')){tag(b,'split-lock');b.mult*=.6;c={x:b.x+1,y:b.y,vx:Math.abs(b.vx||55)+55,vy:b.vy,r:b.r,tags:b.tags.slice(),mult:b.mult,depth:b.depth+1,hit:{},life:b.life,done:false,p:b.p};b.vx=-Math.abs(b.vx||55)-55;b.depth++;B.push(c);}}
function physics(dt){var i,j,b,p,dx,dy,d2,min,d,nx,ny,dot,push;for(i=0;i<B.length;i++){b=B[i];if(b.done)continue;b.life-=dt;b.vy+=360*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<b.r+7){b.x=b.r+7;b.vx=Math.abs(b.vx)*.82;}if(b.x>C.width-b.r-7){b.x=C.width-b.r-7;b.vx=-Math.abs(b.vx)*.82;}for(j=0;j<P.length;j++){p=P[j];dx=b.x-p.x;dy=b.y-p.y;d2=dx*dx+dy*dy;min=b.r+p.r;if(d2<min*min&&d2>.01){d=Math.sqrt(d2);nx=dx/d;ny=dy/d;dot=b.vx*nx+b.vy*ny;if(dot<0){b.vx-=1.72*dot*nx;b.vy-=1.72*dot*ny;b.vx+=rnd(-14,14);b.vy*=.95;push=min-d+.2;b.x+=nx*push;b.y+=ny*push;}if(!b.hit[j]){b.hit[j]=1;pegEffect(b,p);}}}if(b.y>C.height-31||b.life<=0)resolveBall(b);}B=B.filter(function(v){return!v.done;});for(i=FX.length-1;i>=0;i--){FX[i].life-=dt;if(FX[i].life<=0)FX.splice(i,1);}}
function resolveBall(b){if(b.done)return;b.done=true;var slot=clamp(Math.floor(b.x/(C.width/9)),0,8),v=SLOTS[slot],d=b.p*v*b.mult*stats().slot,crit=Math.random()<stats().crit;if(crit)d*=2;shoot(d,b.tags,crit);G.resolved++;queue();}
function enemyElement(eid){return document.querySelector('[data-enemy-id="'+eid+'"]');}
function lineFx(eid,kind){var combat=$('combat'),hero=$('heroUnit'),target=enemyElement(eid),layer=$('combatFx');if(!combat||!hero||!target||!layer)return;var cr=combat.getBoundingClientRect(),hr=hero.getBoundingClientRect(),tr=target.getBoundingClientRect(),x1=hr.left-cr.left+hr.width*.77,y1=hr.top-cr.top+hr.height*.46,x2=tr.left-cr.left+tr.width*.5,y2=tr.top-cr.top+tr.height*.42,dx=x2-x1,dy=y2-y1,len=Math.sqrt(dx*dx+dy*dy),ang=Math.atan2(dy,dx)*180/Math.PI,m=document.createElement('i'),l=document.createElement('i');m.className='muzzle-flash';m.style.left=(x1-11)+'px';m.style.top=(y1-11)+'px';l.className='shot-tracer';l.style.left=x1+'px';l.style.top=y1+'px';l.style.width=len+'px';l.style.transform='rotate('+ang+'deg)';if(kind==='chain')l.style.background='linear-gradient(90deg,#f7eeff,#b67cff 55%,transparent)';if(kind==='fire')l.style.background='linear-gradient(90deg,#fff3ae,#ff6b2b 55%,transparent)';layer.appendChild(m);layer.appendChild(l);setTimeout(function(){if(m.parentNode)m.parentNode.removeChild(m);if(l.parentNode)l.parentNode.removeChild(l);},220);}
function deathFx(eid){var combat=$('combat'),target=enemyElement(eid),layer=$('combatFx');if(!combat||!target||!layer)return;var cr=combat.getBoundingClientRect(),tr=target.getBoundingClientRect(),d=document.createElement('i');d.className='death-spark';d.style.left=(tr.left-cr.left+tr.width*.5-15)+'px';d.style.top=(tr.top-cr.top+tr.height*.4-15)+'px';layer.appendChild(d);setTimeout(function(){if(d.parentNode)d.parentNode.removeChild(d);},500);}
function flashEnemy(eid){var el=enemyElement(eid);if(el){el.classList.add('hit');setTimeout(function(){if(el)el.classList.remove('hit');},190);}}
function hit(e,d,crit,gold,label){if(!e||e.hp<=0)return;var before=e.hp;flashEnemy(e.id);e.hp-=d;pop(Math.round(d),crit,label||'');if(before>0&&e.hp<=0){deathFx(e.id);var x=Math.round(e.reward*.75),c=e.reward*(gold?2:1);save.xp+=x;save.coins+=c;G.runXp+=x;G.runCoins+=c;G.kills++;persist();if(gold)pop('2× BOUNTY',false,'GOLD');}renderEnemies();if(!living().length)setTimeout(doneWave,360);}
function shoot(raw,tags,crit){var a=living(),i,x,primary=raw,kind='normal';if(!a.length)return;if(has(tags,'chain')){primary*=.78;kind='chain';}if(has(tags,'fire')){primary*=.72;kind='fire';}if(has(tags,'boom'))kind='boom';if(has(tags,'pierce'))kind='pierce';lineFx(a[0].id,kind);hit(a[0],primary,crit,has(tags,'gold'),'');if(has(tags,'pierce')){x=raw*.65;for(i=1;i<Math.min(4,a.length);i++){hit(a[i],x,false,false,'PIERCE');x*=.65;}}if(has(tags,'boom'))for(i=1;i<Math.min(3,a.length);i++)hit(a[i],raw*(i===1?.5:.25),false,false,'BOOM');if(has(tags,'chain')){x=raw*.55;for(i=1;i<Math.min(4,a.length);i++){hit(a[i],x,false,false,'CHAIN');x*=.62;}}if(has(tags,'fire'))for(i=1;i<=3;i++)setTimeout(function(){var live=living();if(live.length)hit(live[0],raw*.13,false,false,'BURN');},i*650);}
function doneWave(){if(living().length)return;B=[];var w=G.wave;if(w%5===0)save.checkpoint=w+1;save.highest=Math.max(save.highest,w+1);var bonus=20+w*4;save.coins+=bonus;G.runCoins+=bonus;persist();G.wave++;spawnWave();}
function reloadDone(){var a=living(),i,e;for(i=0;i<a.length;i++){e=a[i];e.counter++;if(e.counter>=e.step){e.counter=0;if(e.distance<3)e.distance++;else{G.hp-=e.dmg;pop('-'+Math.round(e.dmg)+' HP',false,'HIT');}}}if(G.hp<=0){G.state='dead';G.hp=0;$('deathSummary').textContent='You reached Wave '+G.wave+', defeated '+G.kills+' enemies, and banked '+G.runXp+' XP + '+G.runCoins+' coins. Checkpoint: Wave '+save.checkpoint+'.';$('deathModal').classList.remove('hidden');}else{G.state='fire';G.mag=stats().mag;G.launched=0;G.resolved=0;G.next=performance.now()+220;}renderEnemies();queue();}
function frame(now){var dt=Math.min(.033,(now-last)/1000);last=now;if(G&&G.state!=='dead'){physics(dt);if(G.state==='fire'&&now>=G.next&&G.launched<G.mag){launch(null);G.launched++;G.next=now+650;queue();}if(G.state==='fire'&&G.launched>=G.mag&&G.resolved>=G.mag&&!B.length&&living().length){G.state='reload';G.rs=now;G.re=now+stats().reload;}if(G.state==='reload'&&now>=G.re)reloadDone();}draw();hud();requestAnimationFrame(frame);}
function draw(){var W=C.width,H=C.height,i,p,b,c,f,g=X.createLinearGradient(0,0,0,H),colors={n:'#9a7e5d',fire:'#ff6b2b',split:'#62d6c8',pierce:'#70cfe0',boom:'#e34d2e',chain:'#b67cff'},glyph={fire:'F',split:'2',pierce:'P',boom:'D',chain:'Z'};g.addColorStop(0,'#2b1d15');g.addColorStop(1,'#15100d');X.clearRect(0,0,W,H);X.fillStyle=g;X.fillRect(0,0,W,H);X.strokeStyle='rgba(220,174,99,.20)';X.lineWidth=1;for(i=1;i<9;i++){X.beginPath();X.moveTo(i*(W/9),H-57);X.lineTo(i*(W/9),H-4);X.stroke();}for(i=0;i<P.length;i++){p=P[i];c=colors[p.t];X.beginPath();X.arc(p.x,p.y,p.t==='n'?5.3:7.2,0,Math.PI*2);X.fillStyle=c;X.shadowBlur=p.t==='n'?0:12;X.shadowColor=c;X.fill();X.shadowBlur=0;X.strokeStyle='#362116';X.lineWidth=1.5;X.stroke();if(p.t!=='n'){X.fillStyle='#20120d';X.font='bold 7px sans-serif';X.textAlign='center';X.textBaseline='middle';X.fillText(glyph[p.t],p.x,p.y+.5);}}for(i=0;i<FX.length;i++){f=FX[i];c=colors[f.type]||'#fff';X.beginPath();X.arc(f.x,f.y,8+(1-f.life/f.max)*18,0,Math.PI*2);X.strokeStyle=c;X.globalAlpha=f.life/f.max;X.lineWidth=2;X.stroke();X.globalAlpha=1;}for(i=0;i<B.length;i++){b=B[i];c=has(b.tags,'chain')?'#c89aff':has(b.tags,'boom')?'#ff7348':has(b.tags,'fire')?'#ff9a3d':has(b.tags,'pierce')?'#7de3ed':has(b.tags,'gold')?'#ffd957':'#e1bd73';X.beginPath();X.arc(b.x,b.y,b.r,0,Math.PI*2);X.fillStyle=c;X.shadowBlur=10;X.shadowColor=c;X.fill();X.shadowBlur=0;X.strokeStyle='#5b351d';X.stroke();}}
function wallet(){$('xpValue').textContent=Math.floor(save.xp);$('coinValue').textContent=Math.floor(save.coins);}
function renderSlots(){$('slotLabels').innerHTML=SLOTS.map(function(v,i){return'<div class="slot-label '+(i===0||i===8?'edge':'')+'">'+v+'</div>';}).join('');}
function queue(){var q=$('bulletQueue'),i,s;if(!G)return;q.innerHTML='';for(i=0;i<G.mag;i++){s=document.createElement('span');s.className='queue-bullet'+(i<G.launched?' spent':'');q.appendChild(s);}}
function hud(){if(!G)return;$('heroHpFill').style.width=clamp(G.hp/G.max*100,0,100)+'%';$('heroHpText').textContent=Math.max(0,Math.round(G.hp))+' / '+G.max;$('magText').textContent=Math.max(0,G.mag-G.launched)+' / '+G.mag;$('waveBadge').textContent='WAVE '+G.wave;$('bossBadge').textContent=G.wave%10===0?'BOSS':'BOSS IN '+(10-G.wave%10);if(G.state==='reload'){var p=clamp((performance.now()-G.rs)/(G.re-G.rs),0,1);$('reloadFill').style.width=p*100+'%';$('reloadLabel').textContent='RELOADING '+(Math.max(0,G.re-performance.now())/1000).toFixed(1)+'s';}else{$('reloadFill').style.width='0%';$('reloadLabel').textContent=G.state==='dead'?'DOWN':'FIRING';}}
function sprite(kind){if(kind==='zombie')return'<svg viewBox="0 0 100 120"><path class="sprite-outline zombie-shirt" d="M28 58q22-14 44 0l9 50H19z"/><circle class="sprite-outline zombie-skin" cx="51" cy="38" r="18"/><path class="sprite-outline zombie-skin" d="M41 48l-5 16 17-4z"/><path class="sprite-outline zombie-body" d="M31 20h41l-8 13H37z"/><path fill="#21120e" d="M39 37h8v4h-8zm16 0h8v4h-8z"/></svg>';if(kind==='ghoul')return'<svg viewBox="0 0 100 120"><path class="sprite-outline ghoul-body" d="M27 56q23-18 46 0l6 52H20z"/><circle class="sprite-outline ghoul-skin" cx="50" cy="38" r="18"/><path class="sprite-outline ghoul-skin" d="M35 34l-13-8 14 17zm30 0 13-8-14 17z"/><path fill="#2a1510" d="M39 37h8v4h-8zm15 0h8v4h-8zm-6 11h8v8h-8z"/></svg>';if(kind==='ghost')return'<svg viewBox="0 0 100 120"><path class="sprite-outline ghost-body" d="M23 104q3-21 1-43Q23 18 50 15q28 3 27 46-3 23 1 43l-13-9-14 11-14-11z"/><circle class="ghost-glow" cx="41" cy="46" r="5"/><circle class="ghost-glow" cx="60" cy="46" r="5"/><path class="ghost-glow" d="M41 62q9 8 18 0-3 14-9 14t-9-14z"/></svg>';if(kind==='troll')return'<svg viewBox="0 0 100 120"><path class="sprite-outline troll-body" d="M17 107l9-56 17-12h16l17 12 8 56z"/><circle class="sprite-outline troll-body" cx="51" cy="34" r="21"/><path class="sprite-outline troll-hide" d="M16 64h22l-2 15H12zm48 0h22l4 15H66z"/><path fill="#2a1510" d="M38 32h9v5h-9zm18 0h9v5h-9zm-8 11h9v10h-9z"/></svg>';return'<svg viewBox="0 0 100 120"><path class="sprite-outline boss-body" d="M22 109l8-62q20-13 40 0l9 62z"/><circle class="sprite-outline boss-body" cx="50" cy="33" r="19"/><path class="sprite-outline boss-body" d="M20 20h60L65 34H35zM35 5h30l7 17H28z"/><circle class="boss-fire" cx="42" cy="34" r="5"/><circle class="boss-fire" cx="59" cy="34" r="5"/><path class="boss-fire" d="M42 49h17l-8 12z"/></svg>';}
function renderEnemies(){var lane=$('enemyLane'),a=living(),i,e,d;lane.innerHTML='';for(i=0;i<a.length;i++){e=a[i];d=document.createElement('div');d.className='enemy'+(e.boss?' boss':'')+(e.elite?' elite':'');d.setAttribute('data-enemy-id',e.id);d.style.transform='translateX('+(-e.distance*13)+'px)';d.innerHTML='<div class="unit-figure">'+sprite(e.kind)+'</div><div class="enemy-name">'+e.name+'</div><div class="hp-track"><div class="hp-fill" style="width:'+clamp(e.hp/e.max*100,0,100)+'%"></div></div><div class="unit-meta"><span>'+Math.max(0,Math.round(e.hp))+' HP</span><span>'+['FAR','MID','NEAR','COVER'][e.distance]+'</span></div>';lane.appendChild(d);}}
function pop(v,crit,label){var d=document.createElement('div');d.className='damage-number'+(crit?' crit':'')+(label?' effect':'');d.style.right=rnd(12,42)+'%';d.style.top=rnd(35,62)+'%';d.textContent=(crit?'CRIT ':'')+v+(label?' '+label:'');$('damageFeed').appendChild(d);setTimeout(function(){if(d.parentNode)d.parentNode.removeChild(d);},850);}
function cost(base,rank,growth){return Math.round(base*Math.pow(growth||1.7,rank));}
var HERO=[['power','High Caliber','+9% base bullet damage',40],['crit','Deadeye','+2% critical chance',50],['reload','Quick Hands','8% faster reload',55],['mag','Deep Pockets','+1 bullet per cylinder',100],['hp','Grit','+15 maximum HP',60]];
var PEGS=[['fire','Fire Peg','Burning: reduced impact + 3 ticks',90],['split','Splitter Peg','Creates two 60% branches',120],['pierce','Piercing Peg','100% → 65% → 42% → 27%',150],['boom','Dynamite Peg','100% / 50% / 25% splash',190],['chain','Storm Peg','Lower damage, multiple chained targets',240]];
function openSheet(name){sheet=name;$('sheet').classList.add('open');$('sheet').setAttribute('aria-hidden','false');var title=$('sheetTitle'),c=$('sheetContent'),h='',i,a,n;if(name==='hero'){title.textContent='Gunslinger';for(i=0;i<HERO.length;i++){a=HERO[i];n=cost(a[3],save[a[0]],1.62);h+='<article class="upgrade-card"><h3>'+a[1]+'</h3><div class="rankline"><span>Rank '+save[a[0]]+'</span><span>'+a[2]+'</span></div><button class="buy-btn" data-hero="'+a[0]+'" data-base="'+a[3]+'" '+(save.xp<n?'disabled':'')+'>✦ '+n+'</button></article>';}c.innerHTML='<div class="balance-card"><span>Permanent gunslinger upgrades</span><b>✦ '+Math.floor(save.xp)+' XP</b></div><div class="upgrade-grid">'+h+'</div>';}else if(name==='board'){title.textContent='Pachinko Board';n=cost(50,save.slot,1.58);h='<article class="upgrade-card"><h3>Sharpen Slots</h3><div class="rankline"><span>Rank '+save.slot+'</span><span>+8% slot damage</span></div><button class="buy-btn" data-board="slot" data-base="50" '+(save.coins<n?'disabled':'')+'>● '+n+'</button></article>';for(i=0;i<PEGS.length;i++){a=PEGS[i];n=cost(a[3],save[a[0]],1.7);h+='<article class="upgrade-card"><h3><span class="peg-dot '+a[0]+'"></span>'+a[1]+'</h3><div class="rankline"><span>Owned '+save[a[0]]+'</span><span>Placed '+placementUsed(a[0])+'</span></div><p>'+a[2]+'</p><button class="buy-btn" data-board="'+a[0]+'" data-base="'+a[3]+'" '+(save.coins<n?'disabled':'')+'>BUY ● '+n+'</button><button class="place-btn" data-place="'+a[0]+'" '+(save[a[0]]<1?'disabled':'')+'>'+ (placementUsed(a[0])<save[a[0]]?'PLACE AVAILABLE':'MOVE A PEG') +'</button></article>';}c.innerHTML='<div class="balance-card"><span>Tap PLACE, then tap the peg on the live board.</span><b>● '+Math.floor(save.coins)+' coins</b></div><div class="upgrade-grid">'+h+'</div>';}else if(name==='ammo'){title.textContent='Ammo Lab';c.innerHTML='<div class="peg-legend"><div class="peg-chip"><b>Golden rounds</b><small>3% natural chance. Killing blow pays 2× coins.</small></div><div class="peg-chip"><b>Piercing</b><small>Diminishing damage through up to 4 enemies.</small></div><div class="peg-chip"><b>Dynamite</b><small>Primary target plus 50% / 25% splash.</small></div><div class="peg-chip"><b>Storm</b><small>Reduced primary damage, then lightning jumps.</small></div></div><div class="info-card"><h3>Next milestone</h3><p>Ammo becomes a selectable loadout with bullet rarity, magazine composition, and permanent ammunition upgrades.</p></div>';}else if(name==='gear'){title.textContent='Gear';c.innerHTML='<div class="info-card"><h3>Boss loot — next</h3><p>Wave bosses will pause progression and present current-vs-drop comparison for guns, hats, dusters, boots, and charms.</p></div>';}else{title.textContent='Bounties';c.innerHTML='<div class="info-card"><h3>Frontier progress</h3><p>Highest wave: <b>'+save.highest+'</b><br>Secured checkpoint: <b>'+save.checkpoint+'</b><br>Current run kills: <b>'+G.kills+'</b></p></div>';}bindSheet();}
function closeSheet(){sheet=null;$('sheet').classList.remove('open');$('sheet').setAttribute('aria-hidden','true');}
function bindSheet(){var a=document.querySelectorAll('[data-hero]'),i;for(i=0;i<a.length;i++)a[i].onclick=function(){var k=this.getAttribute('data-hero'),base=Number(this.getAttribute('data-base')),n=cost(base,save[k],1.62),before=stats();if(save.xp<n)return;save.xp-=n;save[k]++;persist();if(k==='hp'){var after=stats();G.hp+=after.maxHp-before.maxHp;G.max=after.maxHp;}if(k==='mag')G.mag=stats().mag;openSheet('hero');};a=document.querySelectorAll('[data-board]');for(i=0;i<a.length;i++)a[i].onclick=function(){var k=this.getAttribute('data-board'),base=Number(this.getAttribute('data-base')),n=cost(base,save[k],k==='slot'?1.58:1.7);if(save.coins<n)return;save.coins-=n;save[k]++;buildPegs();persist();openSheet('board');};a=document.querySelectorAll('[data-place]');for(i=0;i<a.length;i++)a[i].onclick=function(){beginPlacement(this.getAttribute('data-place'));};}
function beginPlacement(type){if(save[type]<1)return;placing=type;closeSheet();$('placementText').textContent='Tap a board peg to place '+pegName(type)+'. Game stays live.';$('placementBanner').classList.remove('hidden');document.querySelector('.board-wrap').classList.add('placing');}
function cancelPlacement(){placing=null;$('placementBanner').classList.add('hidden');document.querySelector('.board-wrap').classList.remove('placing');}
function pegName(type){var m={fire:'Fire Peg',split:'Splitter Peg',pierce:'Piercing Peg',boom:'Dynamite Peg',chain:'Storm Peg'};return m[type]||'Peg';}
function nearestPeg(px,py){var best=-1,bd=999999,i,dx,dy,d;for(i=0;i<P.length;i++){dx=P[i].x-px;dy=P[i].y-py;d=dx*dx+dy*dy;if(d<bd){bd=d;best=i;}}return bd<35*35?best:-1;}
function placeAt(index){if(!placing||index<0)return;var type=placing,k,arr;for(k in save.placements){arr=save.placements[k];if(k!==type){var oi=arr.indexOf(index);if(oi>=0)arr.splice(oi,1);}}arr=save.placements[type];if(arr.indexOf(index)<0){if(arr.length<save[type])arr.push(index);else if(arr.length)arr[arr.length-1]=index;}buildPegs();persist();addBoardFx(P[index].x,P[index].y,type);cancelPlacement();setTimeout(function(){openSheet('board');},180);}
function canvasPoint(ev){var r=C.getBoundingClientRect(),t=ev.touches&&ev.touches.length?ev.touches[0]:ev.changedTouches&&ev.changedTouches.length?ev.changedTouches[0]:ev;return{x:(t.clientX-r.left)*(C.width/r.width),y:(t.clientY-r.top)*(C.height/r.height)};}
C.addEventListener('click',function(ev){if(!placing)return;var p=canvasPoint(ev);placeAt(nearestPeg(p.x,p.y));});C.addEventListener('touchend',function(ev){if(!placing)return;ev.preventDefault();var p=canvasPoint(ev);placeAt(nearestPeg(p.x,p.y));},{passive:false});
document.querySelectorAll('.dock button').forEach(function(b){b.onclick=function(){openSheet(this.getAttribute('data-sheet'));};});$('closeSheet').onclick=closeSheet;$('cancelPlacement').onclick=cancelPlacement;$('deathHero').onclick=function(){$('deathModal').classList.add('hidden');openSheet('hero');};$('deathBoard').onclick=function(){$('deathModal').classList.add('hidden');openSheet('board');};$('rideAgain').onclick=function(){closeSheet();cancelPlacement();newGame();};
renderSlots();wallet();newGame();window.__ipsBooted=true;var err=$('bootError');if(err)err.classList.add('hidden');requestAnimationFrame(frame);
})();
