(function(){
'use strict';
var META_KEY='ips-idle-v1',TELEMETRY_KEY='ips-telemetry-v1',SAVE_KEYS=['ips-v7','ips-v6','ips-v5'];
var now=Date.now(),sessionStart=now,summary=null,hiddenAt=0,resumeReload=false;
function $(id){return document.getElementById(id);}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function readJSON(key,fallback){try{var raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback;}catch(e){return fallback;}}
function writeJSON(key,val){try{localStorage.setItem(key,JSON.stringify(val));}catch(e){}}
function activeSaveKey(){var i;for(i=0;i<SAVE_KEYS.length;i++)if(localStorage.getItem(SAVE_KEYS[i]))return SAVE_KEYS[i];return null;}
function rarityScore(name){var m={common:1,uncommon:2,rare:3,legendary:4,mythic:5,unique:7};return m[String(name||'').toLowerCase()]||0;}
function buildScore(save){var score=0,k,it;['power','reload','mag','crit','hp','slot','fire','split','pierce','boom','chain'].forEach(function(x){score+=Number(save[x]||0);});if(save.ammoRank)for(k in save.ammoRank)score+=Number(save.ammoRank[k]||0)*.7;if(save.gear)for(k in save.gear){it=save.gear[k];if(it)score+=rarityScore(it.rarity)*1.7;}return score;}
function offlineRates(save){var checkpoint=Math.max(1,Number(save.checkpoint||1)),build=buildScore(save),cpFactor=1+(checkpoint-1)*.105,buildFactor=clamp(1+build*.012,1,2.5);return{xp:.22*cpFactor*buildFactor,coins:.35*cpFactor*buildFactor,checkpoint:checkpoint,buildFactor:buildFactor};}
function formatDuration(ms){var mins=Math.floor(ms/60000),h=Math.floor(mins/60),m=mins%60;if(h>0)return h+'h '+m+'m';return mins+'m';}
function applyOfflineProgress(){var meta=readJSON(META_KEY,{lastSeen:0,totalOfflineXp:0,totalOfflineCoins:0,totalAwayMs:0,returns:0}),key=activeSaveKey(),save=key?readJSON(key,null):null,last=Number(meta.lastSeen||0),away=last?Math.max(0,now-last):0;meta.lastSeen=now;if(save&&away>=120000){var capped=Math.min(away,8*60*60*1000),mins=capped/60000,r=offlineRates(save),xp=Math.floor(mins*r.xp),coins=Math.floor(mins*r.coins),patrols=Math.max(1,Math.floor(mins/(7.5/Math.sqrt(r.checkpoint))));if(xp>0||coins>0){save.xp=Number(save.xp||0)+xp;save.coins=Number(save.coins||0)+coins;writeJSON(key,save);meta.totalOfflineXp=Number(meta.totalOfflineXp||0)+xp;meta.totalOfflineCoins=Number(meta.totalOfflineCoins||0)+coins;meta.totalAwayMs=Number(meta.totalAwayMs||0)+capped;meta.returns=Number(meta.returns||0)+1;summary={away:away,capped:capped,xp:xp,coins:coins,patrols:patrols,checkpoint:r.checkpoint,capHit:away>capped};}}writeJSON(META_KEY,meta);}
function showReturnSummary(){if(!summary)return;var modal=$('returnModal');if(!modal)return;$('returnTime').textContent=formatDuration(summary.away);$('returnCheckpoint').textContent='Checkpoint '+summary.checkpoint;$('returnPatrols').textContent=summary.patrols+' patrol skirmishes';$('returnXp').textContent='+'+summary.xp+' XP';$('returnCoins').textContent='+'+summary.coins+' coins';$('returnCapNote').textContent=summary.capHit?'Offline earnings are capped at 8 hours. Bosses, checkpoints, and loot never resolve offline.':'Bosses, checkpoints, and loot never resolve offline.';modal.classList.remove('hidden');}
function telemetry(){return readJSON(TELEMETRY_KEY,{sessions:0,totalPlayMs:0,totalReloads:0,totalDeaths:0,totalBossLoot:0,totalWaveTransitions:0,bestWaveSeen:1,lastSession:null});}
var session={started:sessionStart,reloads:0,deaths:0,bossLoot:0,waveTransitions:0,bestWave:1,lastWave:1};
function persistTelemetry(){var t=telemetry(),elapsed=Math.max(0,Date.now()-sessionStart);t.sessions=Number(t.sessions||0)+1;t.totalPlayMs=Number(t.totalPlayMs||0)+elapsed;t.totalReloads=Number(t.totalReloads||0)+session.reloads;t.totalDeaths=Number(t.totalDeaths||0)+session.deaths;t.totalBossLoot=Number(t.totalBossLoot||0)+session.bossLoot;t.totalWaveTransitions=Number(t.totalWaveTransitions||0)+session.waveTransitions;t.bestWaveSeen=Math.max(Number(t.bestWaveSeen||1),session.bestWave);t.lastSession={durationMs:elapsed,reloads:session.reloads,deaths:session.deaths,bossLoot:session.bossLoot,waveTransitions:session.waveTransitions,bestWave:session.bestWave,endedAt:Date.now()};writeJSON(TELEMETRY_KEY,t);sessionStart=Date.now();session.reloads=session.deaths=session.bossLoot=session.waveTransitions=0;}
function observeGame(){var wave=$('waveBadge'),reload=$('reloadLabel'),death=$('deathModal'),loot=$('lootModal');if(wave){var wobs=new MutationObserver(function(){var m=(wave.textContent||'').match(/(\d+)/),w=m?Number(m[1]):1;if(w!==session.lastWave){session.waveTransitions++;session.lastWave=w;session.bestWave=Math.max(session.bestWave,w);}});wobs.observe(wave,{childList:true,characterData:true,subtree:true});}if(reload){var prev=reload.textContent||'';var robs=new MutationObserver(function(){var cur=reload.textContent||'';if(cur.indexOf('RELOADING')===0&&prev.indexOf('RELOADING')!==0)session.reloads++;prev=cur;});robs.observe(reload,{childList:true,characterData:true,subtree:true});}if(death){var dprev=death.classList.contains('hidden');var dobs=new MutationObserver(function(){var hidden=death.classList.contains('hidden');if(dprev&&!hidden)session.deaths++;dprev=hidden;});dobs.observe(death,{attributes:true,attributeFilter:['class']});}if(loot){var lprev=loot.classList.contains('hidden');var lobs=new MutationObserver(function(){var hidden=loot.classList.contains('hidden');if(lprev&&!hidden)session.bossLoot++;lprev=hidden;});lobs.observe(loot,{attributes:true,attributeFilter:['class']});}}
function gearSummary(save){var out=[],k,it;if(!save||!save.gear)return'None yet';for(k in save.gear){it=save.gear[k];if(it)out.push(k+': '+(it.rarity||'?')+' '+(it.name||''));}return out.length?out.join('\n'):'None yet';}
function ammoSummary(save){if(!save||!save.cylinder)return'Standard only';var counts={},i,t,out=[];for(i=0;i<save.cylinder.length;i++){t=save.cylinder[i]||'standard';counts[t]=(counts[t]||0)+1;}for(t in counts)out.push(t+' ×'+counts[t]);return out.join(', ');}
function openTelemetry(){var key=activeSaveKey(),save=key?readJSON(key,{}):{},meta=readJSON(META_KEY,{}),t=telemetry(),wave=($('waveBadge')&&$('waveBadge').textContent)||'—',hp=($('heroHpText')&&$('heroHpText').textContent)||'—',rates=offlineRates(save),mins=(Date.now()-sessionStart)/60000,wpm=mins>0?session.waveTransitions/mins:0;$('telemetryContent').innerHTML='<div class="telemetry-grid"><div><b>LIVE</b><span>'+wave+'</span><small>HP '+hp+'</small></div><div><b>SESSION</b><span>'+formatDuration(Date.now()-sessionStart)+'</span><small>'+session.waveTransitions+' wave moves · '+session.reloads+' reloads</small></div><div><b>PACE</b><span>'+wpm.toFixed(2)+' waves/min</span><small>'+session.deaths+' deaths · '+session.bossLoot+' boss drops</small></div><div><b>PROGRESS</b><span>CP '+Number(save.checkpoint||1)+'</span><small>Highest '+Number(save.highest||1)+'</small></div><div><b>OFFLINE RATE</b><span>'+rates.xp.toFixed(2)+' XP/min</span><small>'+rates.coins.toFixed(2)+' coins/min · 8h cap</small></div><div><b>LIFETIME IDLE</b><span>'+Number(meta.totalOfflineXp||0)+' XP</span><small>'+Number(meta.totalOfflineCoins||0)+' coins · '+Number(meta.returns||0)+' returns</small></div></div><div class="telemetry-section"><h3>Current cylinder</h3><p>'+ammoSummary(save)+'</p></div><div class="telemetry-section"><h3>Equipped gear</h3><pre>'+gearSummary(save)+'</pre></div><div class="telemetry-section"><h3>Lifetime prototype telemetry</h3><p>'+Number(t.sessions||0)+' prior sessions · '+formatDuration(Number(t.totalPlayMs||0))+' play time · best wave '+Number(t.bestWaveSeen||1)+'</p></div>';$('telemetryModal').classList.remove('hidden');}
function bindUi(){var c=$('returnContinue'),dev=$('devButton'),close=$('closeTelemetry'),reset=$('resetTelemetry');if(c)c.onclick=function(){$('returnModal').classList.add('hidden');};if(dev)dev.onclick=openTelemetry;if(close)close.onclick=function(){$('telemetryModal').classList.add('hidden');};if(reset)reset.onclick=function(){writeJSON(TELEMETRY_KEY,{sessions:0,totalPlayMs:0,totalReloads:0,totalDeaths:0,totalBossLoot:0,totalWaveTransitions:0,bestWaveSeen:1,lastSession:null});openTelemetry();};}
function touchLastSeen(){var meta=readJSON(META_KEY,{});meta.lastSeen=Date.now();writeJSON(META_KEY,meta);}
applyOfflineProgress();
window.addEventListener('DOMContentLoaded',function(){bindUi();observeGame();setTimeout(showReturnSummary,900);});
setInterval(touchLastSeen,15000);
document.addEventListener('visibilitychange',function(){if(document.hidden){hiddenAt=Date.now();touchLastSeen();persistTelemetry();}else if(hiddenAt&&Date.now()-hiddenAt>120000){var meta=readJSON(META_KEY,{});meta.lastSeen=hiddenAt;writeJSON(META_KEY,meta);resumeReload=true;location.reload();}});
window.addEventListener('pagehide',function(){if(!resumeReload)touchLastSeen();persistTelemetry();});
})();