(function(){
'use strict';
var board=document.getElementById('board'),wrap=board&&board.closest('.board-wrap'),api=null,menu=null,moving=null,levelCanvas=null,confirmSellUntil=0;
var TYPES=['fire','split','pierce','boom','chain'];
function snap(){return api&&api.snapshot?api.snapshot():{};}
function pegPositions(){var out=[],r,c,n,g=(393-56)/8;for(r=0;r<8;r++){n=r%2?8:9;for(c=0;c<n;c++)out.push({x:28+c*g+(r%2?g/2:0),y:70+r*44});}return out;}
var POS=pegPositions();
function boardPoint(ev){var r=board.getBoundingClientRect();return{x:(ev.clientX-r.left)*(board.width/r.width),y:(ev.clientY-r.top)*(board.height/r.height)};}
function nearestIndex(pt,max){var best=-1,bd=Infinity,i,dx,dy,d;for(i=0;i<POS.length;i++){dx=POS[i].x-pt.x;dy=POS[i].y-pt.y;d=dx*dx+dy*dy;if(d<bd){bd=d;best=i;}}return bd<=max*max?best:-1;}
function typeAt(index,s){var p=(s&&s.placements)||{},i,t,a;for(i=0;i<TYPES.length;i++){t=TYPES[i];a=p[t]||[];if(a.indexOf(index)>=0)return t;}return null;}
function toast(title,text){var b=document.getElementById('campaignToast');if(!b)return;b.innerHTML='<b>'+title+'</b><span>'+text+'</span>';b.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(function(){b.classList.remove('show');},2600);}
function removeMenu(){if(menu&&menu.parentNode)menu.parentNode.removeChild(menu);menu=null;confirmSellUntil=0;}
function clampMenu(){if(!menu||!wrap)return;var rr=wrap.getBoundingClientRect(),mr=menu.getBoundingClientRect(),left=parseFloat(menu.style.left)||0,top=parseFloat(menu.style.top)||0;left=Math.max(8,Math.min(rr.width-mr.width-8,left));top=Math.max(8,Math.min(rr.height-mr.height-8,top));menu.style.left=left+'px';menu.style.top=top+'px';}
function showMenu(type,index,clientX,clientY){if(!api)return;var info=api.getPegInfo(type,index);if(!info)return;removeMenu();menu=document.createElement('div');menu.className='peg-context';menu.setAttribute('role','dialog');menu.setAttribute('aria-label',info.name+' controls');var upDisabled=info.level>=info.maxLevel?' disabled':'';menu.innerHTML='<div class="peg-context-head"><div><small>BOARD PEG</small><b>'+info.name+'</b></div><span>LV '+info.level+'/'+info.maxLevel+'</span></div><div class="peg-effect">'+info.effect+'</div><div class="peg-context-actions"><button data-peg-upgrade'+upDisabled+'>'+(info.level>=info.maxLevel?'MAX LEVEL':'UPGRADE · ● '+info.upgradeCost)+'</button><button data-peg-move>MOVE</button><button class="sell" data-peg-sell>SELL · ● '+info.sellValue+'</button></div><div class="peg-invested">Invested ● '+info.invested+' · sell returns 50%</div>';
  wrap.appendChild(menu);
  var wr=wrap.getBoundingClientRect();menu.style.left=(clientX-wr.left+8)+'px';menu.style.top=(clientY-wr.top-24)+'px';requestAnimationFrame(clampMenu);
  var up=menu.querySelector('[data-peg-upgrade]'),mv=menu.querySelector('[data-peg-move]'),sell=menu.querySelector('[data-peg-sell]');
  if(up)up.onclick=function(ev){ev.stopPropagation();if(up.disabled)return;var res=api.upgradePeg(type,index);if(res&&res.ok){toast('PEG UPGRADED',res.info.effect);showMenu(type,index,clientX,clientY);drawLevels();}else if(res&&res.reason==='coins')toast('NOT ENOUGH COINS','Need ● '+Math.ceil(res.need||0)+' more.');};
  if(mv)mv.onclick=function(ev){ev.stopPropagation();moving={type:type,index:index,name:info.name};removeMenu();var banner=document.getElementById('placementBanner'),text=document.getElementById('placementText');if(text)text.textContent='Move '+info.name+' — tap an empty peg position.';if(banner)banner.classList.remove('hidden');wrap.classList.add('peg-moving');toast('MOVE PEG','Tap an empty board peg.');};
  if(sell)sell.onclick=function(ev){ev.stopPropagation();var now=performance.now();if(now>confirmSellUntil){confirmSellUntil=now+2400;sell.textContent='TAP AGAIN TO SELL · ● '+info.sellValue;sell.classList.add('confirm');return;}var res=api.sellPeg(type,index);if(res&&res.ok){removeMenu();toast('PEG SOLD','Recovered ● '+res.value);drawLevels();}else toast('SELL FAILED','Peg could not be sold.');};
}
function clearMove(){moving=null;if(wrap)wrap.classList.remove('peg-moving');var banner=document.getElementById('placementBanner');if(banner)banner.classList.add('hidden');}
function handleBoardPointer(ev){if(!api||!board||!wrap)return;var pt=boardPoint(ev),idx=nearestIndex(pt,24),s=snap(),type;
  if(moving){ev.preventDefault();ev.stopPropagation();if(idx<0){toast('MOVE PEG','Tap closer to a peg position.');return;}type=typeAt(idx,s);if(type&&idx!==moving.index){toast('SPOT OCCUPIED','Choose an empty peg position.');return;}var res=api.movePeg(moving.type,moving.index,idx);if(res&&res.ok){toast('PEG MOVED',moving.name+' repositioned.');clearMove();drawLevels();}else if(res&&res.reason==='occupied')toast('SPOT OCCUPIED','Choose an empty peg position.');return;}
  if(idx<0){removeMenu();return;}type=typeAt(idx,s);if(!type){removeMenu();return;}ev.preventDefault();ev.stopPropagation();showMenu(type,idx,ev.clientX,ev.clientY);
}
function ensureLevelCanvas(){if(levelCanvas||!board||!wrap)return;levelCanvas=document.createElement('canvas');levelCanvas.className='peg-level-overlay';levelCanvas.width=board.width*2;levelCanvas.height=board.height*2;levelCanvas.setAttribute('aria-hidden','true');board.insertAdjacentElement('afterend',levelCanvas);placeLevelCanvas();}
function placeLevelCanvas(){if(!levelCanvas||!board||!wrap)return;var br=board.getBoundingClientRect(),wr=wrap.getBoundingClientRect();levelCanvas.style.left=(br.left-wr.left)+'px';levelCanvas.style.top=(br.top-wr.top)+'px';levelCanvas.style.width=br.width+'px';levelCanvas.style.height=br.height+'px';}
function drawLevels(){ensureLevelCanvas();if(!levelCanvas||!api)return;var ctx=levelCanvas.getContext('2d'),s=snap(),meta=s.pegMeta||{},i,j,t,a,idx,m,lvl,p,x;ctx.setTransform(2,0,0,2,0,0);ctx.clearRect(0,0,board.width,board.height);for(i=0;i<TYPES.length;i++){t=TYPES[i];a=(s.placements&&s.placements[t])||[];for(j=0;j<a.length;j++){idx=a[j];m=(meta[t]&&meta[t][String(idx)])||{};lvl=Math.max(0,Math.min(3,Number(m.level||0)));if(!lvl)continue;p=POS[idx];if(!p)continue;for(x=0;x<lvl;x++){ctx.fillStyle='#ffd36b';ctx.strokeStyle='#3d2412';ctx.lineWidth=1;ctx.fillRect(p.x-((lvl*5-2)/2)+x*5,p.y-15,3,3);ctx.strokeRect(p.x-((lvl*5-2)/2)+x*5-.5,p.y-15.5,4,4);}}}}
function rewriteBoardSheet(){var title=document.getElementById('sheetTitle'),content=document.getElementById('sheetContent');if(!title||!content||!/Pachinko/i.test(title.textContent))return;var balance=content.querySelector('.balance-card span');if(balance)balance.textContent='Buy pegs here. Tap a placed special peg on the board to upgrade, move, or sell.';}
function boot(){api=window.__ipsAPI;if(!api||!api.getPegInfo||!board||!wrap)return false;board.addEventListener('pointerup',handleBoardPointer,true);document.addEventListener('pointerdown',function(ev){if(menu&&!menu.contains(ev.target)&&ev.target!==board)removeMenu();},true);var cancel=document.getElementById('cancelPlacement');if(cancel)cancel.addEventListener('click',function(){if(moving)clearMove();});document.addEventListener('ips:pegUpgrade',drawLevels);document.addEventListener('ips:pegMove',drawLevels);document.addEventListener('ips:pegSell',drawLevels);document.addEventListener('ips:upgrade',function(){setTimeout(drawLevels,40);});document.addEventListener('ips:menu',function(){setTimeout(rewriteBoardSheet,30);});window.addEventListener('resize',function(){placeLevelCanvas();removeMenu();});var content=document.getElementById('sheetContent');if(content)new MutationObserver(function(){rewriteBoardSheet();}).observe(content,{childList:true,subtree:true});ensureLevelCanvas();drawLevels();return true;}
var tries=0,t=setInterval(function(){tries++;if(boot()||tries>120)clearInterval(t);},100);
})();
