(function(){
'use strict';
var META={
 hero:{src:'assets/sprites/v110/hero.png',fw:64,fh:80},
 zombie:{src:'assets/sprites/v110/zombie.png',fw:64,fh:80},
 ghoul:{src:'assets/sprites/v110/ghoul.png',fw:64,fh:80},
 ghost:{src:'assets/sprites/v110/ghost.png',fw:64,fh:80,floating:true},
 troll:{src:'assets/sprites/v110/troll.png',fw:80,fh:96,heavy:true}
};
var FRAME={idle:0,moveA:1,moveB:2,attack:3,hurt:4},images={},status={},views={},hero=null,lastScan=0;
function cadence(k){return{ghoul:145,zombie:285,ghost:210,troll:315}[k]||230;}
function attackMs(k){return{ghoul:155,zombie:240,ghost:185,troll:310}[k]||220;}
Object.keys(META).forEach(function(key){var im=new Image(),m=META[key];images[key]=im;status[key]='loading';im.decoding='async';im.onload=function(){if(im.naturalWidth!==m.fw*5||im.naturalHeight!==m.fh){status[key]='failed';console.warn('IPS v1.11.5 '+key+' sprite dimensions rejected.',im.naturalWidth,im.naturalHeight);return;}status[key]='ready';scan(true);};im.onerror=function(){status[key]='failed';};im.src=m.src+'?v=115';});
function now(){return performance.now();}function enemyId(el){return el&&el.getAttribute('data-enemy-id');}
function keyFromName(name){var n=(name||'').toLowerCase();if(n.indexOf('undertaker')>=0)return'undertaker';if(n.indexOf('dead-eye')>=0||n.indexOf('dead eye')>=0)return'deadeye';if(n.indexOf('big hank')>=0)return'hank';if(n.indexOf('nevermore')>=0)return'nevermore';if(n.indexOf('last train')>=0)return'train';if(n.indexOf('troll')>=0)return'troll';if(n.indexOf('ghost')>=0||n.indexOf('wraith')>=0||n.indexOf('specter')>=0||n.indexOf('gunner')>=0||n.indexOf('gunhand')>=0)return'ghost';if(n.indexOf('ghoul')>=0||n.indexOf('hound')>=0||n.indexOf('stalker')>=0)return'ghoul';return'zombie';}
function makeCanvas(host,id,key){var m=META[key],c,ctx;if(!m)return null;c=host.querySelector('canvas.sprite-v115');if(!c){c=document.createElement('canvas');c.className='sprite-v110 sprite-v115 sprite-'+key;c.width=m.fw;c.height=m.fh;c.dataset.entityId=id||'';c.dataset.spriteKey=key;c.setAttribute('aria-hidden','true');host.appendChild(c);ctx=c.getContext('2d');ctx.imageSmoothingEnabled=false;if('webkitImageSmoothingEnabled'in ctx)ctx.webkitImageSmoothingEnabled=false;}if(status[key]==='ready')host.classList.add('sprite-v110-ready');return c;}
function view(el){var id=enemyId(el),host=el&&el.querySelector('.unit-figure'),name=el&&el.querySelector('.enemy-name'),key,v,c;if(!id||!host)return null;key=keyFromName(name&&name.textContent);el.dataset.spriteKey=key;if(name&&/Wraith Deputy/i.test(name.textContent||''))el.dataset.summoned='1';if(!META[key]){host.classList.remove('sprite-v110-ready');return null;}v=views[id];if(!v||v.key!==key){c=makeCanvas(host,id,key);if(!c)return null;v=views[id]={id:id,key:key,el:el,host:host,c:c,ctx:c.getContext('2d'),state:'idle',until:0,lastX:null,lastMove:0,phase:id.length%2,frame:-1};v.ctx.imageSmoothingEnabled=false;}else{v.el=el;v.host=host;if(!v.c.isConnected){v.c=makeCanvas(host,id,key);if(!v.c)return null;v.ctx=v.c.getContext('2d');v.ctx.imageSmoothingEnabled=false;v.frame=-1;}}if(status[key]==='ready')host.classList.add('sprite-v110-ready');return v;}
function heroView(){var host=document.querySelector('.hero-art'),unit=document.getElementById('heroUnit'),c;if(!host)return null;if(!hero||!hero.c.isConnected){c=makeCanvas(host,'hero','hero');if(!c)return null;hero={id:'hero',key:'hero',el:unit,host:host,c:c,ctx:c.getContext('2d'),state:'idle',until:0,phase:0,frame:-1};hero.ctx.imageSmoothingEnabled=false;}if(status.hero==='ready')host.classList.add('sprite-v110-ready');return hero;}
function priority(s){return{idle:0,move:1,attack:2,hurt:3,death:4}[s]||0;}function setState(v,state,ms){if(!v)return;var n=now();if(n>=v.until||priority(state)>=priority(v.state)){v.state=state;v.until=ms?n+ms:0;v.frame=-1;}}
function syncClass(v){if(!v||!v.el)return;v.el.classList.toggle('sprite-hurt',v.state==='hurt'||v.state==='death');v.el.classList.toggle('sprite-attack',v.state==='attack');v.el.classList.toggle('sprite-moving',v.state==='move');}
function frameFor(v,t){if(v.state==='hurt'||v.state==='death')return FRAME.hurt;if(v.state==='attack')return FRAME.attack;if(v.state==='move')return((Math.floor(t/cadence(v.key))+v.phase)&1)?FRAME.moveA:FRAME.moveB;if(v.key==='hero')return(Math.floor(t/1500)&1)?FRAME.moveA:FRAME.idle;if(v.key==='ghost')return(Math.floor(t/920)&1)?FRAME.moveA:FRAME.idle;return FRAME.idle;}
function draw(v,t){if(!v||status[v.key]!=='ready')return;var im=images[v.key],m=META[v.key],f,ctx;if(v.until&&t>=v.until){v.state='idle';v.until=0;v.frame=-1;}f=frameFor(v,t);if(f===v.frame){syncClass(v);return;}v.frame=f;ctx=v.ctx;ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,m.fw,m.fh);ctx.drawImage(im,f*m.fw,0,m.fw,m.fh,0,0,m.fw,m.fh);syncClass(v);}
function motion(v,t){var s=v.el&&v.el.style.transform||'',m=/translate3d\((-?[\d.]+)px/.exec(s),x=m?Number(m[1]):0;if(v.lastX===null)v.lastX=x;if(Math.abs(x-v.lastX)>.08){v.lastX=x;v.lastMove=t;if(v.state==='idle')v.state='move';}else if(v.state==='move'&&t-v.lastMove>Math.max(190,cadence(v.key))){v.state='idle';}if(v.el&&v.el.classList.contains('enemy-lunge'))setState(v,'attack',attackMs(v.key));}
function scan(force){var t=now(),els,live={},i,v;if(!force&&t-lastScan<120)return;lastScan=t;els=document.querySelectorAll('#enemyLane .enemy');for(i=0;i<els.length;i++){v=view(els[i]);if(v)live[v.id]=1;}Object.keys(views).forEach(function(id){if(!live[id])delete views[id];});heroView();}
function currentHit(){var el=document.querySelector('#enemyLane .enemy.hit');return el?views[enemyId(el)]||view(el):null;}
function attacker(){var el=document.querySelector('#enemyLane .enemy.enemy-lunge');return el?views[enemyId(el)]||view(el):null;}
document.addEventListener('ips:shot',function(){setState(heroView(),'attack',145);});document.addEventListener('ips:heroHit',function(){setState(heroView(),'hurt',210);setState(attacker(),'attack',220);});document.addEventListener('ips:heroDeath',function(){setState(heroView(),'death',900);});document.addEventListener('ips:enemyHit',function(){setState(currentHit(),'hurt',165);});document.addEventListener('ips:enemyDeath',function(){setState(currentHit(),'death',380);});document.addEventListener('ips:waveStart',function(){setTimeout(function(){scan(true);},0);});
function loop(t){scan(false);Object.keys(views).forEach(function(id){motion(views[id],t);draw(views[id],t);});draw(heroView(),t);requestAnimationFrame(loop);}
function boot(){scan(true);var lane=document.getElementById('enemyLane');if(lane)new MutationObserver(function(){scan(true);}).observe(lane,{childList:true,subtree:true});requestAnimationFrame(loop);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(boot,120);});else setTimeout(boot,120);
window.__ipsSpriteV115={refresh:function(){scan(true);},meta:META,status:status};
})();
