(function(){
'use strict';
var content=document.getElementById('sheetContent'),savedAnchor=null,armor={current:0,max:0};
function $q(s,r){return (r||document).querySelector(s);}function $qa(s,r){return Array.prototype.slice.call((r||document).querySelectorAll(s));}
function esc(v){return String(v).replace(/"/g,'\\"');}
function selectorFor(btn){var attrs=['data-hero','data-board','data-ammo-rank','data-ammo-qty','data-ammo-unlock','data-ammo-load','data-blueprint-buy','data-chamber'];for(var i=0;i<attrs.length;i++){var a=attrs[i],v=btn.getAttribute&&btn.getAttribute(a);if(v!==null)return'['+a+'="'+esc(v)+'"]';}return null;}
function captureAnchor(e){if(!content)return;var btn=e.target&&e.target.closest?e.target.closest('button'):null;if(!btn||!content.contains(btn))return;var sel=selectorFor(btn),r=btn.getBoundingClientRect(),cr=content.getBoundingClientRect();savedAnchor={selector:sel,offset:r.top-cr.top,scroll:content.scrollTop,until:performance.now()+700};}
function restoreAnchor(){if(!savedAnchor||!content||performance.now()>savedAnchor.until)return;var target=savedAnchor.selector?$q(savedAnchor.selector,content):null;if(target){var r=target.getBoundingClientRect(),cr=content.getBoundingClientRect();content.scrollTop+=r.top-cr.top-savedAnchor.offset;}else content.scrollTop=savedAnchor.scroll;}
function arrangeBlueprints(){if(!content)return;var desk=$q('.research-desk',content);if(!desk)return;var title=(document.getElementById('sheetTitle')||{}).textContent||'',target=null;if(/Pachinko/i.test(title))target=$q('.upgrade-grid',content);else if(/Ammo/i.test(title))target=$q('.ammo-grid',content);if(target&&target.nextElementSibling!==desk)target.insertAdjacentElement('afterend',desk);}
function tuneText(type,rank){var s='Each Tune rank adds +4% multiplicative impact damage.';if(type==='concuss')s+=' Stun duration: '+(1.4+rank*.25).toFixed(2)+'s → '+(1.4+(rank+1)*.25).toFixed(2)+'s.';if(type==='poison')s+=' Cloud duration: '+(5+Math.min(3,rank*.5)).toFixed(1)+'s → '+(5+Math.min(3,(rank+1)*.5)).toFixed(1)+'s.';return s;}
function explainAmmoTuning(){if(!content||!window.__ipsAPI)return;var snap=window.__ipsAPI.snapshot(),buttons=$qa('[data-ammo-rank]',content);buttons.forEach(function(btn){var type=btn.getAttribute('data-ammo-rank'),card=btn.closest('.ammo-card');if(!card||card.querySelector('.tune-explainer'))return;var p=document.createElement('p');p.className='tune-explainer';p.textContent=tuneText(type,Number((snap.ammoRank&&snap.ammoRank[type])||0));btn.parentNode.insertBefore(p,btn);});}
function threatTitle(el){var out=[];if(el.classList.contains('role-melee'))out.push('Melee');if(el.classList.contains('role-ranged'))out.push('Ranged');if(el.classList.contains('role-hybrid'))out.push('Hybrid');if(el.classList.contains('armored'))out.push('Armored');if(el.classList.contains('regenerating'))out.push('Regenerates');if(el.classList.contains('spectral'))out.push('Spectral');if(el.classList.contains('warded'))out.push('Warded');if(el.classList.contains('stunned'))out.push('Stunned');if(el.classList.contains('burning'))out.push('Burning');return out.join(', ');}
function decorateEnemies(){var lane=document.getElementById('enemyLane');if(!lane)return;$qa('.enemy',lane).forEach(function(el){var old=$q('.threat-icons',el);if(old)old.remove();var bar=$q('.hp-track',el),icons=document.createElement('div'),parts=[];icons.className='threat-icons';if(el.classList.contains('role-melee'))parts.push(['⚔','Melee']);else if(el.classList.contains('role-ranged'))parts.push(['➶','Ranged']);else if(el.classList.contains('role-hybrid'))parts.push(['◈','Hybrid']);if(el.classList.contains('armored'))parts.push(['▣','Armor']);if(el.classList.contains('regenerating'))parts.push(['↻','Regen']);if(el.classList.contains('spectral'))parts.push(['✧','Spectral']);if(el.classList.contains('warded'))parts.push(['⬡','Ward']);if(el.classList.contains('stunned'))parts.push(['✹','Stunned']);for(var i=0;i<parts.length;i++){var s=document.createElement('span');s.textContent=parts[i][0];s.setAttribute('aria-label',parts[i][1]);icons.appendChild(s);}icons.title=threatTitle(el);el.insertBefore(icons,el.firstChild);if(bar){bar.setAttribute('aria-label',Math.round(parseFloat(($q('.hp-fill',bar)||{}).style&&parseFloat($q('.hp-fill',bar).style.width)||0))+'% health remaining');}});}
function ensureArmorBar(){var hero=document.getElementById('heroUnit'),hp=hero&&$q('.hp-track',hero);if(!hero||!hp)return null;var t=$q('.hero-armor-track',hero);if(!t){t=document.createElement('div');t.className='hero-armor-track';t.innerHTML='<i></i>';hp.insertAdjacentElement('afterend',t);}return t;}
function paintArmor(){var t=ensureArmorBar();if(!t)return;t.classList.toggle('active',armor.max>0);var f=$q('i',t);if(f)f.style.width=(armor.max?Math.max(0,Math.min(100,armor.current/armor.max*100)):0)+'%';t.title=armor.max?Math.ceil(armor.current)+' / '+Math.ceil(armor.max)+' armor':'';}
function refreshSheet(){arrangeBlueprints();explainAmmoTuning();requestAnimationFrame(restoreAnchor);setTimeout(restoreAnchor,35);setTimeout(restoreAnchor,120);}
if(content){content.addEventListener('pointerdown',captureAnchor,true);content.addEventListener('click',captureAnchor,true);new MutationObserver(refreshSheet).observe(content,{childList:true,subtree:true});}
var lane=document.getElementById('enemyLane');if(lane)new MutationObserver(function(){requestAnimationFrame(decorateEnemies);}).observe(lane,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});
document.addEventListener('ips:menu',function(){setTimeout(refreshSheet,25);});
document.addEventListener('ips:upgrade',function(){setTimeout(refreshSheet,25);});
document.addEventListener('ips:ammoLoad',function(){setTimeout(refreshSheet,25);});
document.addEventListener('ips:waveStart',function(e){var d=e.detail||{},snap=window.__ipsAPI&&window.__ipsAPI.snapshot?window.__ipsAPI.snapshot():{};armor.max=Number(d.armorMax!==undefined?d.armorMax:Number(snap.armor||0)*10);armor.current=Number(d.armor!==undefined?d.armor:armor.max);paintArmor();});
document.addEventListener('ips:runStart',function(e){var d=e.detail||{},snap=window.__ipsAPI&&window.__ipsAPI.snapshot?window.__ipsAPI.snapshot():{};armor.max=Number(d.armorMax!==undefined?d.armorMax:Number(snap.armor||0)*10);armor.current=Number(d.armor!==undefined?d.armor:armor.max);paintArmor();});
document.addEventListener('ips:heroHit',function(e){var d=e.detail||{};if(d.armorMax!==undefined)armor.max=Number(d.armorMax||0);if(d.armor!==undefined)armor.current=Number(d.armor||0);paintArmor();});
setTimeout(function(){decorateEnemies();refreshSheet();var snap=window.__ipsAPI&&window.__ipsAPI.snapshot?window.__ipsAPI.snapshot():{};armor.max=Number(snap.armor||0)*10;armor.current=armor.max;paintArmor();},500);
})();
